-- ARKHER :: Continuum V2 verification (continuum / epoch / sparse / multiscale / persistent / coherence / neuralfield + runtimes)
local A = ARKHER
local TestKit = A:import("arkher/kernel/testkit")
local Kits = A:import("arkher/runtime/kits")
local Vec = A:import("arkher/kernel/vec")
local v3 = Vec.vec3
local t = TestKit.new()

t:describe("continuum/kits", function(s)
	s:it("continuum pages with hysteresis and seams", function(a)
		local cont = Kits.create("continuum", { id = "test.cont", cellSize = 64, radius = 160, horizon = 1024 })
		a:equal(cont.cellOf(0,0).key, "0:0")
		a:equal(cont.span(), 3)
		cont.update(0,0)
		local pumped = cont.pump(16)
		a:gte(pumped, 4)
		a:gte(cont.loadedCount(), 4)
		a:ok(cont.isLoaded(0,0))
		a:ok(cont.isLoadedKey("0:0"))
		local key = cont.cellOf(0,0).key
		a:gte(#cont.neighbors(key), 0)
		a:gte(cont.checksum(), 0)
		a:gte(cont.stats().coherence, 0)
		-- hysteresis: far move should unload after pump after hysteresis distance
		cont.update(10000, 10000)
		cont.pump(16)
		a:gte(cont.stats().unloads, 0)
		a:gte(cont.stats().seams, 0)
	end)

	s:it("epoch advances, checkpoints and catches up", function(a)
		local ep = Kits.create("epoch", { id = "test.epoch", tickRate = 20, budget = 8, capacity = 64 })
		a:equal(ep.epoch, 0)
		local ticks = ep.advance(0.2)
		a:gte(ticks, 3)
		a:gte(ep.epoch, 3)
		a:equal(ep.epochNow(), ep.epoch)
		a:gte(ep.elapsedSince(0), 1)
		a:gte(ep.drift(), 0)
		local cp = ep.checkpoint()
		a:equal(cp.epoch, ep.epoch)
		ep.advance(0.5)
		a:gt(ep.epoch, cp.epoch)
		ep.restore(cp)
		a:equal(ep.epoch, cp.epoch)
		local target = ep.epoch + 4
		local caught = ep.catchUp(target)
		a:equal(caught, 4)
		a:equal(ep.epoch, target)
		a:gte(ep.setDilation(1.5), 1.4)
		a:gte(ep.stats().catchups, 1)
	end)

	s:it("sparse residency with LRU, pin and eviction", function(a)
		local sp = Kits.create("sparse", { id = "test.sparse", capacity = 4, pageBytes = 1024 })
		a:ok(sp.write("a", { v = 1 }))
		a:ok(sp.write("b", { v = 2 }))
		a:ok(sp.read("a") ~= nil)
		a:equal(sp.read("a").v, 1)
		a:ok(sp.isResident("a"))
		a:ok(sp.pin("a"))
		a:ok(sp.touch("a"))
		a:gte(sp.residentBytes(), 1024)
		a:gte(sp.compressionRatio(), 0)
		-- fill beyond capacity, pinned should survive
		sp.write("c", { v = 3 })
		sp.write("d", { v = 4 })
		sp.write("e", { v = 5 })
		a:lte(sp.stats().pages, 4)
		a:gte(sp.stats().evictions, 1)
		a:ok(sp.has("a"), "pinned a must survive eviction")
		a:ok(sp.unpin("a"))
		a:equal(sp.hitRate() > 0, true)
		a:gte(sp.evict(1), 0)
	end)

	s:it("multiscale selects level with hysteresis and budget eviction", function(a)
		local ms = Kits.create("multiscale", { id = "test.ms", levels = 4, baseTriangles = 80000 })
		a:lte(ms.levelFor(10), ms.levelFor(5000))
		a:gte(ms.costAt(0), ms.costAt(3))
		local lvl, cost = ms.request("obj1", 10)
		a:gte(lvl, 0)
		a:gte(cost, 0)
		ms.request("obj2", 4000)
		a:gte(#ms.visibleLevels(), 1)
		a:gte(ms.totalCost(), cost)
		a:gte(ms.coherence(), 0)
		a:gte(ms.coherence(), 0)
		local ev = ms.evictToBudget(5000)
		a:gte(ev, 0)
		a:lte(ms.totalCost(), 200000)
	end)

	s:it("persistent commits, diffs and rollback", function(a)
		local ps = Kits.create("persistent", { id = "test.persist", capacity = 16 })
		local c1 = ps.commit(1, { tick = 1, v = 10 })
		a:ok(c1 ~= nil)
		local c2 = ps.commit(2, { tick = 2, v = 20 })
		a:ok(ps.read(1) ~= nil)
		a:equal(ps.read(1).state.v, 10)
		a:ok(ps.verify(1))
		local diff, _, changed = ps.diff(1, 2)
		a:ok(diff ~= nil)
		-- rollback to 1 should truncate
		a:ok(ps.rollback(1))
		a:equal(ps.stats().head, 1)
		local cp = ps.checkpoint()
		a:gte(cp.count, 1)
		a:ok(ps.restore(cp))
		a:gte(ps.stats().writes, 2)
	end)

	s:it("coherence observes and scores", function(a)
		local coh = Kits.create("coherence", { id = "test.coh", window = 16, threshold = 0.12 })
		for i=1, 10 do coh.observe({ coherence = 0.9 - i*0.01, drift = 0.04, cost = 40000, budget = 80000 }) end
		a:gte(coh.score(), 0)
		a:lte(coh.score(), 1)
		a:isType(coh.isCoherent(), "boolean")
		a:gte(coh.driftValue(), 0)
		a:gte(coh.pressure(), 0)
		a:gte(coh.stats().checks, 10)
		a:ok(coh.reset())
		a:equal(coh.stats().checks, 0)
	end)

	s:it("neuralfield encodes, infers and quantizes", function(a)
		local nf = Kits.create("neuralfield", { id = "test.nf", dims = 12, hidden = 8, seed = 42 })
		local enc = nf.encode(0.5, 1)
		a:equal(#enc, 12)
		local out = nf.infer(enc)
		a:isType(out, "number")
		a:gte(out, 0)
		a:lte(out, 1)
		a:gte(nf.forward(enc), 0)
		local ds = nf.generateDataset(10)
		a:equal(#ds, 10)
		local loss = nf.train({ { enc, 0.8 } }, 2)
		a:gte(loss, 0)
		local q = nf.quantize(8)
		a:equal(q.bits, 8)
		a:gte(nf.memoryBytes(), 100)
		local tbl = nf.exportTable()
		a:ok(tbl.W1 ~= nil)
		a:ok(nf.importTable(tbl))
	end)
end)

t:describe("continuum/runtimes", function(s)
	s:it("WorldContinuum steps, pumps and checkpoints", function(a)
		local WC = A:import("arkher/continuum/world_continuum")
		local wc = WC.new({ id = "test.wc", cellSize = 64, radius = 160, sparseCap = 64 })
		wc:registerObject("o1", v3(0,0,0), { lodBias = 1 })
		wc:registerObject("o2", v3(5000,0,5000), { lodBias = 0.5 })
		local r = wc:step(0, 0, 1/20)
		a:gte(r.pumped, 0)
		a:gte(r.loaded, 0)
		a:gte(r.coherence, 0)
		a:gte(r.totalCost, 0)
		local cp = wc:checkpoint()
		a:gte(cp.checksum, 0)
		wc:step(10000, 10000, 1/20)
		a:ok(wc:restore(cp))
		a:equal(wc:checksum(), cp.checksum)
		a:gte(wc:catchUp(2), 0)
		a:gte(wc:loadedCount(), 0)
		local before = wc:report().epoch
		wc:step(0,0,1/20)
		a:gte(wc:report().epoch, before)
	end)

	s:it("NeuralContinuum measures frames and adapts scale", function(a)
		local NC = A:import("arkher/continuum/neural_continuum")
		local nc = NC.new({ id = "test.nc", budgetMs = 16, dims = 12, hidden = 8, seed = 99 })
		local m = nc:measureFrame(10)
		a:gte(m.predicted, 0)
		a:isType(m.scale, "number")
		-- heavy frames should push scale down after hysteresis
		for _=1, 6 do nc:measureFrame(30) end
		local down = nc:measureFrame(30)
		a:lte(down.scale, 1.0)
		-- light frames pull scale up
		for _=1, 8 do nc:measureFrame(2) end
		local up = nc:measureFrame(2)
		a:gte(up.scale, down.scale)
		a:gte(nc:trainForDevice(4), 0)
		local q = nc:quantizeAndExport(8)
		a:equal(q.bits, 8)
		local enc = nc.field.encode(0.2, 1)
		a:gte(nc.field.infer(enc), 0)
		a:gte(nc:report().coherence, 0)
	end)

	s:it("SimulationContinuum steps domains with budgeting", function(a)
		local SC = A:import("arkher/continuum/simulation_continuum")
		local sc = SC.new({ id = "test.sc", tickRate = 10, sparseCap = 32 })
		sc:addDomain("test", { hz = 10, priority = 1, budget = 0.35, stepFn = function() return 1 end })
		-- defaults
		sc:installDefaults()
		a:gte(#sc.order, 4)
		local r = sc:step(1/10, 6)
		a:gte(r.spent, 0)
		a:gte(r.coherence, 0)
		a:gte(sc:report().epoch, 1)
		local cp = sc:checkpoint()
		a:ok(cp.epoch ~= nil)
		a:ok(sc:restore(cp))
		a:gte(sc:catchUp(0.5), 0)
		a:ok(sc:report().domains.test ~= nil)
	end)

	s:it("ArchitectContinuum composes with budget conservation", function(a)
		local AC = A:import("arkher/continuum/architect_continuum")
		local arch = AC.new({ id = "test.arch", budget = 1200 })
		local res = arch:compose({ target = "city", quantity = 40, density = 1 })
		a:gte(res.nodes, 7)
		a:gte(res.districts, 1)
		a:gte(res.budget, 100)
		a:lte(res.allocated, res.budget)
		a:ok(arch:coherent())
		local prog = arch:programme()
		a:equal(#prog, #arch.order)
		-- roads before buildings
		local idx = {}
		for i, id in ipairs(prog) do idx[id]=i end
		-- check at least terrain before roads when present
		if idx["city.terrain"] and idx["city.roads"] then a:lt(idx["city.terrain"], idx["city.roads"]) end
		a:gte(arch:estimate(1), 0)
		a:gte(arch:checksum(), 0)
		a:gte(arch:stats().composed, 1)
	end)

	s:it("WorldContinuum integrates continuum + sparse + multiscale + epoch", function(a)
		local WC = A:import("arkher/continuum/world_continuum")
		local wc = WC.new({ id = "test.integ", cellSize = 128, radius = 320 })
		-- place objects at varying distances
		for i=1, 10 do wc:registerObject("obj"..i, v3(i*30,0,0), { lodBias = 1, importance = i%3==0 and 2 or 1 }) end
		local beforeCost = wc:totalCost()
		wc:step(0,0,1/20)
		a:gte(wc:totalCost(), 0)
		-- cost should be budgeted
		a:gte(wc:report().budget, 1000)
		a:gte(wc.temporal.epoch, 0)
		a:gte(wc.sparse.stats().pages, 0)
		a:gte(wc.multiscale.levelFor(10), 0)
		wc:removeObject("obj1")
		a:equal(wc.objects["obj1"], nil)
	end)
end)

local r=t:run(); t:report(); return r
