-- ARKHER :: Round 7 verification (VFX, audio, gameplay, UI, networking)
local A = ARKHER
local TestKit = A:import("arkher/kernel/testkit")
local Kits = A:import("arkher/runtime/kits")
local Vec = A:import("arkher/kernel/vec")
local v3 = Vec.vec3
local t = TestKit.new()

t:describe("experience/kits", function(s)
	s:it("emitter emits by rate, by burst and inside a budget", function(a)
		local em = Kits.create("emitter", { id = "e", shape = "cone", rate = 60,
			speed = 10, life = 1, budget = 40, seed = 5 })
		local first = em.emit(0.5, 0)
		a:equal(#first, 30)
		a:equal(em.stats().emitted, 30)
		em.burst(10, 0.5)
		local second = em.emit(0.1, 0)
		a:gte(#second, 10)
		-- the budget is a hard ceiling: nothing is emitted into a full system
		local blocked = em.emit(1, 40)
		a:equal(#blocked, 0)
		a:gt(em.stats().dropped, 0)
		local spec = em.sampleSpec()
		a:ok(spec.position ~= nil and spec.velocity ~= nil)
		a:gt(spec.velocity:length(), 0)
		a:gt(spec.life, 0)
		em.setShape("sphere", { radius = 3 })
		local p = em.samplePosition()
		a:lte(p:length(), 3.001)
		em.pause()
		a:equal(#em.emit(1, 0), 0)
		em.resume()
		local low = em.applyQuality(0.1)
		a:lt(low.budget, 40)
	end)

	s:it("particles integrate, age out and respect the pool", function(a)
		local ps = Kits.create("particles", { id = "p", capacity = 8,
			gravity = v3(0, -10, 0), drag = 0, groundY = 0, bounce = 0.5 })
		for i = 1, 10 do
			ps.spawn({ position = v3(0, 5, 0), velocity = v3(1, 0, 0), life = 2, size = 1 })
		end
		a:equal(ps.aliveCount(), 8, "the pool is a hard limit")
		ps.step(0.1)
		local p = ps.particleAt(1)
		a:lt(p.position.y, 5)
		a:gt(p.position.x, 0)
		-- a particle bounces off the ground instead of falling through it
		for _ = 1, 60 do ps.step(1 / 60) end
		a:gte(ps.particleAt(1) and ps.particleAt(1).position.y or 0, 0)
		local bounds = ps.bounds()
		a:ok(bounds ~= nil)
		for _ = 1, 80 do ps.step(1 / 60) end
		a:equal(ps.aliveCount(), 0, "everything must die at the end of its life")
		a:gt(ps.stats().killed, 0)
		a:equal(ps.occupancy(), 0)
	end)

	s:it("force fields push, pull, swirl and drag", function(a)
		local ff = Kits.create("forcefield", { id = "f", seed = 3 })
		ff.addField("wind", "wind", { direction = v3(1, 0, 0), strength = 5 })
		a:near(ff.evaluate(v3(), v3()).x, 5, 0.001)
		ff.addField("pull", "radial", { position = v3(10, 0, 0), strength = -8, radius = 20 })
		local force = ff.evaluate(v3(0, 0, 0), v3())
		a:gt(force.x, 5, "the attractor at +x must pull on top of the wind")
		ff.setEnabled("wind", false)
		a:gt(ff.evaluate(v3(), v3()).x, 0)
		ff.addField("swirl", "vortex", { position = v3(), direction = v3(0, 1, 0),
			strength = 6, radius = 20 })
		local swirl = ff.evaluate(v3(2, 0, 0), v3())
		a:gt(math.abs(swirl.z), 0)
		ff.addField("air", "drag", { strength = 2 })
		local damped = ff.evaluate(v3(2, 0, 0), v3(0, 0, 10))
		a:lt(damped.z, swirl.z)
		a:equal(ff.fieldCount(), 4)
		a:ok(ff.removeField("air"))
		a:equal(ff.fieldCount(), 3)
		a:gt(ff.stats().evaluations, 3)
	end)

	s:it("ribbon trails follow, fade and decimate", function(a)
		local r = Kits.create("ribbon", { id = "r", maxPoints = 8, lifetime = 1,
			minDistance = 0.5, width = 1 })
		for i = 1, 6 do r.push(v3(i, 0, 0)) end
		a:equal(r.stats().points, 6)
		a:ok(not r.push(v3(6.1, 0, 0)), "a point too close to the last is merged")
		a:near(r.length(), 5, 0.001)
		local verts = r.vertices(v3(0, 10, 0))
		a:equal(#verts, 12)
		a:gt(r.widthAt(6), r.widthAt(1))
		for _ = 1, 12 do r.update(0.1) end
		a:equal(r.stats().points, 0, "the trail must expire")
		a:equal(r.beam(v3(), v3(10, 0, 0), 8, 2), 9)
		local kept = r.simplify(0.01)
		a:lte(kept, 9)
		a:gt(r.clear(), 0)
	end)

	s:it("dsp filters, delays and meters a real signal", function(a)
		local d = Kits.create("dsp", { id = "d", sampleRate = 8000, filter = "lowpass",
			cutoff = 400 })
		local low = d.tone(100, 400, 1)
		local high = d.tone(3000, 400, 1)
		local lowOut = d.process(low)
		d.reset()
		local highOut = d.process(high)
		a:gt(d.rms(lowOut), d.rms(highOut), "a lowpass must keep bass and kill treble")
		d.setFilter("highpass", 1500)
		d.reset()
		local hp = d.process(high)
		d.reset()
		local hpLow = d.process(low)
		a:gt(d.rms(hp), d.rms(hpLow))
		a:lte(d.peak(hp), 1.01, "the soft clipper must keep the signal bounded")
		a:equal(d.setDelay(0.01, 0.4, 0.5), 80)
		d.process(d.tone(200, 200, 1))
		a:gt(d.stats().processed, 1000)
		a:gt(d.stats().envelope, 0)
	end)

	s:it("mixer routes, mutes, ducks and steals voices", function(a)
		local m = Kits.create("mixer", { id = "m", maxVoices = 2 })
		m.addBus("master")
		m.addBus("sfx", { parent = "master", gainDb = -6 })
		a:near(m.effectiveGain("sfx"), 0.5011, 0.01)
		m.setGain("master", -6)
		a:lt(m.effectiveGain("sfx"), 0.3)
		m.setMute("master", true)
		a:equal(m.effectiveGain("sfx"), 0)
		m.setMute("master", false)
		m.duck("sfx", 0.8)
		m.tick(1)
		a:lt(m.effectiveGain("sfx"), 0.1)
		m.duck("sfx", 0)
		m.tick(2)
		a:gt(m.effectiveGain("sfx"), 0.1)
		a:ok(m.play("v1", "sfx", 1))
		a:ok(m.play("v2", "sfx", 1))
		a:ok(not m.play("v3", "sfx", 1), "an equal-priority voice must not steal")
		a:ok(m.play("v4", "sfx", 5), "a more important voice must steal a slot")
		a:equal(m.stats().steals, 1)
		local snap = m.snapshot()
		m.setGain("master", 0)
		m.restore(snap)
		a:equal(m.buses.master.gainDb, -6)
	end)

	s:it("spatial audio attenuates, pans and culls", function(a)
		local sa = Kits.create("spatialaudio", { id = "sa", refDistance = 5,
			maxDistance = 100, maxVoices = 2 })
		sa.setListener(v3(), v3(0, 0, -1), v3(0, 1, 0))
		sa.addSource("near", v3(0, 0, 5), { volume = 1, priority = 1 })
		sa.addSource("right", v3(20, 0, 0), { volume = 1, priority = 1 })
		sa.addSource("far", v3(0, 0, 95), { volume = 1, priority = 1 })
		a:equal(sa.gainOf("near"), 1)
		a:lt(sa.gainOf("far"), 0.2)
		a:gt(sa.pan(v3(20, 0, 0)), 0.9)
		a:lt(sa.pan(v3(-20, 0, 0)), -0.9)
		sa.setOcclusion("near", 1)
		a:lt(sa.gainOf("near"), 0.3)
		sa.setOcclusion("near", 0)
		-- moving toward the listener raises the pitch, away lowers it
		sa.moveSource("right", v3(20, 0, 0), v3(-30, 0, 0))
		a:gt(sa.doppler("right"), 1)
		sa.moveSource("right", v3(20, 0, 0), v3(30, 0, 0))
		a:lt(sa.doppler("right"), 1)
		local live = sa.cullVoices()
		a:equal(#live, 2)
		a:gt(sa.stats().culled, 0)
		local mix = sa.mixSnapshot()
		a:equal(#mix, 2)
		a:ok(mix[1].gain >= mix[2].gain)
	end)

	s:it("sequencer keeps musical time and fires cues", function(a)
		local sq = Kits.create("sequencer", { id = "sq", bpm = 120 })
		sq.addSection("explore", 8)
		sq.addSection("combat", 8)
		sq.addLayer("pad", { threshold = 0, fade = 0.2 })
		sq.addLayer("drums", { threshold = 0.5, fade = 0.2 })
		sq.addCue("hit", 2)
		sq.addCue("swell", 6)
		sq.setIntensity(0.2)
		sq.play()
		a:near(sq.beatDuration(), 0.5, 0.001)
		local fired = sq.advance(1.2)
		a:equal(#fired, 1)
		a:equal(fired[1].name, "hit")
		a:equal(sq.stats().current, "explore")
		local at = sq.transitionTo("combat", 4)
		a:gte(at, 4)
		sq.setIntensity(0.9)
		sq.advance(2.0)
		a:equal(sq.stats().current, "combat")
		a:gt(sq.layerGain("drums"), 0.3)
		a:equal(#sq.activeLayers(), 2)
		sq.advance(2.0)
		a:equal(sq.stats().fired, 2)
		a:gt(sq.bar(), 1)
	end)

	s:it("stats stack modifiers in the right order and expire", function(a)
		local st = Kits.create("stats", { id = "st" })
		st.define("power", 10, { min = 0, max = 1000 })
		a:equal(st.get("power"), 10)
		st.addModifier("power", "sword", { flat = 5 })
		a:equal(st.get("power"), 15)
		st.addModifier("power", "rage", { percent = 0.5 })
		a:near(st.get("power"), 22.5, 0.001)
		st.addModifier("power", "blessing", { multiplier = 2, duration = 1 })
		a:near(st.get("power"), 45, 0.001)
		st.tick(1.5)
		a:near(st.get("power"), 22.5, 0.001, "a timed buff must expire")
		a:equal(st.removeModifier("sword"), 1)
		a:near(st.get("power"), 15, 0.001)
		st.defineDerived("dps", function(s) return s.get("power") * 2 end)
		a:equal(st.getDerived("dps"), 30)
		a:gt(st.stats().recomputes, 3)
		a:equal(#st.modifiersFor("power"), 1)
	end)

	s:it("inventory stacks, weighs, equips and crafts", function(a)
		local inv = Kits.create("inventory", { id = "inv", slots = 4, maxWeight = 20 })
		inv.defineItem("wood", { stack = 10, weight = 1, value = 2 })
		inv.defineItem("iron", { stack = 10, weight = 2, value = 5 })
		inv.defineItem("axe", { stack = 1, weight = 4, slot = "hand", value = 30 })
		a:equal(inv.add("wood", 12), 12)
		a:equal(inv.countOf("wood"), 12)
		a:equal(inv.stats().used, 2, "12 wood must fit in two stacks of 10")
		a:equal(inv.weight(), 12)
		local added = inv.add("iron", 10)
		a:lt(added, 10, "the weight limit must stop the last items")
		a:gt(inv.stats().rejected, 0)
		inv.addRecipe("makeAxe", { wood = 5, iron = 2 }, { axe = 1 })
		a:ok(inv.canCraft("makeAxe"))
		a:ok(inv.craft("makeAxe"))
		a:equal(inv.countOf("axe"), 1)
		a:equal(inv.countOf("wood"), 7)
		a:ok(inv.equip("axe"))
		a:equal(inv.equipment.hand, "axe")
		a:equal(inv.countOf("axe"), 0)
		local other = Kits.create("inventory", { id = "chest", slots = 8, maxWeight = 100 })
		a:equal(inv.moveTo(other, "wood", 5), 5)
		a:equal(other.countOf("wood"), 5)
		local blob = inv.serialize()
		inv.deserialize(blob)
		a:equal(inv.countOf("wood"), 2)
		a:gt(inv.totalValue(), 0)
	end)

	s:it("quests chain, track objectives and complete", function(a)
		local q = Kits.create("quest", { id = "q" })
		q.define("gather")
		q.addObjective("gather", "wood", { required = 3, event = "collect.wood" })
		q.define("hunt", { requires = { "gather" }, rewards = { gold = 50 } })
		q.addObjective("hunt", "wolves", { required = 2, event = "kill.wolf" })
		a:equal(q.stateOf("gather"), "available")
		a:equal(q.stateOf("hunt"), "locked")
		a:ok(q.start("gather"))
		q.notify("collect.wood", 2)
		a:near(q.progress("gather"), 2 / 3, 0.001)
		a:equal(q.stateOf("gather"), "active")
		q.notify("collect.wood", 1)
		a:equal(q.stateOf("gather"), "completed")
		a:equal(q.stateOf("hunt"), "available", "finishing a quest must unlock the next")
		a:ok(q.start("hunt"))
		q.notify("kill.wolf", 2)
		a:equal(q.stateOf("hunt"), "completed")
		a:equal(q.stats().completed, 2)
		a:gt(#q.recent(5), 3)
		a:equal(#q.active(), 0)
	end)

	s:it("combat resolves mitigation, crits, statuses and death", function(a)
		local c = Kits.create("combat", { id = "c", seed = 12 })
		c.addActor("hero", { health = 100, armour = 100, power = 40, accuracy = 1,
			critChance = 0, team = "player" })
			c.addActor("orc", { health = 200, armour = 0, power = 12, accuracy = 1,
			critChance = 0, team = "enemy", resistances = { fire = 0.5 } })
		-- 100 armour halves the damage at armourK = 100
		local hit = c.attack("hero", "orc", { power = 40 })
		a:near(hit.damage, 40, 0.001)
		local resisted = c.attack("hero", "orc", { power = 40, damageType = "fire" })
		a:near(resisted.damage, 20, 0.001, "a 50% resistance must halve the damage")
		local mitigated = c.attack("orc", "hero", { power = 40 })
		a:near(mitigated.damage, 20, 0.001, "armour must halve incoming damage")
		c.applyStatus("orc", "burn", { duration = 2, tickDamage = 5 })
		a:ok(c.hasStatus("orc", "burn"))
		local before = c.actors.orc.health
		c.tick(1)
		a:lt(c.actors.orc.health, before, "a damage-over-time status must bite")
		c.tick(2)
		a:ok(not c.hasStatus("orc", "burn"), "a status must expire")
		c.setCooldown("hero", "smash", 2)
		a:ok(not c.ready("hero", "smash"))
		c.tick(2.5)
		a:ok(c.ready("hero", "smash"))
		c.attack("hero", "orc", { power = 900 })
		a:equal(c.teamAlive("enemy"), 0)
		a:gt(c.stats().kills, 0)
		a:gt(c.dps("hero"), 0)
	end)

	s:it("flex layout is responsive and safe-area aware", function(a)
		local f = Kits.create("flex", { id = "f", width = 400, height = 800,
			safeArea = { top = 44, bottom = 34, left = 0, right = 0 } })
		f.addNode("root", { direction = "column", padding = 10, gap = 10 })
		f.addNode("header", { parent = "root", height = 60 })
		f.addNode("body", { parent = "root", weight = 1 })
		f.addNode("footer", { parent = "root", height = 80 })
		local rect = f.solve()
		a:equal(rect.y, 44)
		a:equal(rect.height, 800 - 44 - 34)
		local header = f.rectOf("header")
		a:equal(header.height, 60)
		a:equal(header.width, 380)
		local body = f.rectOf("body")
		a:gt(body.height, 400)
		a:equal(f.breakpoint(), "phone")
		f.setViewport(1400, 2000)
		a:equal(f.breakpoint(), "desktop")
		f.setViewport(400, 800)
		f.solve()
		a:equal(f.hitTest(200, 100), "header")
		f.setVisible("header", false)
		f.solve()
		a:gt(f.rectOf("body").height, body.height, "hiding a sibling gives room back")
		f.addNode("tiny", { parent = "root", height = 20 })
		f.solve()
		a:gt(#f.touchTargetsBelow(44), 0, "the audit must catch a 20pt touch target")
		a:equal(f.depthOf("tiny"), 1)
	end)

	s:it("input map works the same on touch, pad and keyboard", function(a)
		local im = Kits.create("inputmap", { id = "im", holdTime = 0.3, deadzone = 0.2 })
		im.bind("jump", { keys = { "Space" }, buttons = { "A" },
			touchZone = { x = 0, y = 0, width = 100, height = 100 } })
		im.bind("crouch", { keys = { "C" } })
		im.bind("slide", { chord = { "jump", "crouch" } })
		a:ok(im.press("jump"))
		a:ok(im.isDown("jump"))
		a:ok(not im.press("jump"), "a held action does not re-press")
		im.tick(0.4)
		a:ok(im.isHeld("jump"))
		im.press("crouch")
		a:ok(im.chordActive("slide"))
		a:ok(not im.release("jump"), "a long press is not a tap")
		im.press("jump")
		im.tick(0.05)
		a:ok(im.release("jump"))
		a:ok(im.wasTapped("jump"))
		a:ok(not im.wasTapped("jump"), "a tap is consumed once")
		local axis = im.setAxis("move", 0.1, 0)
		a:equal(axis.magnitude, 0, "inside the dead zone means no movement")
		axis = im.setAxis("move", 1, 0)
		a:near(axis.x, 1, 0.001)
		local stick = im.thumbstick("look", 100, 100, 160, 100, 60)
		a:gt(stick.x, 0.5)
		a:equal(im.touchAt(50, 50), "jump")
		a:equal(#im.bindingsFor("keyboard"), 2)
		a:gt(im.stats().holds, 0)
	end)

	s:it("tween eases, loops, sequences and completes", function(a)
		local tw = Kits.create("tween", { id = "tw" })
		tw.create("fade", { from = 0, to = 1, duration = 0.5, easing = "quadOut" })
		tw.update(0.25)
		a:gt(tw.valueOf("fade"), 0.5, "quadOut must be past halfway at half time")
		local finished = tw.update(0.3)
		a:equal(#finished, 1)
		a:equal(tw.valueOf("fade"), 1)
		a:equal(tw.stats().completed, 1)
		a:near(tw.ease("linear", 0.5), 0.5, 0.001)
		a:gt(tw.ease("bounceOut", 0.9), 0.9)
		tw.create("slide", { from = 0, to = 100, duration = 1, delay = 0.5 })
		tw.update(0.4)
		a:equal(tw.valueOf("slide"), 0, "a delayed tween has not started")
		tw.update(0.6)
		a:gt(tw.valueOf("slide"), 0)
		local ids, total = tw.sequence("intro", {
			{ from = 0, to = 1, duration = 0.2 },
			{ from = 1, to = 0, duration = 0.3 } })
		a:equal(#ids, 2)
		a:near(total, 0.5, 0.001)
		a:gt(tw.activeCount(), 1)
		a:gt(tw.clear(), 2)
	end)

	s:it("replicator sends deltas, respects interest and splits packets", function(a)
		local rep = Kits.create("replicator", { id = "rep", mtu = 120,
			interestRadius = 50, fullEvery = 10 })
		rep.spawn("a", { hp = 100, name = "ana" }, v3(0, 0, 0))
		rep.spawn("b", { hp = 80, name = "bo" }, v3(40, 0, 0))
		rep.spawn("far", { hp = 50, name = "zed" }, v3(400, 0, 0))
		rep.addClient("c1", v3())
		a:equal(#rep.interestSet("c1"), 2, "distant entities are not replicated")
		local first = rep.snapshotFor("c1")
		a:ok(first.full)
		a:gt(first.bytes, 10)
		rep.flush()
		local quiet = rep.snapshotFor("c1")
		a:equal(next(quiet.entities), nil, "nothing changed, nothing is sent")
		rep.set("a", "hp", 90)
		local delta = rep.snapshotFor("c1")
		a:ok(delta.entities.a ~= nil)
		a:equal(delta.entities.b, nil, "a delta carries only what changed")
		local target = {}
		a:gt(rep.apply(delta, target), 0)
		a:equal(target.a.hp, 90)
		rep.moveClient("c1", v3(400, 0, 0))
		a:equal(#rep.interestSet("c1"), 1, "interest follows the player")
		for i = 1, 12 do rep.spawn("e" .. i, { hp = i, name = "name" .. i }, v3(400, 0, 0)) end
		local big = rep.snapshotFor("c1")
		local parts = rep.split(big)
		a:gt(#parts, 1, "an oversized packet must be split under the MTU")
		for _, part in ipairs(parts) do a:lte(part.bytes, 240) end
		a:gt(rep.stats().bytesSent, 0)
	end)

	s:it("netclock estimates offset, rejects outliers and buffers jitter", function(a)
		local clock = Kits.create("netclock", { id = "clk", tickRate = 20, bufferDelay = 0.1 })
		for i = 1, 8 do
			clock.sample(i * 0.1, i * 0.1 + 1.0 + 0.025, i * 0.1 + 0.05)
		end
		a:near(clock.offset, 1.0, 0.02)
		a:near(clock.rtt, 0.05, 0.01)
		clock.sample(1.0, 2.05, 1.6)
		a:near(clock.offset, 1.0, 0.05, "one spike must not move the clock")
		a:gte(clock.advance(1.0), 19)
		a:gte(clock.stats().tick, 19)
		a:near(clock.serverTime(), 2.0, 0.05)
		clock.push({ tick = 1 }, clock.localTime)
		a:equal(#clock.pop(), 0, "a snapshot waits out the buffer delay")
		clock.advance(0.2)
		a:equal(#clock.pop(), 1)
		a:gte(clock.jitter, 0)
		local delay = clock.adaptBuffer()
		a:gte(delay, 0.016)
	end)

	s:it("prediction replays unacknowledged inputs after a correction", function(a)
		local pr = Kits.create("prediction", { id = "pr", errorThreshold = 0.05 })
		local input = { move = v3(1, 0, 0), speed = 10 }
		for _ = 1, 10 do pr.pushInput(input, 1 / 30) end
		a:equal(pr.stats().sequence, 10)
		a:equal(pr.pending(), 10)
		a:gt(pr.state.position.x, 0)
		-- the server agrees: no correction, no replay
		local corrected = pr.reconcile({ position = pr.state.position, velocity = pr.state.velocity }, 10)
		a:ok(not corrected)
		a:equal(pr.pending(), 0)
		for _ = 1, 6 do pr.pushInput(input, 1 / 30) end
		local far = v3(pr.state.position.x - 3, 0, 0)
		local fixed, err = pr.reconcile({ position = far, velocity = v3() }, 12)
		a:ok(fixed, "a big disagreement must force a correction")
		a:gt(err, 0.05)
		a:gt(pr.stats().replays, 0)
		a:equal(pr.stats().mispredictions, 1)
		a:gt(pr.state.position.x, far.x, "the replay must re-apply the pending inputs")
		local corrected = pr.state.position.x
		local smoothed = pr.smooth({ position = v3(), velocity = v3() }, 1 / 30)
		a:lt(math.abs(smoothed.position.x), math.abs(corrected))
		a:gt(smoothed.position.x * corrected, 0, "smoothing must move toward the server")
	end)
end)

t:describe("vfx/effects", function(s)
	s:it("spawns effects from templates and finishes them", function(a)
		local Effects = A:import("arkher/vfx/effect_system")
		local fx = Effects.new({ budget = 800 })
		a:equal(fx:defineDefaults(), 4)
		local inst = fx:spawn("spark", v3(0, 1, 0))
		a:ok(inst ~= nil)
		a:equal(fx:activeCount(), 1)
		fx:update(1 / 60, v3())
		a:gt(fx:particleCount(), 0, "a burst must produce particles immediately")
		fx:run(2.5, 1 / 60)
		a:equal(fx:activeCount(), 0, "a one-shot effect must clean itself up")
		a:equal(fx:report().completed, 1)
	end)

	s:it("drops fidelity with distance and culls what nobody sees", function(a)
		local Effects = A:import("arkher/vfx/effect_system")
		local fx = Effects.new({ budget = 2000 })
		fx:defineDefaults()
		fx:spawn("smoke", v3(0, 0, 0), { id = "close" })
		fx:spawn("smoke", v3(0, 0, 80), { id = "mid" })
		fx:spawn("smoke", v3(0, 0, 5000), { id = "gone" })
		fx:run(1.0, 1 / 30)
		local byLod = fx:byLod()
		a:equal(byLod.full, 1)
		a:equal(byLod.reduced, 1)
		a:equal(byLod.culled, 1)
		a:equal(fx:get("gone").particles.aliveCount(), 0)
		a:gt(fx:get("close").particles.aliveCount(), 0)
		a:gt(fx:get("close").particles.aliveCount(), fx:get("mid").particles.aliveCount())
	end)

	s:it("holds a global particle budget and degrades on quality", function(a)
		local Effects = A:import("arkher/vfx/effect_system")
		local fx = Effects.new({ budget = 150 })
		fx:defineDefaults()
		for i = 1, 8 do fx:spawn("smoke", v3(i * 2, 0, 0), { id = "s" .. i }) end
		fx:run(1.5, 1 / 30)
		a:lte(fx:particleCount(), 200, "the shared budget must cap total particles")
		a:gt(fx:report().starved, 0)
		local low = fx:applyQuality(0.1)
		a:lt(low.budget, 800)
		a:lt(low.fullDistance, 40)
		fx:run(0.5, 1 / 30)
		a:gt(fx:report().frame, 50)
	end)
end)

t:describe("audio/engine", function(s)
	s:it("plays, mixes and finishes voices", function(a)
		local Audio = A:import("arkher/audio/audio_engine")
		local audio = Audio.new({ maxVoices = 8 })
		audio:define("step", { bus = "sfx", length = 0.4, volume = 0.8 })
		audio:define("theme", { bus = "music", length = 30, loop = true, spatial = false })
		audio:setListener(v3(), v3(0, 0, -1), v3(0, 1, 0))
		local voice = audio:play("step", v3(0, 0, 3))
		a:ok(voice ~= nil)
		a:ok(audio:isPlaying(voice))
		a:gt(audio:gainOf(voice), 0)
		local music = audio:play("theme")
		a:gt(audio:gainOf(music), 0)
		audio:run(1.0, 1 / 30)
		a:ok(not audio:isPlaying(voice), "a one-shot must end on its own")
		a:ok(audio:isPlaying(music), "a loop must keep going")
		a:equal(audio:report().played, 2)
	end)

	s:it("spatialises, ducks and steals voices under pressure", function(a)
		local Audio = A:import("arkher/audio/audio_engine")
		local audio = Audio.new({ maxVoices = 3 })
		audio:define("bang", { bus = "sfx", length = 5, priority = 1 })
		audio:define("line", { bus = "voice", length = 5, priority = 9 })
		audio:setListener(v3(), v3(0, 0, -1), v3(0, 1, 0))
		local near = audio:play("bang", v3(0, 0, 4), { id = "near" })
		local far = audio:play("bang", v3(0, 0, 90), { id = "far" })
		a:gt(audio:gainOf(near), audio:gainOf(far))
		local right = audio:play("bang", v3(30, 0, 0), { id = "right" })
		a:gt(audio:panOf(right), 0.8)
		a:ok(audio:play("bang", v3(), { id = "extra" }) == nil, "a full mixer refuses a voice")
		local dialogue = audio:play("line", v3(0, 0, 1), { id = "line1" })
		a:ok(dialogue ~= nil, "an important voice steals a slot")
		audio:duckFor("sfx", 0.9, 0.5)
		audio:run(0.4, 1 / 30)
		a:lt(audio.mixer.effectiveGain("sfx"), 0.4, "dialogue must push the effects down")
		audio:run(1.5, 1 / 30)
		a:gt(audio.mixer.effectiveGain("sfx"), 0.4, "ducking must release")
		local loudest = audio:loudest()
		a:ok(loudest ~= nil)
	end)

	s:it("runs adaptive music with stems and quantized transitions", function(a)
		local Audio = A:import("arkher/audio/audio_engine")
		local audio = Audio.new({ bpm = 120 })
		audio:setupMusic()
		local cues = 0
		audio.onCue:connect(function() cues = cues + 1 end)
		audio:scheduleCue("stinger", 2)
		audio:run(1.5, 1 / 30)
		a:equal(cues, 1)
		a:equal(audio.music.stats().current, "explore")
		audio:setIntensity(0.9)
		audio:transition("combat", 4)
		audio:run(3.0, 1 / 30)
		a:equal(audio.music.stats().current, "combat")
		a:gt(audio.music.layerGain("percussion"), 0.3)
		local low = audio:applyQuality(0.1)
		a:lte(low.maxVoices, 24)
		a:gt(audio:report().time, 4)
	end)
end)

t:describe("gameplay/framework", function(s)
	s:it("builds characters whose numbers actually connect", function(a)
		local Gameplay = A:import("arkher/gameplay/gameplay_framework")
		local game = Gameplay.new({ seed = 3 })
		local hero = game:createEntity("hero", { vitality = 12, strength = 14, agility = 10 })
		a:ok(hero ~= nil)
		a:equal(game:actor("hero").maxHealth, 20 + 12 * 8)
		a:gt(game:actor("hero").power, 20)
		hero.inventory.defineItem("sword", { slot = "hand", weight = 3,
			tags = { strength = 6 }, value = 50 })
		hero.inventory.add("sword", 1)
		a:ok(game:equip("hero", "sword"))
		a:equal(hero.stats.get("strength"), 20, "equipment must move the attribute")
		a:gt(game:actor("hero").power, 30, "and the attribute must move the fighter")
		game:unequip("hero", "hand")
		a:equal(hero.stats.get("strength"), 14)
	end)

	s:it("fights, kills, levels and rewards", function(a)
		local Gameplay = A:import("arkher/gameplay/gameplay_framework")
		local game = Gameplay.new({ seed = 5 })
		game:createEntity("hero", { strength = 20, agility = 14, team = "player" })
		game:createEntity("wolf", { vitality = 2, armour = 0, team = "enemy" })
		game.quests.define("hunt")
		game.quests.addObjective("hunt", "wolves", { required = 1, event = "kill" })
		game.quests.start("hunt")
		local deaths = 0
		game.onDeath:connect(function() deaths = deaths + 1 end)
		local killed = false
		for _ = 1, 30 do
			local result = game:attack("hero", "wolf", { power = 40 })
			if result and result.killed then killed = true break end
		end
		a:ok(killed)
		a:equal(deaths, 1)
		a:equal(game.quests.stateOf("hunt"), "completed")
		a:gt(game:get("hero").xp + (game:get("hero").level - 1) * 100, 0)
		a:gt(game:loot("hero", "pelt", 2) >= 0 and 1 or 0, 0)
		a:gt(game:report().combat.attacks, 0)
	end)

	s:it("saves and restores the whole gameplay state", function(a)
		local Gameplay = A:import("arkher/gameplay/gameplay_framework")
		local game = Gameplay.new({ seed = 9 })
		local hero = game:createEntity("hero", { vitality = 10 })
		hero.inventory.defineItem("potion", { stack = 5, weight = 0.5, value = 10 })
		hero.inventory.add("potion", 3)
		game:grantXp("hero", 250)
		a:gt(hero.level, 1)
		local before = game:checksum()
		local blob = game:save()
		a:gt(#blob, 20)
		hero.inventory.remove("potion", 3)
		game:grantXp("hero", 1000)
		a:ok(game:checksum() ~= before)
		a:equal(game:load(blob), 1)
		a:equal(game:checksum(), before, "a load must restore the exact state")
		a:equal(hero.inventory.countOf("potion"), 3)
		local difficulty = game:tuneDifficulty(0.9, 1)
		a:ok(difficulty ~= nil)
		a:gt(game:report().entities, 0)
	end)
end)

t:describe("ui/framework", function(s)
	s:it("builds a responsive screen stack", function(a)
		local UI = A:import("arkher/ui/ui_framework")
		local ui = UI.new({ width = 400, height = 800 })
		ui:defineScreen("home", function(u, root)
			u:panel(root, "home.body", { weight = 1 })
			u:label("home.body", "home.title", "ARKHER")
			u:button(root, "home.play", "Play", "play", { height = 56 })
		end)
		ui:defineScreen("settings", function(u, root)
			u:button(root, "settings.back", "Back", "back", { height = 56 })
		end)
		a:ok(ui:push("home"))
		a:equal(ui:current(), "home")
		a:gt(ui.layout.rectOf("home.play").height, 44)
		a:ok(ui:push("settings"))
		a:equal(ui:current(), "settings")
		a:equal(ui.layout.nodes["home.root"].visible, false)
		a:equal(ui:pop(), "settings")
		a:equal(ui:current(), "home")
		a:ok(not ui:pop(), "the root screen cannot be popped")
		a:equal(ui:report().screens, 2)
	end)

	s:it("routes taps to actions and binds state to widgets", function(a)
		local UI = A:import("arkher/ui/ui_framework")
		local ui = UI.new({ width = 400, height = 800 })
		local fired = nil
		ui:defineScreen("hud", function(u, root)
			u:label(root, "hud.hp", "HP")
			u:button(root, "hud.attack", "Attack", "attack", { height = 60 })
		end)
		ui:push("hud")
		ui.onAction:connect(function(e) fired = e.action end)
		ui:bind("hud.hp", "text", "hp", function(v) return "HP " .. tostring(v or 0) end)
		ui:set("hp", 42)
		a:equal(ui:propOf("hud.hp", "text"), "HP 42")
		local rect = ui.layout.rectOf("hud.attack")
		local hit = ui:tap(rect.x + 10, rect.y + 10)
		a:equal(hit, "hud.attack")
		a:equal(fired, "attack")
		a:ok(ui.input.wasTapped("attack"))
		a:equal(ui:report().interactions, 1)
	end)

	s:it("adapts to devices and passes the accessibility audits", function(a)
		local UI = A:import("arkher/ui/ui_framework")
		local ui = UI.new({ width = 400, height = 800 })
		ui:defineScreen("main", function(u, root)
			u:button(root, "main.ok", "OK", "ok", { height = 48 })
		end)
		ui:push("main")
		a:equal(#ui:auditTouchTargets(44), 0, "every target must be at least 44pt")
		a:equal(#ui:auditContrast(), 0, "the palette must pass WCAG AA")
		a:equal(ui:setViewport(1600, 1200), "desktop")
		a:equal(ui:setDevice("gamepad"), "gamepad")
		a:equal(ui.layout.safeArea.top, 16)
		ui:setViewport(400, 800, { top = 44, bottom = 34, left = 0, right = 0 })
		a:equal(ui.layout.breakpoint(), "phone")
		local low = ui:applyQuality(0.1)
		a:gt(low.timeScale, 1)
		ui:run(0.5, 1 / 60)
		a:gt(ui:report().frame, 20)
	end)
end)

t:describe("net/replication", function(s)
	s:it("replicates an authoritative world to interested clients", function(a)
		local Net = A:import("arkher/net/replication")
		local net = Net.new({ tickRate = 30, interestRadius = 60, mtu = 400 })
		net:spawn("p1", { hp = 100 }, v3())
		net:spawn("p2", { hp = 100 }, v3(30, 0, 0))
		net:spawn("boss", { hp = 900 }, v3(500, 0, 0))
		net:connect("p1", { latency = 0.05 })
		net:moveClient("p1", v3())
		local sent = 0
		net.onSnapshot:connect(function() sent = sent + 1 end)
		net:step(1 / 30)
		a:gt(sent, 0)
		net:setField("p2", "hp", 80)
		net:step(1 / 30)
		a:gt(net:report().bytesSent, 0)
		a:equal(net:report().entities, 3)
		a:gt(net:report().bandwidth, 0)
	end)

	s:it("predicts on the client and reconciles with the server", function(a)
		local Net = A:import("arkher/net/replication")
		local net = Net.new({})
		net:spawn("p1", { hp = 100 }, v3())
		net:connect("p1", { errorThreshold = 0.05 })
		local input = { move = v3(1, 0, 0), speed = 8, sequence = 1 }
		for i = 1, 8 do
			input.sequence = i
			net:clientPredict("p1", input, 1 / 30)
		end
		a:gt(net:clientState("p1").position.x, 0)
		for i = 1, 8 do
			input.sequence = i
			net:acceptInput("p1", input, 1 / 30)
		end
		local corrected, err = net:clientReconcile("p1")
		a:ok(err ~= nil)
		a:lt(err, 1, "server and client must agree closely on the same model")
		net:moveClient("p1", v3(0, 0, 0))
		net.replicator.move("p1", v3(50, 0, 0))
		local fixed = net:clientReconcile("p1")
		a:ok(fixed, "a teleport from the server must correct the client")
	end)

	s:it("rate limits, rewinds and validates hits", function(a)
		local Net = A:import("arkher/net/replication")
		local net = Net.new({ tickRate = 30, rateCapacity = 5, rateRefill = 5 })
		net:spawn("shooter", { hp = 100 }, v3())
		net:spawn("target", { hp = 100 }, v3(10, 0, 0))
		net:connect("shooter", { latency = 0.2 })
		for i = 1, 12 do net:step(1 / 30) end
		a:gt(net:report().history, 5)
		net:move("target", v3(30, 0, 0))
		for i = 1, 6 do net:step(1 / 30) end
		local hitOld = net:validateHit("shooter", "target", v3(10, 0, 0), 1.5)
		a:ok(hitOld, "lag compensation must accept a hit where the target used to be")
		local hitGhost = net:validateHit("shooter", "target", v3(300, 0, 0), 1.5)
		a:ok(not hitGhost)
		a:equal(net:report().validated, 1)
		a:gt(net:report().rejected, 0)
		local blocked = 0
		for i = 1, 40 do
			local ok = net:acceptInput("shooter", { move = v3(1, 0, 0), speed = 5, sequence = i }, 1 / 30)
			if not ok then blocked = blocked + 1 end
		end
		a:gt(blocked, 0, "input flooding must be rate limited")
		local low = net:applyQuality(0.1)
		a:lt(low.interestRadius, 200)
		a:lte(low.tickRate, 30)
	end)
end)

local r = t:run()
if not t:report() then error("ARKHER round 7 tests failed") end
