-- ARKHER :: Round 8 verification (Singularity AI, assets, cinematic, original tech)
local A = ARKHER
local TestKit = A:import("arkher/kernel/testkit")
local Kits = A:import("arkher/runtime/kits")
local Vec = A:import("arkher/kernel/vec")
local v3 = Vec.vec3
local t = TestKit.new()

t:describe("intelligence/kits", function(s)
	s:it("intent parses a real sentence into an actionable structure", function(a)
		local intent = Kits.create("intent", { id = "i" })
		local r = intent.parse("build a realistic city with 120 buildings for weak phones")
		a:equal(r.action, "create")
		a:equal(r.target, "city")
		a:equal(r.quantity, 120)
		a:equal(r.constraints.device, "mobile")
		a:ok(r.understood)
		a:gt(r.confidence, 0.3)
		local found = false
		for _, q in ipairs(r.qualifiers) do
			if q == "realistic" then found = true end
		end
		a:ok(found, "the qualifier must survive parsing")
		-- an unrelated sentence must NOT be claimed as understood
		local noise = intent.parse("zzz qqq")
		a:ok(not noise.understood)
		a:equal(intent.stats().unmatched, 1)
		a:ok(intent.explain(r):find("city") ~= nil)
	end)

	s:it("intent recovers the action from context when no verb is spoken", function(a)
		local intent = Kits.create("intent", { id = "i2" })
		local r = intent.parse("the map is slow and the fps drops on phones")
		a:equal(r.action, "optimize")
		a:equal(r.constraints.device, "mobile")
		a:gt(intent.vocabulary().verbs, 3)
	end)

	s:it("knowledge infers transitive dependencies and finds a path", function(a)
		local k = Kits.create("knowledge", { id = "k" })
		k.addEntity("terrain", "system")
		k.addEntity("roads", "system")
		k.addEntity("buildings", "system")
		k.addEntity("lighting", "system")
		k.relate("roads", "depends_on", "terrain")
		k.relate("buildings", "depends_on", "roads")
		k.relate("lighting", "depends_on", "buildings")
		a:ok(not k.hasRelation("lighting", "depends_on", "terrain"))
		local added = k.addRule("depends_on", "transitive") and k.infer(4)
		a:gt(added, 0)
		a:ok(k.hasRelation("lighting", "depends_on", "terrain"), "closure must be derived")
		local _, inferred = k.hasRelation("lighting", "depends_on", "terrain")
		a:ok(inferred, "a derived edge must be marked as derived")
		local path = k.path("lighting", "terrain")
		a:ok(path ~= nil)
		a:gte(#path, 2)
		a:equal(#k.query({ type = "system" }), 4)
	end)

	s:it("knowledge embeds entities and ranks similarity", function(a)
		local k = Kits.create("knowledge", { id = "k2", dims = 16 })
		k.addEntity("oak", "tree", { biome = "forest" })
		k.addEntity("pine", "tree", { biome = "forest" })
		k.addEntity("crane", "machine", { biome = "city" })
		k.relate("oak", "near", "pine")
		local sameKind = k.similarity("oak", "pine")
		local otherKind = k.similarity("oak", "crane")
		a:gt(sameKind, otherKind, "same-type entities must be closer")
		local nearest = k.nearest("oak", 1)
		a:equal(nearest[1].id, "pine")
		a:ok(k.forget("crane"))
		a:equal(k.stats().entities, 2)
	end)

	s:it("workflow orders, verifies, retries and rolls back", function(a)
		local w = Kits.create("workflow", { id = "w", maxRetries = 2 })
		local log = {}
		w.addStep("c", { requires = { "b" }, cost = 1,
			run = function() log[#log + 1] = "c" return true end,
			verify = function() return true end })
		w.addStep("a", { cost = 2, run = function() log[#log + 1] = "a" return true end })
		w.addStep("b", { requires = { "a" }, cost = 1,
			run = function() log[#log + 1] = "b" return true end,
			undo = function() log[#log + 1] = "undo-b" end })
		local order = w.plan()
		a:equal(order[1], "a")
		a:equal(order[3], "c")
		local ok = w.run({})
		a:ok(ok)
		a:equal(table.concat(log, ","), "a,b,c")
		a:near(w.progress(), 1, 1e-9)
		a:equal(w.estimate(), 4)

		local flaky = Kits.create("workflow", { id = "w2", maxRetries = 3 })
		local attempts = 0
		flaky.addStep("shaky", { run = function()
			attempts = attempts + 1
			return attempts
		end, verify = function() return attempts >= 3 end })
		a:ok(flaky.run({}))
		a:equal(attempts, 3, "the step must be retried until verification passes")

		local doomed = Kits.create("workflow", { id = "w3", maxRetries = 0 })
		local undone = 0
		doomed.addStep("good", { run = function() return true end,
			undo = function() undone = undone + 1 end })
		doomed.addStep("bad", { requires = { "good" }, run = function() return true end,
			verify = function() return false end })
		local ranOk, failedAt = doomed.run({})
		a:ok(not ranOk)
		a:equal(failedAt, "bad")
		a:equal(undone, 1, "a failed workflow must undo what it already did")
	end)

	s:it("critic scores against direction and names the worst offender", function(a)
		local c = Kits.create("critic", { id = "c" })
		c.addCriterion("frameMs", { weight = 3, target = 16, direction = "lower" })
		c.addCriterion("coverage", { weight = 2, target = 1, direction = "higher" })
		c.addCriterion("density", { weight = 1, floor = 0.4, ceiling = 0.6, direction = "range" })
		local good = c.evaluate({ frameMs = 15, coverage = 1, density = 0.5 })
		a:equal(good.verdict, "pass")
		a:gt(good.overall, 0.9)
		local bad = c.evaluate({ frameMs = 60, coverage = 0.2, density = 2 })
		a:lt(bad.overall, good.overall)
		a:equal(c.worst(bad), "frameMs")
		a:gt(#c.suggestions(bad, 2), 0)
		a:lt(c.improvement(), 0, "the second evaluation was worse")
	end)

	s:it("importer validates, normalizes, hashes and deduplicates", function(a)
		local imp = Kits.create("importer", { id = "imp", unitScale = 2 })
		imp.installDefaults()
		local bad, errors = imp.import("mesh", { name = "rock" })
		a:ok(bad == nil)
		a:gt(#errors, 0)
		local asset = imp.import("mesh", { name = "rock", vertices = 900, triangles = 1200,
			bytes = 2048, size = 4, extension = "obj" })
		a:ok(asset ~= nil)
		a:equal(asset.data.size, 8, "scaleFields must be converted into ARKHER units")
		local again, _, note = imp.import("mesh", { name = "rock", vertices = 900,
			triangles = 1200, bytes = 2048, size = 4, extension = "obj" })
		a:equal(note, "duplicate")
		a:equal(again.id, "rock")
		local tex = imp.import("texture", { name = "brick", width = 300, height = 300,
			bytes = 4096, extension = "png" })
		a:equal(#tex.warnings, 1, "a non power-of-two texture must warn, not fail")
		imp.import("mesh", { name = "wall", vertices = 10, triangles = 20, bytes = 64 },
			{ "missing-thing" })
		a:equal(#imp.missingDependencies(), 1)
		local stats = imp.stats()
		a:equal(stats.imported, 3)
		a:equal(stats.rejected, 1)
		a:equal(stats.duplicates, 1)
	end)

	s:it("bundler packs to a size ceiling and diffs against a previous manifest", function(a)
		local b = Kits.create("bundler", { id = "b", maxBundleBytes = 1000 })
		for i = 1, 6 do
			b.add("mesh" .. i, { bytes = 800, type = "mesh", group = "core", priority = i })
		end
		b.add("music", { bytes = 900, type = "audio", group = "stream" })
		local count = b.pack()
		a:gt(count, 3, "800 raw bytes compress to 440, so two fit per bundle")
		for _, bundle in ipairs(b.bundles) do a:lte(bundle.bytes, 1000) end
		a:ok(b.bundleOf("music") ~= nil)
		local first = b.manifest()
		a:equal(first.entries, 7)
		b.entries["mesh1"].hash = 999999
		b.add("mesh7", { bytes = 100, type = "mesh", group = "core" })
		b.pack()
		local delta = b.delta(first)
		a:equal(#delta.added, 1)
		a:equal(delta.added[1], "mesh7")
		a:equal(#delta.changed, 1)
		a:equal(delta.changed[1], "mesh1")
		a:lt(b.compressionRatio(), 1)
		a:equal(#b.loadPlan({ "stream" }), 1)
	end)

	s:it("timeline interpolates, fires events once and loops", function(a)
		local tl = Kits.create("timeline", { id = "tl", duration = 4 })
		tl.addTrack("fov", { default = 1 })
		tl.addKey("fov", 0, 1)
		tl.addKey("fov", 2, 2, "linear")
		a:near(tl.valueAt("fov", 1), 1.5, 1e-6)
		tl.addTrack("exposure", { easing = "easeIn" })
		tl.addKey("exposure", 0, 0)
		tl.addKey("exposure", 1, 1)
		a:near(tl.valueAt("exposure", 0.5), 0.25, 1e-6)
		tl.addClip("intro", 0, 1.5)
		tl.addClip("outro", 2, 2)
		a:equal(#tl.activeClips(0.5), 1)
		a:equal(#tl.activeClips(2.5), 1)
		tl.addEvent("bang", 1.0)
		tl.addEvent("boom", 3.0)
		tl.play()
		local fired = tl.advance(1.5)
		a:equal(#fired, 1)
		a:equal(fired[1].name, "bang")
		a:equal(#tl.advance(1.0), 0, "an event must not fire twice")
		a:equal(#tl.advance(1.0), 1)
		a:near(tl.trim(), 4, 1e-9)
		a:equal(tl.stats().fired, 2)
	end)

	s:it("camerarig frames, focuses and settles toward its target", function(a)
		local rig = Kits.create("camerarig", { id = "rig", mode = "orbit",
			distance = 10, height = 4, smoothing = 12 })
		local subject = v3(0, 0, 0)
		local first = rig.update(1 / 30, subject)
		local firstDistance = first:distance(subject)
		for _ = 1, 120 do rig.update(1 / 30, subject) end
		local settled = rig.position:distance(subject)
		a:lt(math.abs(settled - math.sqrt(10 * 10 + 4 * 4)), math.abs(firstDistance - 10) + 2)
		a:near(rig.focus, settled, 1e-6, "focus must follow the subject")
		a:near(rig.circleOfConfusion(rig.focus), 0, 1e-6)
		a:gt(rig.circleOfConfusion(rig.focus * 4), 0)
		local near = rig.frameSubject(2, 0.5)
		local wide = rig.frameSubject(2, 0.25)
		a:gt(wide, near, "a smaller screen fraction must pull the camera back")
		rig.shake(1)
		rig.update(0.1, subject)
		a:lt(rig.shakeAmount, 1, "shake must decay")
		rig.setMode("dolly")
		rig.addPathPoint(v3(0, 0, 0))
		rig.addPathPoint(v3(10, 0, 0))
		a:near(rig.pathAt(0.5).x, 5, 1e-6)
		a:near(rig.pathLength, 10, 1e-6)
	end)

	s:it("grade exposes, tone maps and auto-exposes to a target luma", function(a)
		local g = Kits.create("grade", { id = "g" })
		local mid = g.apply({ 0.5, 0.5, 0.5 })
		a:lte(mid[1], 1)
		a:gte(mid[1], 0)
		g.exposure = 1
		local brighter = g.apply({ 0.2, 0.2, 0.2 })
		g.exposure = 0
		local base = g.apply({ 0.2, 0.2, 0.2 })
		a:gt(brighter[1], base[1], "one stop must be brighter")
		g.installLooks()
		g.applyLook("noir", 1)
		local noir = g.apply({ 0.8, 0.2, 0.2 })
		a:lt(math.abs(noir[1] - noir[3]), 0.2, "noir must desaturate")
		g.reset()
		local dark = {}
		for i = 1, 8 do dark[i] = { 0.02, 0.02, 0.02 } end
		local before = g.averageLuma(dark)
		for _ = 1, 12 do g.autoExpose(dark, 0.18) end
		local after = g.averageLuma(dark)
		a:gt(after, before)
		a:lt(math.abs(after - 0.18), math.abs(before - 0.18))
		g.toneMap = "reinhard"
		a:near(g.toneCurve(1), 0.5, 1e-9)
	end)

	s:it("reality resolves layers by priority and commits a proposal", function(a)
		local r = Kits.create("reality", { id = "r" })
		r.installStack()
		r.set("authored", "city.population", 100)
		a:equal(r.get("city.population"), 100)
		r.set("simulated", "city.population", 140)
		local value, from = r.get("city.population")
		a:equal(value, 140)
		a:equal(from, "simulated")
		r.set("proposed", "city.population", 500)
		a:equal(r.get("city.population"), 500)
		a:equal(r.discard("proposed"), 1, "a discarded proposal must leave nothing behind")
		a:equal(r.get("city.population"), 140)
		r.set("proposed", "city.population", 200)
		a:equal(r.commit("proposed", "authored"), 1)
		a:equal(r.get("city.population"), 140, "simulated still wins over authored")
		a:gt(r.divergence("authored"), 0, "the simulation has pulled reality off the authored value")
		r.setEnabled("simulated", false)
		a:equal(r.get("city.population"), 200)
		a:near(r.divergence("authored"), 0, 1e-9, "with the simulation off, reality is the authored truth")
		a:equal(#r.keys(), 1)
	end)

	s:it("complexity holds the frame budget and protects important zones", function(a)
		local c = Kits.create("complexity", { id = "c", targetMs = 10 })
		c.addZone("downtown", { objects = 400, agents = 40, lights = 30, effects = 10 })
		c.addZone("suburb", { objects = 200, agents = 10, lights = 10, effects = 2 })
		c.setImportance("downtown", 4)
		c.setImportance("suburb", 1)
		a:gt(c.totalCost(), 10, "this scene must be over budget")
		a:equal(c.classify("downtown"), "critical")
		local result = c.evaluate()
		a:gt(result.pressure, 1)
		local down = c.directiveFor("downtown")
		local sub = c.directiveFor("suburb")
		a:lt(down.objects, 400)
		a:lt(sub.objects, 200)
		a:gt(down.quality, sub.quality, "the important zone must keep more quality")
		local heaviest = c.heaviest()
		a:equal(heaviest, "downtown")
		c.setTarget(1000)
		local relaxed = c.evaluate()
		a:lt(relaxed.pressure, 1)
		a:equal(c.directiveFor("downtown").objects, 400)
	end)

	s:it("fabric steps domains at their own rate inside one budget", function(a)
		local f = Kits.create("fabric", { id = "f", budgetMs = 1.5, starvationLimit = 4 })
		local counts = { fast = 0, slow = 0, heavy = 0 }
		f.addDomain("fast", { hz = 30, cost = 1, priority = 3,
			step = function() counts.fast = counts.fast + 1 end })
		f.addDomain("slow", { hz = 2, cost = 1, priority = 2,
			step = function() counts.slow = counts.slow + 1 end })
		f.addDomain("heavy", { hz = 10, cost = 1, priority = 1,
			step = function() counts.heavy = counts.heavy + 1 end })
		f.run(2, 1 / 30)
		a:gt(counts.fast, counts.slow, "a 30 Hz domain must outrun a 2 Hz domain")
		a:gt(counts.heavy, 0, "a low priority domain must not starve forever")
		a:gt(f.stats().deferred, 0, "the budget must actually defer work")
		f.send("weather", { rain = 1 })
		f.send("weather", { rain = 0.5 })
		a:equal(#f.receive("weather", 1), 1)
		a:equal(#f.receive("weather"), 1)
		local loadBefore = f.load()
		f.applyQuality(0.2)
		a:lt(f.load(), loadBefore, "lowering quality must lower the simulation load")
	end)

	s:it("autopipeline finds real faults, repairs them and measures the gain", function(a)
		local p = Kits.create("autopipeline", { id = "p" })
		p.installDefaults()
		local project = { frameMs = 40, targetMs = 16.6, drawCalls = 2000,
			maxDrawCalls = 900, failingTests = 2, orphanAssets = 5,
			memoryMb = 900, memoryCeilingMb = 512, quality = 1 }
		local findings = p.analyze(project)
		a:equal(#findings, 5)
		a:equal(findings[1].severity, 3, "the worst findings must come first")
		local health = p.health(project)
		a:lt(health, 0.2)
		local record = p.improve(project, 30)
		a:gt(record.gain, 0)
		a:gt(record.after, health)
		a:lt(project.drawCalls, 2000)
		a:lt(project.memoryMb, 900)
		a:equal(project.orphanAssets, 0)
		local clean = { frameMs = 10, targetMs = 16.6, drawCalls = 100, maxDrawCalls = 900,
			failingTests = 0, orphanAssets = 0, memoryMb = 100, memoryCeilingMb = 512 }
		a:equal(#p.analyze(clean), 0)
		a:near(p.health(clean), 1, 1e-9)
	end)

	s:it("worldmemory recalls, compacts, checkpoints and restores", function(a)
		local m = Kits.create("worldmemory", { id = "m", capacity = 8 })
		m.remember("ana", "born", { region = "north" })
		m.advance(1)
		m.remember("ana", "moved", { region = "south", weight = 2 })
		m.remember("bob", "born", { region = "north" })
		a:equal(#m.recall({ subject = "ana" }), 2)
		a:equal(#m.recall({ region = "north" }), 2)
		a:equal(#m.recall({ since = 0.5 }), 2)
		a:equal(#m.historyOf("ana"), 2)
		local epoch = m.advanceEpoch("age-of-steel")
		a:equal(epoch, 2)
		m.remember("bob", "built", { region = "north" })
		a:equal(#m.recall({ epoch = 2 }), 1)
		local cp = m.checkpoint("save1")
		m.remember("bob", "died", {})
		a:ok(m.checksum() ~= cp.checksum)
		a:ok(m.restore(cp), "restoring must reproduce the exact checksum")
		a:equal(#m.recall({ subject = "bob" }), 2)
		for i = 1, 12 do m.remember("crowd", "step" .. (i % 3), {}) end
		a:lte(#m.records, 12)
		a:gt(m.stats().compacted, 0, "overflow must fold into summaries")
		a:ok(m.summaryOf("ana", "born") ~= nil or m.summaryOf("crowd", "step1") ~= nil)
	end)

	s:it("emergence detects a pattern nobody scripted", function(a)
		local e = Kits.create("emergence", { id = "e", windowSize = 2, threshold = 1.2,
			minCount = 3 })
		for i = 1, 12 do
			e.observe("drought")
			e.observe("migration")
			e.observe("noise" .. i)
		end
		local found = e.detect()
		a:gt(#found, 0)
		a:gt(e.lift("drought", "migration"), 1.2)
		local names = e.named()
		local hit = false
		for _, name in ipairs(names) do
			if name == "drought-migration" or name == "migration-drought" then hit = true end
		end
		a:ok(hit, "the recurring pair must be named as a phenomenon")
		a:lt(e.novelty("drought"), e.novelty("brand-new"))
		for i = 1, 20 do e.signal("unrest", 0.2) end
		a:near(e.deviation("unrest"), 0, 1e-6)
		e.signal("unrest", 5)
		a:gt(e.deviation("unrest"), 2, "a spike must show as a deviation")
		e.forget()
		a:equal(e.stats().observations, 0)
	end)

	s:it("architect composes a coherent world and a build order", function(a)
		local arch = Kits.create("architect", { id = "arch", budget = 1000 })
		local composed = arch.compose({ target = "porto", quantity = 120, density = 1 })
		a:equal(composed.root, "porto")
		a:gt(composed.nodes, 8)
		local ok, failures = arch.coherent()
		a:ok(ok, failures and table.concat(failures, ",") or "")
		local leaves = 0
		for _, id in ipairs(arch.order) do
			if #arch.nodes[id].children == 0 then leaves = leaves + arch.budgetOf(id) end
		end
		a:near(leaves, 1000, 0.001, "budget must be conserved down the tree")
		local programme = arch.programme()
		a:equal(#programme, #arch.order)
		local index = {}
		for i, id in ipairs(programme) do index[id] = i end
		a:lt(index["porto.terrain"], index["porto.roads"])
		a:lt(index["porto.roads"], index["porto.district1"])
		a:lt(index["porto.district1"], index["porto.district1.buildings"])
		a:gt(arch.estimate(1), 0)
		a:gt(arch.describe().district, 0)
	end)
end)

t:describe("intelligence/subsystems", function(s)
	s:it("the singularity agent turns a sentence into a verified city", function(a)
		local Agent = A:import("arkher/singularity/agent")
		local agent = Agent.new({ seed = 9 })
		local result = agent:fulfil("build a dense city with 100 buildings")
		a:ok(result.ok, tostring(result.reason))
		a:equal(result.action, "create")
		a:gt(result.plan.districts, 1)
		a:ok(agent.world.terrainReady)
		a:gt(agent.world.objects, 0)
		a:gt(agent.world.agents, 0)
		a:gt(agent.world.roads, 0)
		a:ok(agent.world.economy)
		a:near(agent.workflow.progress(), 1, 1e-9)
		a:ok(result.verdict == "pass" or result.verdict == "revise")
		a:gt(result.score, 0.5)
		local report = agent:report()
		a:gt(report.knowledge.entities, 5)
		a:gt(report.ledger, 0)
	end)

	s:it("the agent refuses what it does not understand", function(a)
		local Agent = A:import("arkher/singularity/agent")
		local agent = Agent.new({})
		local result = agent:fulfil("qqq zzz wubble")
		a:ok(not result.ok)
		a:equal(result.reason, "not understood")
		a:equal(agent.world.objects, 0, "nothing may be built from a sentence nobody parsed")
	end)

	s:it("the agent optimizes an existing scene for weak phones", function(a)
		local Agent = A:import("arkher/singularity/agent")
		local agent = Agent.new({})
		agent.world.objects = 2000
		agent.world.agents = 300
		agent.world.lights = 120
		agent.world.effects = 60
		local result = agent:fulfil("optimize this map for weak phones")
		a:ok(result.ok)
		a:equal(result.action, "optimize")
		a:lt(result.after, result.before, "the frame time must actually come down")
		a:lt(agent.world.quality, 1)
		a:lt(agent.world.objects, 2000)
		a:gt(result.passes, 0)
	end)

	s:it("the agent knows the prerequisites of a system", function(a)
		local Agent = A:import("arkher/singularity/agent")
		local agent = Agent.new({})
		a:ok(agent:knows("lighting"))
		local deps = agent:prerequisitesOf("lighting")
		local hasTerrain = false
		for _, dep in ipairs(deps) do
			if dep == "terrain" then hasTerrain = true end
		end
		a:ok(hasTerrain, "the inferred closure must reach terrain")
	end)

	s:it("the asset pipeline cooks to a mobile budget", function(a)
		local Pipeline = A:import("arkher/assets/pipeline")
		local p = Pipeline.new({ profile = "mobile" })
		p:add("mesh", { name = "tower", vertices = 90000, triangles = 60000,
			bytes = 3 * 1024 * 1024, extension = "fbx" })
		p:add("texture", { name = "facade", width = 4096, height = 4096,
			bytes = 3 * 1024 * 1024, extension = "png" })
		p:add("audio", { name = "ambience", seconds = 120, bytes = 2 * 1024 * 1024,
			extension = "ogg" })
		local cooked = p:cookAll()
		a:equal(cooked, 3)
		local mesh = p.cooked["tower"]
		a:equal(mesh.triangles, 8000, "a mobile cook must respect the triangle budget")
		a:equal(mesh.actions[1], "decimated")
		a:gt(mesh.lods, 1)
		local tex = p.cooked["facade"]
		a:equal(tex.width, 1024)
		a:equal(tex.mips, 11)
		a:ok(p.cooked["ambience"].streamed)
		a:gt(p:savings(), 0.5, "cooking must save real bytes")
		local pcPipe = Pipeline.new({ profile = "pc" })
		pcPipe:add("mesh", { name = "tower", vertices = 90000, triangles = 60000,
			bytes = 3 * 1024 * 1024, extension = "fbx" })
		pcPipe:cookAll()
		a:equal(pcPipe.cooked["tower"].triangles, 60000, "pc keeps the detail")
		a:gt(pcPipe.cooked["tower"].bytes, p.cooked["tower"].bytes)
	end)

	s:it("the asset pipeline bundles, manifests and patches", function(a)
		local Pipeline = A:import("arkher/assets/pipeline")
		local p = Pipeline.new({ profile = "mobile", maxBundleBytes = 200000 })
		for i = 1, 5 do
			p:add("mesh", { name = "prop" .. i, vertices = 500, triangles = 400,
				bytes = 120000, extension = "obj" })
		end
		p:add("texture", { name = "sky", width = 1024, height = 512, bytes = 300000,
			extension = "png" })
		p:cookAll()
		p:bundle(function(id) return id == "sky" and "stream" or "core" end)
		local manifest = p:manifest()
		a:gt(#manifest.bundles, 1)
		a:equal(manifest.profile, "mobile")
		a:ok(manifest.withinBudget)
		a:equal(manifest.assets, 6)
		p:add("mesh", { name = "prop6", vertices = 10, triangles = 10, bytes = 1000,
			extension = "obj" })
		p:cook("prop6")
		p:bundle()
		local delta = p:patch(manifest)
		a:equal(#delta.added, 1)
		a:equal(delta.added[1], "prop6")
		a:lt(p:budgetReport().memoryMb, 320)
		a:gt(p:report().budget.headroom, 0)
	end)

	s:it("the asset pipeline resolves dependencies and rejects bad input", function(a)
		local Pipeline = A:import("arkher/assets/pipeline")
		local p = Pipeline.new({})
		p:add("texture", { name = "bark", width = 512, height = 512, bytes = 4096,
			extension = "png" })
		p:add("mesh", { name = "tree", vertices = 100, triangles = 120, bytes = 8192,
			extension = "obj" }, { "bark" })
		local bad = p:add("mesh", { name = "broken" })
		a:ok(bad == nil)
		a:equal(#p.rejects, 1)
		local ordered, missing = p:resolve()
		a:equal(#missing, 0)
		local index = {}
		for i, id in ipairs(ordered) do index[id] = i end
		a:lt(index["bark"], index["tree"], "a dependency must be cooked first")
	end)

	s:it("the cinematic director cuts between shots and covers the sequence", function(a)
		local Director = A:import("arkher/cinematic/director")
		local d = Director.new({})
		d:addShot("wide", { length = 2, mode = "orbit", look = "warmDay" })
		d:addShot("close", { length = 2, mode = "follow", look = "coldNight",
			transition = "dissolve", transitionTime = 0.5 })
		a:equal(d.shots["close"].startTime, 2)
		a:near(d:duration(), 4, 1e-9)
		local coverage, gaps = d:coverage()
		a:near(coverage, 1, 1e-9)
		a:equal(#gaps, 0)
		local cuts = 0
		d.onCut:connect(function() cuts = cuts + 1 end)
		d:play()
		local subjects = { hero = v3(0, 0, 0) }
		for _ = 1, 90 do d:update(1 / 30, subjects) end
		a:gte(cuts, 1, "the director must cut when the playhead leaves a shot")
		a:equal(d.current, "close")
		local frame = d:frame()
		a:equal(frame.shot, "close")
		a:ok(frame.camera ~= nil)
		a:near(frame.letterbox, 2.39, 1e-9)
		a:ok(d:beatSheet():find("wide") ~= nil)
	end)

	s:it("the director exposes a gap in the coverage instead of hiding it", function(a)
		local Director = A:import("arkher/cinematic/director")
		local d = Director.new({})
		d:addShot("a", { startTime = 0, length = 1 })
		d:addShot("b", { startTime = 3, length = 1 })
		local coverage, gaps = d:coverage()
		a:near(coverage, 0.5, 1e-9)
		a:equal(#gaps, 1)
		a:near(gaps[1].from, 1, 1e-9)
		a:near(gaps[1].to, 3, 1e-9)
		a:equal(d:shotAt(2), nil, "dead air must read as no shot")
	end)

	s:it("the director drives tracks, cues and the grade", function(a)
		local Director = A:import("arkher/cinematic/director")
		local d = Director.new({})
		d:addShot("main", { length = 3, look = "noir" })
		d:addTrack("exposure", { default = 0 })
		d:key("exposure", 0, 0)
		d:key("exposure", 2, 1, "easeInOut")
		d:cue("impact", 1.0, { shake = 1 })
		local heard = {}
		d.onEvent:connect(function(e) heard[#heard + 1] = e.name end)
		d:play()
		for _ = 1, 45 do d:update(1 / 30, nil) end
		a:equal(#heard, 1)
		a:equal(heard[1], "impact")
		a:gt(d:frame().tracks.exposure, 0)
		a:lt(d.grade.saturation, 1, "the noir look must have been blended in")
		local graded = d:render({ { 0.9, 0.3, 0.3 } })
		a:equal(#graded, 1)
		a:lte(graded[1][1], 1)
		d:seek(0.2)
		a:equal(d:frame().shot, "main")
		a:gt(d:transitionWeight(0.0), -1)
	end)

	s:it("the adaptive world keeps living where nobody is looking", function(a)
		local World = A:import("arkher/original/adaptive_world")
		local w = World.new({ targetMs = 16.6, budgetMs = 4 })
		w:addRegion("downtown", { position = v3(0, 0, 0), population = 200,
			objects = 500, lights = 40 })
		w:addRegion("outpost", { position = v3(3000, 0, 0), population = 60,
			objects = 100, lights = 5 })
		w:addObserver("player", v3(0, 0, 0))
		w:run(20, 1 / 15)
		a:equal(w:tierOf("downtown"), "observed")
		a:equal(w:tierOf("outpost"), "dormant")
		local outpost = w.regions["outpost"]
		a:gt(outpost.debt, 0, "an unwatched region must accumulate coarse-mode debt")
		a:ok(outpost.population > 0)
		w:moveObserver("player", v3(3000, 0, 0))
		w:tick(1 / 15)
		a:equal(w:tierOf("outpost"), "observed")
		a:equal(outpost.debt, 0, "returning must reconcile the debt in one pass")
		a:gt(w.reconciliations, 0)
		local report = w:report()
		a:equal(report.regions, 2)
		a:gt(report.ticks, 100)
		a:gt(report.fabric.steps, 0)
	end)

	s:it("the adaptive world defends the frame budget under load", function(a)
		local World = A:import("arkher/original/adaptive_world")
		local w = World.new({ targetMs = 8, budgetMs = 2 })
		for i = 1, 6 do
			w:addRegion("zone" .. i, { position = v3(i * 10, 0, 0), population = 300,
				objects = 900, lights = 60 })
		end
		w:addObserver("player", v3(0, 0, 0))
		local loadBefore = w.fabric.load()
		w:run(4, 1 / 15)
		a:lt(w.fabric.load(), loadBefore, "pressure must slow the simulation down")
		local directive = w.complexity.directiveFor("zone1")
		a:lt(directive.objects, 900)
		a:gt(w.complexity.stats().overBudget, 0)
	end)

	s:it("the adaptive world remembers, snapshots and restores", function(a)
		local World = A:import("arkher/original/adaptive_world")
		local w = World.new({})
		w:addRegion("valley", { position = v3(0, 0, 0), population = 120,
			resources = 20, objects = 100 })
		w:addObserver("player", v3(0, 0, 0))
		w:run(30, 1 / 10)
		local snapshot = w:snapshot()
		local savedPopulation = w.regions["valley"].population
		w:run(30, 1 / 10)
		a:ok(math.abs(w.regions["valley"].population - savedPopulation) >= 0)
		w:restore(snapshot)
		a:near(w.regions["valley"].population, savedPopulation, 1e-9)
		a:gte(w.memory.stats().written, 0)
		a:ok(w.reality.get("valley.population") ~= nil)
	end)

	s:it("the autonomous pipeline repairs a project and proves the gain", function(a)
		local Autopilot = A:import("arkher/original/autonomous_pipeline")
		local auto = Autopilot.new({ project = { frameMs = 48, targetMs = 16.6,
			drawCalls = 3000, maxDrawCalls = 900, memoryMb = 1200,
			memoryCeilingMb = 512, failingTests = 3, totalTests = 20,
			orphanAssets = 9, quality = 1 } })
		local before = auto:score().overall
		local result = auto:converge(8)
		a:gt(result.cycles, 0)
		a:gt(result.finalScore, before)
		a:gt(result.health, 0.2)
		a:lt(auto.project.frameMs, 48)
		a:lt(auto.project.drawCalls, 3000)
		a:equal(auto.project.orphanAssets, 0)
		a:ok(auto:plan():find("draw calls") ~= nil or auto:plan():find("no open findings") ~= nil)
		a:gt(auto:report().runs, 0)
	end)

	s:it("the autonomous pipeline samples live metrics and never regresses", function(a)
		local Autopilot = A:import("arkher/original/autonomous_pipeline")
		local auto = Autopilot.new({ project = { frameMs = 30, targetMs = 16.6,
			drawCalls = 500, maxDrawCalls = 900, memoryMb = 200, memoryCeilingMb = 512,
			failingTests = 0, totalTests = 10, orphanAssets = 0, quality = 1 } })
		local sampled = 0
		auto:addSampler("frameMs", function(p)
			sampled = sampled + 1
			return p.frameMs
		end)
		local findings = auto:analyze()
		a:gt(sampled, 0, "the sampler must actually run")
		a:equal(#findings, 1)
		a:equal(findings[1].rule, "frame-budget")
		local result = auto:cycle()
		a:gte(result.gain, 0, "a cycle may never make the project worse")
		a:lt(auto.project.frameMs, 30)
		a:equal(auto.regressions, 0)
	end)
end)

local r = t:run()
if not t:report() then error("ARKHER round 8 tests failed") end
