-- ARKHER :: Kernel + Kits test suite (runs headless in the fengari VM and in Studio)
local A = ARKHER
local TestKit = A:import("arkher/kernel/testkit")
local t = TestKit.new()

local Errors = A:import("arkher/kernel/errors")
local Signal = A:import("arkher/kernel/signal")
local EventBus = A:import("arkher/kernel/eventbus")
local Scheduler = A:import("arkher/kernel/scheduler")
local JobSystem = A:import("arkher/kernel/jobsystem")
local Promise = A:import("arkher/kernel/promise")
local Clock = A:import("arkher/kernel/clock")
local DepGraph = A:import("arkher/kernel/depgraph")
local Mathx = A:import("arkher/kernel/mathx")
local Vec = A:import("arkher/kernel/vec")
local Rand = A:import("arkher/kernel/random")
local Noise = A:import("arkher/kernel/noise")
local Cont = A:import("arkher/kernel/containers")
local Spatial = A:import("arkher/kernel/spatial")
local Hash = A:import("arkher/kernel/hash")
local Ser = A:import("arkher/kernel/serialize")
local ECS = A:import("arkher/kernel/ecs")
local Service = A:import("arkher/kernel/service")
local State = A:import("arkher/kernel/state")
local Config = A:import("arkher/kernel/config")
local Validate = A:import("arkher/kernel/validate")
local Reflection = A:import("arkher/kernel/reflection")
local Resource = A:import("arkher/kernel/resource")
local Profiler = A:import("arkher/kernel/profiler")
local Version = A:import("arkher/kernel/version")
local Log = A:import("arkher/kernel/log")
local Sandbox = A:import("arkher/security/sandbox")
local Integrity = A:import("arkher/security/integrity")
local Headless = A:import("arkher/platform/headless")
local Device = A:import("arkher/do15/device")
local Budget = A:import("arkher/do15/budget")
local Controller = A:import("arkher/do15/controller")
local Bottleneck = A:import("arkher/do15/bottleneck")
local LOD = A:import("arkher/do15/lod")
local Kits = A:import("arkher/runtime/kits")

t:describe("kernel/errors", function(s)
	s:it("creates coded errors", function(a)
		local e = Errors.new(Errors.Codes.NOT_FOUND, "missing")
		a:equal(e.codeName, "NOT_FOUND")
		a:ok(Errors.is(e))
		a:ok(string.find(tostring(e), "NOT_FOUND") ~= nil)
	end)
	s:it("wraps causes and try()", function(a)
		local ok, err = Errors.try(function() error(Errors.new(Errors.Codes.INTERNAL, "boom")) end)
		a:equal(ok, false)
		a:equal(err.code, Errors.Codes.INTERNAL)
	end)
end)

t:describe("kernel/signal + eventbus", function(s)
	s:it("fires in priority order and disconnects", function(a)
		local sig = Signal.new("t")
		local seen = {}
		sig:connect(function() seen[#seen + 1] = "low" end, 0)
		local c = sig:connect(function() seen[#seen + 1] = "high" end, 10)
		sig:fire()
		a:equal(seen[1], "high")
		c:disconnect()
		sig:fire()
		a:equal(sig:count(), 1)
	end)
	s:it("routes wildcard topics and defers", function(a)
		local bus = EventBus.new()
		local hits = 0
		bus:subscribe("world.*", function() hits = hits + 1 end)
		bus:publish("world.chunk.loaded", {})
		bus:post("world.entity.spawned", {})
		a:equal(hits, 1)
		bus:flush()
		a:equal(hits, 2)
		a:equal(bus:stats().published, 2)
	end)
end)

t:describe("kernel/scheduler", function(s)
	s:it("runs phases with intervals", function(a)
		local time = 0
		local sch = Scheduler.new({ timeFn = function() return time end })
		local n = 0
		sch:add({ id = "tick", phase = Scheduler.Phase.SIMULATION, fn = function() n = n + 1 end })
		sch:add({ id = "slow", phase = Scheduler.Phase.AI, interval = 1.0, fn = function() n = n + 100 end })
		sch:frame(0.1)
		a:equal(n, 1)
		for _ = 1, 10 do sch:frame(0.1) end
		a:gte(n, 111)
	end)
	s:it("degrades to a budget", function(a)
		local sch = Scheduler.new({ timeFn = function() return 0 end })
		sch:add({ id = "a", fn = function() end, importance = 0.2 })
		sch:add({ id = "b", fn = function() end, importance = 1.0 })
		sch.stats.a.avgMs = 20
		sch.stats.b.avgMs = 5
		local disabled = sch:degradeToBudget(10)
		a:equal(disabled[1], "a")
	end)
end)

t:describe("kernel/jobsystem", function(s)
	s:it("runs cooperative jobs to completion", function(a)
		local js = JobSystem.new({ workers = 2, timeFn = function() return 0 end })
		local acc = 0
		local job = js:schedule(function(yield)
			for i = 1, 5 do acc = acc + i yield() end
			return acc
		end)
		js:drain()
		a:equal(job.state, "done")
		a:equal(acc, 15)
	end)
	s:it("parallelFor covers the whole range", function(a)
		local js = JobSystem.new({ workers = 4, timeFn = function() return 0 end })
		local hits = {}
		js:parallelFor(1, 100, 10, function(i) hits[i] = true end)
		js:drain()
		local count = 0
		for i = 1, 100 do if hits[i] then count = count + 1 end end
		a:equal(count, 100)
		a:equal(js:stats().completed, 10)
	end)
end)

t:describe("kernel/promise", function(s)
	s:it("chains and catches", function(a)
		local value
		Promise.resolve(2):andThen(function(v) return v * 3 end):andThen(function(v) value = v end)
		a:equal(value, 6)
		local caught
		Promise.reject("bad"):catch(function(e) caught = e end)
		a:equal(caught, "bad")
	end)
	s:it("all/race resolve", function(a)
		local out
		Promise.all({ Promise.resolve(1), Promise.resolve(2) }):andThen(function(v) out = v end)
		a:equal(out[2], 2)
		local first
		Promise.race({ Promise.resolve("a"), Promise.resolve("b") }):andThen(function(v) first = v end)
		a:equal(first, "a")
	end)
end)

t:describe("kernel/depgraph", function(s)
	s:it("topologically sorts and finds cycles", function(a)
		local g = DepGraph.new()
		g:addEdge("render", "scene")
		g:addEdge("scene", "core")
		local order = g:topoSort()
		a:equal(order[1], "core")
		a:equal(order[3], "render")
		g:addEdge("core", "render")
		a:ok(g:hasCycle())
	end)
	s:it("computes parallel waves", function(a)
		local g = DepGraph.new()
		g:addEdge("b", "a")
		g:addEdge("c", "a")
		local waves = g:waves()
		a:equal(#waves[1], 1)
		a:equal(#waves[2], 2)
	end)
end)

t:describe("kernel/math + vec", function(s)
	s:it("interpolates and clamps", function(a)
		a:near(Mathx.lerp(0, 10, 0.25), 2.5)
		a:equal(Mathx.clamp(11, 0, 10), 10)
		a:near(Mathx.smoothstep(0.5), 0.5)
		a:near(Mathx.remap(5, 0, 10, 0, 100), 50)
	end)
	s:it("vector algebra is correct", function(a)
		local v = Vec.vec3(3, 4, 0)
		a:near(v:length(), 5)
		a:near(v:unit():length(), 1)
		local c = Vec.vec3(1, 0, 0):cross(Vec.vec3(0, 1, 0))
		a:near(c.z, 1)
		a:near(Vec.vec3(1, 0, 0):dot(Vec.vec3(0, 1, 0)), 0)
	end)
	s:it("quaternions rotate vectors", function(a)
		local q = Vec.quatFromAxisAngle(Vec.vec3(0, 1, 0), math.pi / 2)
		local r = q * Vec.vec3(1, 0, 0)
		a:near(r.z, -1, 1e-5)
		local q2 = Vec.quatFromEuler(0, math.pi, 0)
		a:near(q:slerp(q2, 0):dot(q), 1, 1e-6)
	end)
	s:it("matrices transform points", function(a)
		local m = Vec.translation(5, 0, 0)
		local p = m:transformPoint(Vec.vec3(1, 1, 1))
		a:near(p.x, 6)
	end)
end)

t:describe("kernel/random + noise", function(s)
	s:it("is deterministic for a seed", function(a)
		local r1, r2 = Rand.new(99), Rand.new(99)
		for _ = 1, 20 do a:equal(r1:nextUInt(), r2:nextUInt()) end
	end)
	s:it("produces bounded noise", function(a)
		for i = 1, 50 do
			local v = Noise.perlin2D(i * 0.37, i * 0.11, 7)
			a:ok(v >= -1.5 and v <= 1.5, "perlin in range")
		end
		local f = Noise.fbm(Noise.perlin2D, 1.5, 2.5, { octaves = 4, seed = 3 })
		a:ok(f == f)
	end)
	s:it("worley returns increasing distances", function(a)
		local d1, d2 = Noise.worley2D(1.3, 4.2, 11)
		a:gte(d2, d1)
	end)
end)

t:describe("kernel/containers", function(s)
	s:it("ring buffer wraps", function(a)
		local r = Cont.ring(3)
		for i = 1, 5 do r:push(i) end
		a:equal(r.size, 3)
		a:equal(r:get(1), 3)
		a:equal(r:last(), 5)
		a:near(r:average(), 4)
	end)
	s:it("priority queue orders", function(a)
		local pq = Cont.priorityQueue()
		pq:push({ priority = 5 }) pq:push({ priority = 1 }) pq:push({ priority = 3 })
		a:equal(pq:pop().priority, 1)
		a:equal(pq:pop().priority, 3)
	end)
	s:it("sparse set add/remove keeps density", function(a)
		local ss = Cont.sparseSet()
		ss:add(10, "a") ss:add(20, "b") ss:remove(10)
		a:equal(ss:count(), 1)
		a:equal(ss:get(20), "b")
	end)
	s:it("lru evicts oldest", function(a)
		local lru = Cont.lru(2)
		lru:set("a", 1) lru:set("b", 2)
		lru:get("a")
		lru:set("c", 3)
		a:equal(lru:has("b"), false)
		a:equal(lru:get("a"), 1)
	end)
	s:it("bitset counts bits", function(a)
		local bs = Cont.bitset()
		bs:set(1) bs:set(65) bs:set(200)
		a:equal(bs:count(), 3)
		a:ok(bs:test(65))
		bs:clear(65)
		a:equal(bs:test(65), false)
	end)
end)

t:describe("kernel/spatial", function(s)
	s:it("aabb intersect + ray", function(a)
		local box = Spatial.aabb(Vec.vec3(0, 0, 0), Vec.vec3(10, 10, 10))
		a:ok(box:contains(Vec.vec3(5, 5, 5)))
		local hit = box:rayHit(Vec.vec3(-5, 5, 5), Vec.vec3(1, 0, 0), 100)
		a:near(hit, 5)
	end)
	s:it("spatial hash radius query", function(a)
		local h = Spatial.spatialHash(10)
		h:insert("a", Vec.vec3(1, 1, 1))
		h:insert("b", Vec.vec3(100, 0, 0))
		local hits = h:queryRadius(Vec.vec3(0, 0, 0), 20)
		a:equal(#hits, 1)
		a:equal(hits[1].id, "a")
	end)
	s:it("octree subdivides and queries", function(a)
		local tree = Spatial.octree(Spatial.aabb(Vec.vec3(0, 0, 0), Vec.vec3(64, 64, 64)), 4, 2)
		for i = 1, 30 do tree:insert("e" .. i, Vec.vec3(i, i % 10, i % 7)) end
		a:gt(tree:nodeCount(), 1)
		local found = tree:query(Spatial.aabb(Vec.vec3(0, 0, 0), Vec.vec3(10, 64, 64)))
		a:gt(#found, 0)
	end)
	s:it("bvh raycast finds nearest", function(a)
		local prims = {}
		for i = 1, 8 do
			prims[i] = { id = i, bounds = Spatial.aabb(Vec.vec3(i * 10, 0, 0), Vec.vec3(i * 10 + 5, 5, 5)) }
		end
		local bvh = Spatial.bvh(prims)
		local hit = bvh:raycast(Vec.vec3(-10, 2, 2), Vec.vec3(1, 0, 0), 500)
		a:equal(hit.id, 1)
	end)
	s:it("frustum culls behind camera", function(a)
		local f = Spatial.frustumFromCamera(Vec.vec3(0, 0, 0), Vec.vec3(0, 0, -1), Vec.vec3(0, 1, 0), math.rad(70), 1.6, 1, 500)
		a:ok(f:containsSphere(Vec.vec3(0, 0, -50), 5))
		a:equal(f:containsSphere(Vec.vec3(0, 0, 50), 1), false)
	end)
end)

t:describe("kernel/hash + serialize", function(s)
	s:it("hashes stably", function(a)
		a:equal(Hash.fnv1a("arkher"), Hash.fnv1a("arkher"))
		a:ok(Hash.fnv1a("a") ~= Hash.fnv1a("b"))
		a:equal(Hash.crc32("123456789"), 0xCBF43926)
	end)
	s:it("base64 round trips", function(a)
		local src = "ARKHER-UES-D-O15"
		a:equal(Hash.base64decode(Hash.base64encode(src)), src)
	end)
	s:it("json round trips", function(a)
		local data = { name = "arkher", version = 1, nested = { list = { 1, 2, 3 }, flag = true } }
		local decoded = Ser.decodeJSON(Ser.encodeJSON(data))
		a:equal(decoded.nested.list[3], 3)
		a:equal(decoded.name, "arkher")
	end)
	s:it("binary round trips and diffs", function(a)
		local data = { a = 1, b = "two", c = { 3.5, true } }
		local decoded = Ser.decodeBinary(Ser.encodeBinary(data))
		a:deepEqual(decoded, data)
		local d = Ser.diff({ x = 1, y = 2 }, { x = 5, y = 2 })
		a:equal(d.set.x, 5)
		local target = { x = 1, y = 2 }
		Ser.applyDiff(target, d)
		a:equal(target.x, 5)
	end)
end)

t:describe("kernel/ecs", function(s)
	s:it("creates entities and queries components", function(a)
		local w = ECS.new()
		local e1 = w:create("hero")
		w:set(e1, "transform", { x = 0 })
		w:set(e1, "health", { hp = 100 })
		local e2 = w:create()
		w:set(e2, "transform", { x = 5 })
		a:equal(#w:query({ "transform" }), 2)
		a:equal(#w:query({ "transform", "health" }), 1)
		w:destroy(e1)
		a:equal(#w:query({ "transform" }), 1)
	end)
	s:it("hierarchy and tags work", function(a)
		local w = ECS.new()
		local parent, child = w:create(), w:create()
		w:setParent(child, parent)
		a:equal(w:getChildren(parent)[1], child)
		w:addTag(child, "npc")
		a:equal(#w:withTag("npc"), 1)
		w:destroy(parent)
		a:equal(w:isAlive(child), false)
	end)
	s:it("snapshot restores state", function(a)
		local w = ECS.new()
		local e = w:create("x")
		w:set(e, "pos", { x = 3 })
		local snap = w:snapshot()
		w:destroy(e)
		w:restore(snap)
		a:equal(w:stats().entities, 1)
		a:equal(w:get(1, "pos").x, 3)
	end)
	s:it("runs systems with deferred commands", function(a)
		local w = ECS.new()
		for i = 1, 5 do
			local e = w:create()
			w:set(e, "counter", { n = 0 })
		end
		w:addSystem({ name = "inc", fn = function(world) world:each({ "counter" }, function(_, c) c.n = c.n + 1 end) end })
		w:update(0.016)
		w:update(0.016)
		a:equal(w:get(1, "counter").n, 2)
	end)
end)

t:describe("kernel/service + state", function(s)
	s:it("resolves dependency order", function(a)
		local sc = Service.new()
		sc:register({ id = "core", factory = function() return { name = "core", started = false, start = function(self) self.started = true end } end })
		sc:register({ id = "render", deps = { "core" }, factory = function(_, core) return { core = core } end })
		local started = sc:startAll()
		a:equal(started[1], "core")
		a:equal(sc:resolve("render").core.name, "core")
		a:ok(sc:resolve("core").started)
	end)
	s:it("state machine guards transitions", function(a)
		local m = State.machine()
		m:add("idle"):add("run"):add("dead")
		m:allow("idle", "run")
		m:allow("run", "dead")
		a:ok(m:goTo("idle"))
		a:ok(m:goTo("run"))
		a:equal(m:goTo("idle"), false)
		a:ok(m:goTo("dead"))
	end)
end)

t:describe("kernel/config + validate + reflection", function(s)
	s:it("layers configuration", function(a)
		local cfg = Config.new({ render = { scale = 1.0, shadows = true } })
		a:equal(cfg:get("render.scale"), 1.0)
		cfg:set("render.scale", 0.7, "user")
		a:equal(cfg:get("render.scale"), 0.7)
		cfg:defineSchema("render.scale", { type = "number", min = 0.1, max = 1 })
		a:ok(cfg:validate())
		cfg:set("render.scale", 5)
		a:equal(cfg:validate(), false)
	end)
	s:it("feature flags evaluate rules", function(a)
		local flags = Config.flags()
		flags:define("neuralUpscale", false, function(ctx) return (ctx.tier or 0) >= 3 end)
		a:equal(flags:enabled("neuralUpscale", { tier = 1 }), false)
		a:ok(flags:enabled("neuralUpscale", { tier = 3 }))
	end)
	s:it("validates schemas", function(a)
		local ok, issues = Validate.check({ id = "a", kind = "mesh" }, Validate.schemaFor("asset"))
		a:ok(ok)
		local bad = Validate.check({ kind = "mesh" }, Validate.schemaFor("asset"))
		a:equal(bad, false)
	end)
	s:it("reflection builds editor layouts", function(a)
		Reflection.defineType("ArkherLight", { category = "rendering", fields = {
			intensity = { type = "number", default = 1, min = 0, max = 10, editor = { group = "Light" } },
			castShadows = { type = "boolean", default = true, editor = { group = "Light" } } } })
		local inst = Reflection.instantiate("ArkherLight", { intensity = 4 })
		a:equal(inst.intensity, 4)
		a:equal(inst.castShadows, true)
		local layout = Reflection.editorLayout("ArkherLight")
		a:equal(layout.groups[1].name, "Light")
		a:equal(layout.groups[1].fields[1].widget, "toggle")
		a:ok(Reflection.toToolSchema("ArkherLight") ~= nil)
	end)
end)

t:describe("kernel/resource + profiler + version", function(s)
	s:it("streams resources under budget", function(a)
		local rm = Resource.new({ budgetBytes = 1000 })
		rm:registerLoader("mesh", function(id) return { id = id }, 400 end)
		rm:declare("m1", "mesh")
		rm:declare("m2", "mesh")
		rm:declare("m3", "mesh")
		rm:request("m1", 5) rm:request("m2", 3) rm:request("m3", 1)
		rm:pump(3)
		a:equal(rm:state("m1"), "loaded")
		a:gt(rm:memoryPressure(), 1.0)
		rm:release("m1") rm:release("m2") rm:release("m3")
		rm:enforceBudget()
		a:lt(rm.usedBytes, 1001)
	end)
	s:it("object pool reuses", function(a)
		local created = 0
		local pool = Resource.pool(function() created = created + 1 return { alive = true } end, function(o) o.alive = false end, 2)
		local o = pool:acquire()
		pool:release(o)
		local o2 = pool:acquire()
		a:equal(created, 2)
		a:equal(pool:stats().live, 1)
	end)
	s:it("profiler measures scopes", function(a)
		local time = 0
		local p = Profiler.new({ timeFn = function() time = time + 0.001 return time end })
		p:beginFrame()
		p:push("render") p:pop()
		p:push("ai") p:pop()
		p:endFrame()
		a:equal(#p:topScopes(5), 2)
		a:gt(p:frameStats().count, 0)
		p:count("draws", 12)
		a:equal(p:getCounter("draws"), 12)
	end)
	s:it("semver + migrations", function(a)
		a:equal(Version.compare("1.2.3", "1.10.0"), -1)
		a:ok(Version.satisfies("1.4.0", "^1.2.0"))
		local m = Version.migrator()
		m:add("1.0.0", "1.1.0", function(d) d.migrated = true return d end)
		local out = m:migrate({ v = 1 }, "1.0.0", "1.1.0")
		a:ok(out.migrated)
		a:equal(Version.generationFor("1.5.0").name, "ARKHER V1")
	end)
	s:it("logger buffers and filters", function(a)
		local lg = Log.new({ level = Log.Level.DEBUG, capacity = 8 })
		for i = 1, 12 do lg:info("test", "msg " .. i) end
		a:equal(#lg:tail(20), 8)
		lg:setLevel(Log.Level.ERROR)
		a:equal(lg:info("test", "hidden"), false)
		a:ok(lg:error("test", "shown"))
	end)
end)

t:describe("security/sandbox + integrity", function(s)
	s:it("denies ungranted capabilities", function(a)
		local sb = Sandbox.new()
		sb:createPrincipal("plugin.x", { kind = "plugin" })
		local res, err = sb:invoke("plugin.x", "scene.write", function() return true end)
		a:equal(res, nil)
		a:equal(err.codeName, "SANDBOX_VIOLATION")
		sb:grant("plugin.x", "scene.write")
		a:equal(sb:invoke("plugin.x", "scene.write", function() return "ok" end), "ok")
	end)
	s:it("applies roles and wildcards", function(a)
		local sb = Sandbox.new()
		sb:createPrincipal("ai.agent")
		sb:applyRole("ai.agent", "admin")
		a:ok(sb:can("ai.agent", "scene.destroy"))
		a:equal(sb:can("ai.agent", "filesystem.write"), false)
	end)
	s:it("enforces per-frame quota", function(a)
		local sb = Sandbox.new()
		local p = sb:createPrincipal("spam", { quota = { calls = 1000, perFrame = 3 } })
		sb:grant("spam", "scene.read")
		for _ = 1, 3 do sb:invoke("spam", "scene.read", function() end) end
		local _, err = sb:invoke("spam", "scene.read", function() end)
		a:equal(err.codeName, "RESOURCE_EXHAUSTED")
		sb:resetFrameQuotas()
		a:equal(select(2, sb:invoke("spam", "scene.read", function() end)), nil)
	end)
	s:it("detects corruption and recovers", function(a)
		local ig = Integrity.new()
		local state = { level = 1, items = { "a", "b" } }
		ig:checkpoint("start", state)
		local recovered = ig:recover()
		a:equal(recovered.level, 1)
		ig:sign("doc", { v = 1 })
		a:ok(ig:verify("doc", { v = 1 }))
		a:equal(ig:verify("doc", { v = 2 }), false)
	end)
end)

t:describe("platform/headless adapter", function(s)
	s:it("builds a virtual node tree", function(a)
		local h = Headless.new()
		local part = h:createNode("Part", "Wall", h.root)
		h:setProperty(part, "Size", { 4, 4, 1 })
		a:equal(h:getProperty(part, "Name"), "Wall")
		a:equal(#h:children(h.root), 1)
		h:destroyNode(part)
		a:equal(#h:children(h.root), 0)
	end)
	s:it("advances virtual time and tasks", function(a)
		local h = Headless.new()
		local fired = false
		h:wait(1.0, function() fired = true end)
		h:advance(0.5)
		a:equal(fired, false)
		h:advance(0.6)
		a:ok(fired)
	end)
end)

t:describe("D-O15", function(s)
	s:it("classifies devices into tiers", function(a)
		local phone = { class = "phone", memoryMB = 1500, cores = 4, gpuTier = 1, screen = { width = 720, height = 1280 }, touch = true }
		local tier = Device.classify(phone)
		a:ok(tier.id == "mobile" or tier.id == "potato" or tier.id == "mobileHigh")
		local budgets = Device.budgets(phone)
		a:ok(budgets.batteryAware)
		a:gt(budgets.drawCalls, 0)
		local hi = Device.classify({ class = "desktop", memoryMB = 16000, cores = 12, gpuTier = 3, screen = { width = 1920, height = 1080 } })
		a:gt(hi.budgets.parts, budgets.parts)
	end)
	s:it("controller reduces quality when frames are slow", function(a)
		local c = Controller.new({ targetFrameMs = 16.6, level = 1.0 })
		for _ = 1, 30 do c:submitFrame(33) end
		for _ = 1, 20 do c:step(1 / 30) end
		a:lt(c.level, 1.0)
		a:lt(c.dimensions.reflections, c.dimensions.resolution)
		local preset = c:applyToPreset({ renderScale = 1, lodBias = 1, vfxDensity = 1, animationRate = 60, physicsRate = 60, npcTickRate = 15, textureRes = 1024, shadows = "high" })
		a:lt(preset.renderScale, 1.0)
	end)
	s:it("controller recovers when frames are fast", function(a)
		local c = Controller.new({ targetFrameMs = 16.6, level = 0.4 })
		for _ = 1, 30 do c:submitFrame(8) end
		for _ = 1, 40 do c:step(1 / 60) end
		a:gt(c.level, 0.4)
	end)
	s:it("budget allocates by priority", function(a)
		local b = Budget.new({ frameMs = 10 })
		b.policy = "priority"
		b:reserve("render", "frameMs", 8, 1.0)
		b:reserve("ai", "frameMs", 6, 0.3)
		local alloc = b:allocate("frameMs")
		a:equal(alloc.render, 8)
		a:equal(alloc.ai, 2)
	end)
	s:it("bottleneck detector ranks findings", function(a)
		local bd = Bottleneck.new()
		local findings = bd:analyze({ frameMs = 33, scriptMs = 20, drawCalls = 2000, parts = 30000,
			memoryMB = 1400, budgets = { drawCalls = 900, parts = 12000, memoryMB = 1200, particles = 1600 } })
		a:gt(#findings, 2)
		local plan = bd:plan(findings, 0.8)
		a:gt(#plan.steps, 3)
		a:ok(plan.steps[1].action ~= nil)
	end)
	s:it("LOD bands by distance and enforces caps", function(a)
		local lod = LOD.new()
		local band = lod:bandFor(10, 1)
		a:equal(band.name, "hero")
		a:equal(lod:bandFor(5000, 1).name, "statistical")
		for i = 1, 40 do lod:assign("e" .. i, 5 + i * 0.1, 1) end
		local demoted = lod:enforce(10, 20)
		a:gt(demoted, 0)
	end)
end)

t:describe("runtime/kits", function(s)
	s:it("registry stores, tags and queries", function(a)
		local r = Kits.registry({ id = "test" })
		r.define("mat.stone", { density = 2.6 }, { "material", "solid" })
		r.define("mat.water", { density = 1.0 }, { "material", "fluid" })
		a:equal(r.get("mat.stone").density, 2.6)
		a:equal(#r.withTag("material"), 2)
		a:equal(#r.query(function(d) return d.density < 2 end), 1)
		local snap = r.snapshot()
		r.remove("mat.water")
		a:equal(r.stats().count, 1)
		r.restore(snap)
		a:equal(r.stats().count, 2)
	end)
	s:it("pipeline runs stages in order with isolation", function(a)
		local p = Kits.pipeline({ id = "test" })
		p.addStage("double", function(v) return v * 2 end)
		p.addStage("boom", function() error("fail") end, { optional = true })
		p.addStage("inc", function(v) return v + 1 end)
		local out, err = p.run(5)
		a:equal(out, 11)
		a:equal(err, nil)
		a:equal(p.stats().failures, 1)
	end)
	s:it("cache honours policies", function(a)
		local c = Kits.cache({ id = "t", policy = "lfu", capacity = 2 })
		c.set("a", 1) c.set("b", 2)
		c.get("a") c.get("a")
		c.set("c", 3)
		a:equal(c.get("b"), nil)
		a:equal(c.get("a"), 1)
		a:gt(c.hitRate(), 0)
	end)
	s:it("controller converges on target", function(a)
		local c = Kits.controller({ id = "t", target = 10, kp = 0.5, min = 0, max = 100, initial = 0 })
		for _ = 1, 50 do
			c.submit(c.value)
			c.step(0.1)
		end
		a:ok(math.abs(c.value - 10) < 3)
	end)
	s:it("analyzer detects trend and anomalies", function(a)
		local an = Kits.analyzer({ window = 40, threshold = 2.5 })
		for i = 1, 30 do an.submit(i) end
		a:gt(an.trend(), 0.5)
		a:gt(an.forecast(5), an.mean())
		for _ = 1, 20 do an.submit(15) end
		a:ok(an.isAnomaly(500))
	end)
	s:it("budgeter distributes scarce resources", function(a)
		local b = Kits.budgeter({ total = 100, strategy = "priority" })
		b.claim("render", 80, 3)
		b.claim("ai", 60, 1)
		local granted = b.allocate()
		a:equal(granted.render, 80)
		a:equal(granted.ai, 20)
		a:gt(b.pressure(), 1)
	end)
	s:it("guard rate limits", function(a)
		local g = Kits.guard({ algorithm = "token", capacity = 3, refillPerSec = 1 })
		a:ok(g.allow()) a:ok(g.allow()) a:ok(g.allow())
		a:equal(g.allow(), false)
		g.tick(2)
		a:ok(g.allow())
	end)
	s:it("index answers spatial queries", function(a)
		local idx = Kits.index({ cellSize = 16 })
		idx.insert("tree1", Vec.vec3(0, 0, 0), { kind = "tree" })
		idx.insert("tree2", Vec.vec3(200, 0, 0), { kind = "tree" })
		a:equal(#idx.queryRadius(Vec.vec3(0, 0, 0), 50), 1)
		a:equal(idx.nearest(Vec.vec3(190, 0, 0), 64).id, "tree2")
	end)
	s:it("codec round trips all formats", function(a)
		for _, fmt in ipairs({ "binary", "json", "quantized", "rle" }) do
			local c = Kits.codec({ format = fmt })
			local value = { a = 1, b = "x", c = { 2, 3 } }
			local decoded, equal = c.roundTrip(value)
			a:ok(decoded ~= nil, fmt)
			if fmt == "binary" or fmt == "rle" then a:ok(equal, fmt) end
		end
	end)
	s:it("graph finds shortest paths", function(a)
		local g = Kits.graph({ directed = false })
		g.addEdge("a", "b", 1) g.addEdge("b", "c", 1) g.addEdge("a", "c", 5)
		local path, cost = g.shortestPath("a", "c")
		a:equal(cost, 2)
		a:equal(#path, 3)
		a:equal(#g.components(), 1)
	end)
	s:it("field samples deterministic terrain", function(a)
		local f = Kits.field({ seed = 7, frequency = 0.02, octaves = 4 })
		local v1 = f.sample(100, 200)
		local v2 = f.sample(100, 200)
		a:equal(v1, v2)
		a:ok(f.slope(100, 200) >= 0)
		local region = f.region(0, 0, 8, 8, 2)
		a:equal(#region, 5)
	end)
	s:it("predictor forecasts", function(a)
		local p = Kits.predictor({ method = "linear", window = 16 })
		for i = 1, 10 do p.observe(i * 2) end
		a:gt(p.predict(1), 18)
		local m = Kits.predictor({ method = "markov" })
		m.observe("idle") m.observe("walk") m.observe("idle") m.observe("walk")
		a:equal(m.predict(), "idle")
	end)
	s:it("ledger records and seals", function(a)
		local l = Kits.ledger({ capacity = 32 })
		l.write("edit", { op = "move" })
		l.write("edit", { op = "scale" })
		a:equal(#l.query("edit"), 2)
		local seal = l.seal()
		a:ok(l.verifySeal())
		l.observe(5) l.observe(100)
		a:gt(l.percentileBucket(95), 0)
	end)
	s:it("recovery rolls back", function(a)
		local r = Kits.recovery({})
		local state = { hp = 100 }
		r.snapshot("before", state)
		local result, ok = r.protect(function(s2) error("crash") end, state)
		a:equal(ok, false)
		a:equal(result.hp, 100)
		a:gt(r.stats().snapshots, 0)
	end)
	s:it("orchestrator transitions", function(a)
		local o = Kits.orchestrator({ states = { "idle", "build", "verify", "done" } })
		local seen = {}
		o.on("build", function() seen[#seen + 1] = "build" end)
		o.go("build")
		o.go("verify")
		a:equal(o.current, "verify")
		a:equal(o.stats().transitions, 2)
		a:equal(seen[1], "build")
	end)
	s:it("solver converges constraints", function(a)
		local sv = Kits.solver({ iterations = 40, tolerance = 0.01, damping = 0.5 })
		local state = { x = 0 }
		local constraints = { { evaluate = function(s2) return 10 - s2.x end, correct = function(s2, e) s2.x = s2.x + e end } }
		local out, iters = sv.solve(constraints, state)
		a:near(out.x, 10, 0.05)
		a:ok(sv.converged())
	end)
	s:it("streamer loads and unloads chunks", function(a)
		local loaded = 0
		local st = Kits.streamer({ radius = 100, chunkSize = 50, maxPerFrame = 100,
			onLoad = function() loaded = loaded + 1 end })
		st.update(0, 0)
		st.pump()
		a:gt(loaded, 4)
		st.update(10000, 10000)
		a:gt(st.stats().unloads, 0)
	end)
	s:it("composer blends layers", function(a)
		local comp = Kits.composer({ mode = "add" })
		comp.addLayer("base", 1, function() return 0.5 end, "add")
		comp.addLayer("detail", 0.5, function() return 0.4 end, "add")
		a:near(comp.evaluate({}), 0.7)
		comp.normalize()
		a:equal(#comp.layerNames(), 2)
	end)
	s:it("policy schedules fairly", function(a)
		local pol = Kits.policy({ algorithm = "edf" })
		pol.submit("late", 1, 100)
		pol.submit("urgent", 1, 5)
		a:equal(pol.next().id, "urgent")
	end)
	s:it("synthesizer generates deterministically", function(a)
		local syn = Kits.synthesizer({ seed = 11 })
		syn.addRule("root", { { value = "wall roof", weight = 1 } })
		syn.addRule("wall", { { value = "stone", weight = 1 } })
		syn.addRule("roof", { { value = "tile", weight = 1 } })
		local out = syn.generate("root")
		a:equal(out, "stone tile")
		a:ok(syn.deterministicCheck("root"))
	end)
end)

local results = t:run()
local ok = t:report()
if not ok then error("ARKHER kernel tests failed") end
