-- ARKHER :: Round 6 verification (NPC minds, navigation, society, world simulation)
local A = ARKHER
local TestKit = A:import("arkher/kernel/testkit")
local Kits = A:import("arkher/runtime/kits")
local Vec = A:import("arkher/kernel/vec")
local v3 = Vec.vec3
local t = TestKit.new()

t:describe("life/kits", function(s)
	s:it("mindnet decides, learns and exports its weights", function(a)
		local net = Kits.create("mindnet", { id = "m1", inputs = 4, hidden = 4, seed = 7 })
		a:ok(net.addAction("fight"))
		a:ok(net.addAction("flee"))
		a:ok(not net.addAction("fight"))
		local scores = net.forward({ 0.2, 0.8, 0.1, 0.5 })
		a:ok(scores.fight ~= nil and scores.flee ~= nil)
		local action = net.decide({ 0.2, 0.8, 0.1, 0.5 })
		a:ok(action == "fight" or action == "flee")
		-- reinforcing an action must make that action more likely for the same input
		local before = net.actions[action].value
		for _ = 1, 12 do
			net.forward({ 0.2, 0.8, 0.1, 0.5 })
			net.lastAction = action
			net.reinforce(1)
		end
		net.forward({ 0.2, 0.8, 0.1, 0.5 })
		a:gt(net.actions[action].value, before)
		a:gt(net.parameters(), 20)
		local weights = net.exportWeights()
		a:equal(#weights, net.parameters())
		a:equal(net.importWeights(weights), net.parameters())
		a:gt(net.memoryBytes(), 0)
		a:equal(net.resetState(), 4)
		a:gt(net.stats().forwards, 5)
	end)

	s:it("memory decays, recalls and consolidates facts", function(a)
		local mem = Kits.create("memory", { id = "mem", capacity = 5, decayRate = 0.2 })
		mem.remember("danger", { who = "wolf" }, 0.9, v3(10, 0, 0))
		mem.remember("food", { what = "berries" }, 0.4, v3(2, 0, 0))
		a:equal(mem.stats().episodes, 2)
		local danger = mem.recall("danger")
		a:equal(#danger, 1)
		a:equal(danger[1].payload.who, "wolf")
		a:equal(#mem.recallNear(v3(3, 0, 0), 5), 1)
		mem.tick(2)
		a:lt(mem.episodes[2].salience, 0.4)
		-- capacity pressure forgets the weakest memory, not the newest
		for i = 1, 6 do mem.remember("noise", { i = i }, 0.1) end
		a:lte(mem.stats().episodes, 5)
		a:gt(mem.stats().forgotten, 0)
		for _ = 1, 3 do mem.remember("danger", { who = "bear" }, 0.8) end
		a:gt(mem.consolidate(), 0)
		a:ok(mem.knows("danger"))
		a:gt(mem.forget("danger"), 0)
	end)

	s:it("needs decay, become urgent and are satisfied", function(a)
		local needs = Kits.create("need", { id = "n" })
		needs.define("food", { value = 0.5, decay = 0.1, threshold = 0.4 })
		needs.define("rest", { value = 0.9, decay = 0.01, threshold = 0.4 })
		a:near(needs.wellbeing(), 0.7, 0.001)
		a:equal(needs.urgency("food"), 0)
		needs.tick(2)
		a:lt(needs.needs.food.value, 0.4)
		a:gt(needs.urgency("food"), 0)
		local urgent, value = needs.mostUrgent()
		a:equal(urgent, "food")
		a:gt(value, 0)
		needs.satisfy("food", 0.6)
		a:equal(needs.urgency("food"), 0)
		a:equal(#needs.vector(), 2)
		a:gt(needs.stats().satisfactions, 0)
	end)

	s:it("emotion appraises events and settles back to baseline", function(a)
		local emo = Kits.create("emotion", { id = "e" })
		a:equal(emo.label(), "calm")
		emo.appraise(-0.9, 1.0)
		a:lt(emo.valence, 0)
		a:gt(emo.arousal, 0)
		local label = emo.label()
		a:ok(label == "fear" or label == "anger", "a strong bad event must read as fear or anger")
		a:gt(emo.intensity(), 0.3)
		a:lt(emo.mood(), 0)
		local cautious = emo.influence(1)
		a:lt(cautious, 1)
		for _ = 1, 200 do emo.tick(0.1) end
		a:lt(math.abs(emo.valence), 0.05)
		emo.appraise(0.9, 1)
		a:gt(emo.influence(1), 1)
		emo.reset()
		a:equal(emo.valence, 0)
		a:gt(emo.stats().appraisals, 1)
	end)

	s:it("perception sees, hears and keeps a bounded attention list", function(a)
		local p = Kits.create("perception", { id = "p", sightRange = 30,
			hearingRange = 10, attentionSlots = 2 })
		p.place(v3(), v3(0, 0, 1))
		a:ok(p.canSee(v3(0, 0, 10)))
		a:ok(not p.canSee(v3(0, 0, -10)), "nothing behind the head is visible")
		a:ok(not p.canSee(v3(0, 0, 200)))
		a:ok(p.canSee(v3(0, 0, 10), true) == false, "occlusion blocks sight")
		a:ok(p.canHear(v3(0, 0, -8), 1))
		p.submit("near", v3(0, 0, 4), { threat = 0.9, intensity = 0.9 })
		p.submit("far", v3(0, 0, 25), { intensity = 0.2 })
		p.submit("behind", v3(0, 0, -50))
		local attention, perceived = p.scan()
		a:equal(#attention, 2)
		a:equal(attention[1].id, "near")
		a:equal(perceived, 2)
		a:equal(p.focus().id, "near")
		a:gt(p.stats().ignored, 0)
		a:equal(p.clear(), 3)
	end)

	s:it("behaviour tree selects, sequences and respects cooldowns", function(a)
		local bt = Kits.create("behaviortree", { id = "bt" })
		bt.addNode("root", "selector")
		bt.addNode("guard", "sequence")
		bt.addNode("isThreat", "condition",
			{ condition = function(bb) return bb.threat == true end })
		bt.addNode("fight", "action", { action = function(bb) bb.did = "fight" return "success" end })
		bt.addNode("idle", "action", { action = function(bb) bb.did = "idle" return "success" end })
		bt.attach("root", "guard")
		bt.attach("guard", "isThreat")
		bt.attach("guard", "fight")
		bt.attach("root", "idle")
		bt.set("threat", false)
		a:equal(bt.tick(0.1), "success")
		a:equal(bt.get("did"), "idle")
		bt.set("threat", true)
		bt.tick(0.1)
		a:equal(bt.get("did"), "fight")
		a:equal(bt.depth(), 3)
		-- an inverter flips its child, a cooldown blocks repeats
		bt.addNode("never", "inverter")
		bt.addNode("always", "action", { action = function() return "success" end })
		bt.attach("never", "always")
		bt.setRoot("never")
		a:equal(bt.tick(0.1), "failure")
		bt.addNode("throttle", "cooldown", { cooldown = 1 })
		bt.attach("throttle", "always")
		bt.setRoot("throttle")
		a:equal(bt.tick(0.1), "success")
		a:equal(bt.tick(0.1), "failure")
		bt.tick(1.2)
		a:gt(bt.stats().ticks, 4)
	end)

	s:it("utility scores options with response curves", function(a)
		local u = Kits.create("utility", { id = "u", momentum = 0 })
		u.addOption("eat")
		u.addConsideration("eat", "hunger", function(ctx) return 1 - ctx.food end, "quadratic")
		u.addOption("sleep")
		u.addConsideration("sleep", "tired", function(ctx) return 1 - ctx.energy end, "linear")
		local hungry = { food = 0.05, energy = 0.9 }
		a:equal(u.evaluate(hungry, 0), "eat")
		local tired = { food = 0.95, energy = 0.05 }
		a:equal(u.evaluate(tired, 0), "sleep")
		local ranking = u.ranking(tired)
		a:equal(ranking[1].name, "sleep")
		a:gt(ranking[1].score, ranking[2].score)
		-- a cooldown takes an option out of the running
		u.options.sleep.cooldown = 5
		u.evaluate(tired, 0)
		a:equal(u.evaluate(tired, 0.1), "eat")
		a:gt(u.stats().evaluations, 3)
	end)

	s:it("planner builds a GOAP plan and proves it works", function(a)
		local p = Kits.create("planner", { id = "goap" })
		p.addAction("chop", { pre = { hasAxe = true }, effects = { hasWood = true }, cost = 2 })
		p.addAction("getAxe", { pre = { hasAxe = false }, effects = { hasAxe = true }, cost = 1 })
		p.addAction("build", { pre = { hasWood = true }, effects = { hasShelter = true }, cost = 3 })
		local plan, cost = p.plan({ hasAxe = false, hasWood = false, hasShelter = false },
			{ hasShelter = true })
		a:ok(plan ~= nil)
		a:equal(#plan, 3)
		a:equal(plan[1], "getAxe")
		a:equal(plan[3], "build")
		a:equal(cost, 6)
		local final, ok = p.simulate({ hasAxe = false, hasWood = false, hasShelter = false }, plan)
		a:ok(ok)
		a:equal(final.hasShelter, true)
		a:equal(p.planCost(plan), 6)
		local impossible = p.plan({ hasAxe = false }, { hasCastle = true })
		a:equal(impossible, nil)
		a:gt(p.stats().expansions, 2)
	end)

	s:it("navgraph finds, smooths and flows paths around obstacles", function(a)
		local nav = Kits.create("navgraph", { id = "nav", width = 20, height = 20, cellSize = 2 })
		a:ok(nav.walkable(5, 5))
		a:equal(nav.blockRect(5, 0, 5, 15), 16)
		a:ok(not nav.walkable(5, 5))
		local path, cost = nav.findPath(1, 1, 12, 1)
		a:ok(path ~= nil, "a path must exist around the wall")
		a:gt(cost, 11)
		a:gt(#path, 11)
		-- the path must actually go around: some node passes the wall's end
		local maxZ = 0
		for _, node in ipairs(path) do
			if node.z > maxZ then maxZ = node.z end
		end
		a:gt(maxZ, 14)
		local smoothed = nav.smooth(path)
		a:lt(#smoothed, #path)
		a:equal(#nav.worldPath(smoothed), #smoothed)
		a:gt(nav.pathLength(path), 0)
		a:ok(not nav.lineOfSight(1, 1, 12, 1))
		a:ok(nav.lineOfSight(1, 1, 4, 4))
		local field = nav.flowField(12, 1)
		local dir = field.direction(1, 1)
		a:ok(dir:length() > 0)
		a:equal(nav.findPath(5, 5, 12, 1), nil)
		a:gt(nav.stats().expansions, 20)
	end)

	s:it("crowd steers agents to targets without overlapping", function(a)
		local crowd = Kits.create("crowd", { id = "c", maxSpeed = 6 })
		for i = 1, 8 do
			crowd.add("a" .. i, v3(i * 1.5, 0, 0), {})
			crowd.setTarget("a" .. i, v3(30, 0, i * 0.2))
		end
		for _ = 1, 240 do crowd.step(1 / 30) end
		a:gt(crowd.arrivedCount(), 4)
		a:gt(crowd.stats().steps, 200)
		-- no two agents may end the run occupying the same spot
		local overlaps = 0
		for i = 1, 8 do
			for j = i + 1, 8 do
				local d = crowd.agents["a" .. i].position:distance(crowd.agents["a" .. j].position)
				if d < 0.4 then overlaps = overlaps + 1 end
			end
		end
		a:equal(overlaps, 0)
		a:gt(crowd.stats().neighborChecks, 0)
		a:ok(crowd.remove("a1"))
		a:equal(crowd.stats().agents, 7)
	end)

	s:it("society tracks relations, factions and gossip", function(a)
		local soc = Kits.create("society", { id = "s" })
		soc.join("ana", { faction = "north" })
		soc.join("bo", { faction = "north" })
		soc.join("cy", { faction = "south" })
		a:equal(soc.affinity("ana", "bo"), 0)
		soc.interact("ana", "bo", 1, 0.5)
		a:gt(soc.affinity("ana", "bo"), 0.4)
		a:gt(soc.disposition("ana", "bo"), 0.4)
		soc.setFactionStanding("north", "south", -0.8)
		a:lt(soc.disposition("ana", "cy"), 0)
		soc.interact("bo", "cy", 1, 0.6)
		local reached = soc.gossip("ana", "cy", -1)
		a:gte(reached, 1)
		a:lt(soc.members.cy.reputation, 0)
		a:equal(#soc.friendsOf("ana", 0.3), 1)
		a:gt(soc.cohesion(), 0)
		soc.tick(10)
		a:gt(soc.stats().interactions, 1)
	end)

	s:it("economy moves prices with supply and demand", function(a)
		local eco = Kits.create("economy", { id = "eco", elasticity = 0.5 })
		eco.defineGood("grain", { basePrice = 10 })
		eco.addMarket("farm", { wealth = 500 })
		eco.addMarket("city", { wealth = 900 })
		eco.setStock("farm", "grain", 400)
		eco.setStock("city", "grain", 5)
		eco.setProduction("farm", "grain", 8)
		eco.setDemand("city", "grain", 6)
		local cheap = eco.priceOf("grain")
		for _ = 1, 20 do eco.tick(0.5) end
		a:gt(eco.totalStock("grain"), 0)
		a:gt(eco.stats().produced, 0)
		a:gt(eco.stats().consumed, 0)
		local moved, price = eco.trade("farm", "city", "grain", 50)
		a:gt(moved, 0)
		a:gt(price, 0)
		a:gt(eco.markets.city.stock.grain, 5)
		a:lt(eco.markets.city.wealth, 900)
		a:gt(eco.balance(), -1)
		a:gt(eco.stats().trades, 0)
		a:ok(cheap > 0)
	end)

	s:it("schedule runs a day and yields to interruptions", function(a)
		local sc = Kits.create("schedule", { id = "sc", startHour = 7 })
		sc.addSlot("sleep", 22, 6, { priority = 3 })
		sc.addSlot("work", 8, 17, { priority = 2, location = v3(10, 0, 0) })
		sc.addSlot("rest", 17, 22, { priority = 1 })
		a:equal(sc.activeAt(9).activity, "work")
		a:equal(sc.activeAt(23).activity, "sleep")
		a:equal(sc.activeAt(2).activity, "sleep")
		local activity = sc.advance(2)
		a:equal(activity, "work")
		a:equal(sc.stats().hour, 9)
		sc.interrupt("flee", 1, 10)
		a:equal(sc.advance(0.25), "flee")
		sc.advance(1.5)
		a:equal(sc.stats().current, "work")
		a:ok(sc.locationFor("work") ~= nil)
		sc.advance(14)
		a:ok(sc.isNight())
		a:gt(sc.stats().changes, 1)
	end)

	s:it("ecology grows populations and couples predator to prey", function(a)
		local eco = Kits.create("ecology", { id = "bio" })
		eco.addSpecies("deer", { population = 200, growth = 0.3, capacity = 800 })
		eco.addSpecies("wolf", { population = 20, growth = -0.1, capacity = 90 })
		eco.link("wolf", "deer", { predation = 0.001, efficiency = 0.4 })
		local startDeer = eco.populationOf("deer")
		for _ = 1, 40 do eco.step(0.5) end
		a:gt(eco.populationOf("deer"), startDeer)
		a:gt(eco.biomass(), 200)
		-- remove the prey and the predator must collapse
		eco.harvest("deer", eco.populationOf("deer"))
		for _ = 1, 200 do eco.step(0.5) end
		a:lt(eco.populationOf("wolf"), 20)
		a:gt(eco.stats().harvested, 0)
		eco.seed("deer", 150)
		a:gt(eco.populationOf("deer"), 100)
		for _ = 1, 400 do eco.step(0.25) end
		a:gte(eco.stats().ticks, 600)
	end)
end)

t:describe("npc/mind", function(s)
	s:it("senses, remembers and decides from real drives", function(a)
		local Mind = A:import("arkher/npc/mind")
		local mind = Mind.new("hero", { seed = 3 })
		mind:place(v3(), v3(0, 0, 1))
		mind:observe("wolf", v3(0, 0, 6), { threat = 0.9, intensity = 0.9, kind = "danger" })
		mind:observe("berry", v3(0, 0, 12), { intensity = 0.4, kind = "food" })
		local attention = mind:sense()
		a:gt(#attention, 0)
		a:equal(attention[1].id, "wolf")
		a:gt(mind.threat, 0.5)
		a:lt(mind.emotion.valence, 0)
		a:gt(mind.memory.stats().episodes, 0)
		local action, score, need = mind:decide(1 / 30)
		a:ok(action ~= nil)
		a:ok(score ~= nil)
		local described = mind:describe()
		a:equal(described.doing, action)
		a:ok(described.feeling ~= nil)
		a:gt(mind:brainBytes(), 0)
	end)

	s:it("a starving mind eats, and learns from the outcome", function(a)
		local Mind = A:import("arkher/npc/mind")
		local mind = Mind.new("hungry", { seed = 11 })
		mind.needs.needs.food.value = 0.02
		local action, _, need = mind:decide(1 / 30)
		a:equal(need, "food")
		a:equal(action, "eat", "a critical drive must override the policy")
		local before = mind.needs.wellbeing()
		mind:act("eat")
		a:gt(mind.needs.wellbeing(), before)
		a:gt(mind.net.stats().updates, 0)
		a:gt(mind.learnings, 0)
		a:gt(mind.net.rewardTotal, 0)
	end)

	s:it("runs a full life loop and degrades with quality", function(a)
		local Mind = A:import("arkher/npc/mind")
		local mind = Mind.new("citizen", { seed = 5 })
		mind:place(v3())
		mind:observe("market", v3(0, 0, 8), { intensity = 0.8, kind = "place" })
		for _ = 1, 60 do mind:update(1 / 10) end
		a:gt(mind.decisions, 50)
		a:gt(mind.memory.stats().written, 5)
		a:gte(mind.memory.factCount(), 1)
		local report = mind:report()
		a:gt(report.brainBytes, 0)
		a:ok(report.emotion ~= nil and report.needs ~= nil)
		local low = mind:applyQuality(0.1)
		a:lte(low.attentionSlots, 2)
		a:lt(low.sightRange, 30)
		a:lt(low.memoryCapacity, 48)
	end)
end)

t:describe("npc/agents", function(s)
	s:it("spawns agents with behaviour, schedule and navigation", function(a)
		local Agents = A:import("arkher/npc/agent")
		local world = Agents.new({ navWidth = 24, navHeight = 24, cellSize = 4 })
		world.nav.blockRect(8, 0, 8, 15)
		local agent = world:spawn("villager", { position = v3(4, 0, 4),
			home = v3(4, 0, 4), work = v3(60, 0, 60), faction = "village" })
		a:ok(agent ~= nil)
		a:gt(agent.tree.stats().nodes, 5)
		a:gt(#agent.schedule.slots, 4)
		a:gt(agent.planner.stats().actions, 3)
		local path = world:pathTo("villager", v3(60, 0, 60))
		a:ok(path ~= nil)
		a:gt(#path, 2, "the wall must force at least one bend into the path")
		-- the second identical request must be served from the cache
		world:pathTo("villager", v3(60, 0, 60))
		a:gt(world.pathHits, 0)
		local plan = world:replan("villager", { paid = true })
		a:ok(plan ~= nil)
		a:gt(#plan, 0)
		a:equal(world:report().agents, 1)
	end)

	s:it("thinks, moves and reacts to threat", function(a)
		local Agents = A:import("arkher/npc/agent")
		local world = Agents.new({})
		world:spawn("guard", { position = v3(0, 0, 0), home = v3(0, 0, 0), work = v3(20, 0, 0) })
		local agent = world:get("guard")
		local activity = world:think("guard", 1 / 10)
		a:ok(activity ~= nil)
		agent.mind.threat = 0.9
		local reaction = world:think("guard", 1 / 10)
		a:equal(reaction, "flee", "a real threat must beat the routine")
		world:goTo("guard", v3(20, 0, 0))
		for _ = 1, 200 do world:update(1 / 30, v3()) end
		a:gt(agent.position:length(), 1)
		a:gt(world.minded, 10)
		a:gt(world:report().frame, 100)
	end)

	s:it("tiers a village and holds a per-frame budget", function(a)
		local Agents = A:import("arkher/npc/agent")
		local world = Agents.new({ budget = 4 })
		for i = 1, 24 do
			world:spawn("npc" .. i, { position = v3(i * 30, 0, 0),
				home = v3(i * 30, 0, 0), work = v3(i * 30 + 10, 0, 0) })
		end
		local result = world:update(1 / 30, v3())
		a:lte(result.processed, 4)
		a:equal(world:report().agents, 24)
		for _ = 1, 30 do world:update(1 / 30, v3()) end
		a:gt(world.skipped, 0)
		local tiers = world:report().byTier
		a:ok(tiers.acting ~= nil or tiers.behaving ~= nil)
		a:ok(tiers.statistical ~= nil, "distant NPCs must fall to the statistical tier")
		local low = world:applyQuality(0.1)
		a:lte(low.budget, 12)
		a:lt(low.actingDistance, 40)
		a:ok(world:despawn("npc1"))
		a:equal(world:report().agents, 23)
	end)
end)

t:describe("sim/world", function(s)
	s:it("keeps living at three fidelities and reifies on approach", function(a)
		local WorldSim = A:import("arkher/sim/world_simulation")
		local sim = WorldSim.new({ seed = 99, fullRadius = 200, reducedRadius = 700 })
		sim:addRegion("valley", { position = v3(0, 0, 0), population = 300 })
		sim:addRegion("ridge", { position = v3(500, 0, 0), population = 120 })
		sim:addRegion("far", { position = v3(4000, 0, 0), population = 80 })
		local counts = sim:setObserver("player", v3(0, 0, 0))
		a:equal(counts.full, 1)
		a:equal(counts.cohort, 1)
		a:equal(counts.statistical, 1)
		a:gt(sim.reifications, 0)
		local live = 0
		for _ in pairs(sim:region("valley").agents) do live = live + 1 end
		a:gt(live, 0, "a full-fidelity region must have real agents")
		-- walking away demotes the region and aggregates its people into cohorts
		sim:setObserver("player", v3(9000, 0, 0))
		a:gt(sim.demotions, 0)
		local remaining = 0
		for _ in pairs(sim:region("valley").agents) do remaining = remaining + 1 end
		a:equal(remaining, 0)
		a:gt(sim:region("valley").cohorts.farmer.count, 0)
	end)

	s:it("runs a deterministic clock, seasons and world events", function(a)
		local WorldSim = A:import("arkher/sim/world_simulation")
		local function build()
			local sim = WorldSim.new({ seed = 4242, timeScale = 600 })
			sim:addRegion("town", { position = v3(), population = 400 })
			sim:addRegion("mine", { position = v3(2000, 0, 0), population = 90 })
			sim:setObserver("player", v3())
			return sim
		end
		local a1 = build()
		local events = 0
		a1.onEvent:connect(function() events = events + 1 end)
		a1:run(20, 1 / 10)
		a:gt(a1.clock.day, 1)
		a:gt(events, 0)
		a:gt(a1.ticks, 100)
		a:ok(a1:seasonName() ~= nil)
		local b1 = build()
		b1:run(20, 1 / 10)
		a:equal(a1:checksum(), b1:checksum(), "the same seed must produce the same world")
		local report = a1:report()
		a:equal(report.regions, 2)
		a:gt(report.events, 0)
		a:gt(report.world.population, 0)
	end)

	s:it("respects the simulation budget under pressure", function(a)
		local WorldSim = A:import("arkher/sim/world_simulation")
		local sim = WorldSim.new({ seed = 7, tickBudget = 12 })
		for i = 1, 20 do
			sim:addRegion("r" .. i, { position = v3(i * 300, 0, 0), population = 50 + i })
		end
		sim:setObserver("player", v3())
		local step = sim:step(1 / 10)
		a:lt(step.simulated, 20)
		a:gt(step.starved, 0)
		local high = sim:applyQuality(1.0)
		local low = sim:applyQuality(0.05)
		a:lt(low.tickBudget, high.tickBudget)
		a:lt(low.fullRadius, high.fullRadius)
		sim:run(3, 1 / 10)
		a:gt(sim:totalPopulation(), 0)
		a:gt(sim:report().ticks, 20)
	end)
end)

t:describe("sim/civilization", function(s)
	s:it("founds settlements, trades and migrates people", function(a)
		local Civ = A:import("arkher/sim/civilization")
		local civ = Civ.new({ seed = 3 })
		civ:found("harbor", { position = v3(0, 0, 0), population = 400,
			specialties = { "food", "wood" }, faction = "crown", prosperity = 0.7 })
		civ:found("mine", { position = v3(300, 0, 0), population = 150,
			specialties = { "ore" }, faction = "crown", prosperity = 0.3, unrest = 0.4 })
		a:equal(civ:report().settlements, 2)
		a:ok(civ:connect("harbor", "mine", { danger = 0.1 }) ~= nil)
		a:ok(civ:routeBetween("mine", "harbor") ~= nil)
		local path = civ:tradePath("harbor", "mine")
		a:ok(path ~= nil)
		civ:run(20, 0.25)
		a:gt(civ.routes[1].volume, 0, "a connected route must actually move goods")
		a:gt(civ.migrations, 0, "people must move toward the better place")
		a:gt(civ:settlement("harbor").population, 400)
		a:lt(civ:settlement("mine").population, 150)
		a:equal(select(1, civ:largest()), "harbor")
	end)

	s:it("laws, wars and revolts change the numbers", function(a)
		local Civ = A:import("arkher/sim/civilization")
		local civ = Civ.new({ seed = 8 })
		civ:found("north", { position = v3(), population = 300, faction = "north" })
		civ:found("south", { position = v3(400, 0, 0), population = 300, faction = "south" })
		local before = civ:settlement("north").safety
		a:ok(civ:enact("north", "curfew") ~= nil)
		a:gt(civ:settlement("north").safety, before)
		a:equal(civ:enact("north", "curfew"), nil)
		a:ok(civ:repeal("north", "curfew"))
		a:near(civ:settlement("north").safety, before, 0.001)
		a:ok(civ:declareWar("north", "south"))
		a:ok(civ:atWar("north", "south"))
		local safety = civ:settlement("north").safety
		civ:run(10, 0.5)
		a:lt(civ:settlement("north").safety, safety)
		a:ok(civ:makePeace("north", "south"))
		a:ok(not civ:atWar("north", "south"))
		a:equal(civ:report().activeWars, 0)
		a:gt(#civ:chronicle(10), 2)
	end)

	s:it("is deterministic and auditable", function(a)
		local Civ = A:import("arkher/sim/civilization")
		local function build()
			local civ = Civ.new({ seed = 1234 })
			civ:found("a", { position = v3(), population = 250, specialties = { "food" } })
			civ:found("b", { position = v3(200, 0, 0), population = 180, specialties = { "ore" } })
			civ:connect("a", "b", { danger = 0.2 })
			return civ
		end
		local x = build()
		local y = build()
		x:run(15, 0.25)
		y:run(15, 0.25)
		a:equal(x:checksum(), y:checksum())
		a:equal(x:totalPopulation(), y:totalPopulation())
		local report = x:report()
		a:equal(report.settlements, 2)
		a:equal(report.routes, 1)
		a:gt(report.ticks, 50)
		a:ok(report.economy ~= nil and report.society ~= nil)
	end)
end)

local r = t:run()
if not t:report() then error("ARKHER round 6 tests failed") end
