-- ARKHER :: Round 5 verification (physics, animation, digital humans)
local A = ARKHER
local TestKit = A:import("arkher/kernel/testkit")
local Kits = A:import("arkher/runtime/kits")
local Vec = A:import("arkher/kernel/vec")
local v3 = Vec.vec3
local t = TestKit.new()

t:describe("motion/kits", function(s)
	s:it("rigidbody integrates, sleeps and conserves momentum", function(a)
		local b = Kits.create("rigidbody", { id = "b1", position = v3(0, 10, 0), mass = 2 })
		a:near(b.invMass, 0.5, 1e-9)
		b.integrate(1 / 60, v3(0, -10, 0))
		a:lt(b.velocity.y, 0)
		a:lt(b.position.y, 10)
		local before = b.momentum():length()
		b.applyImpulse(v3(0, 20, 0))
		a:gt(b.velocity.y, 0)
		a:ok(b.momentum():length() ~= before)
		a:gt(b.kineticEnergy(), 0)
		-- a body at rest with no forces falls asleep
		local rest = Kits.create("rigidbody", { id = "b2", position = v3(), mass = 1 })
		for _ = 1, 200 do rest.integrate(1 / 60, v3()) end
		a:ok(rest.sleeping, "an idle body must sleep")
		rest.wake()
		a:ok(not rest.sleeping)
		local kin = Kits.create("rigidbody", { id = "b3", kinematic = true })
		kin.integrate(1 / 60, v3(0, -10, 0))
		a:near(kin.position.y, 0, 1e-9)
	end)

	s:it("collider computes bounds, support and closest points", function(a)
		local sphere = Kits.create("collider", { id = "s", shape = "sphere",
			center = v3(0, 0, 0), radius = 2 })
		local box = Kits.create("collider", { id = "b", shape = "box",
			center = v3(5, 0, 0), halfExtents = v3(1, 1, 1) })
		a:near(sphere.aabb().min.x, -2, 1e-9)
		a:gt(sphere.volume(), box.volume())
		a:ok(sphere.contains(v3(1, 0, 0)))
		a:ok(not sphere.contains(v3(3, 0, 0)))
		local support = sphere.support(v3(1, 0, 0))
		a:near(support.x, 2, 1e-6)
		local p, d = box.closestPoint(v3(9, 0, 0))
		a:near(p.x, 6, 1e-6)
		a:near(d, 3, 1e-6)
		a:gt(sphere.expandedBy(1).volume(), sphere.volume())
		a:gt(sphere.expandedAABB(1):volume(), 0)
		local capsule = Kits.create("collider", { id = "c", shape = "capsule",
			center = v3(), radius = 0.4, height = 2 })
		local segA, segB = capsule.segment()
		a:gt(segB.y, segA.y)
	end)

	s:it("contact generation builds real manifolds", function(a)
		local c = Kits.create("contact", { id = "cg" })
		local s1 = Kits.create("collider", { id = "s1", shape = "sphere", center = v3(0, 0, 0), radius = 1 })
		local s2 = Kits.create("collider", { id = "s2", shape = "sphere", center = v3(1.5, 0, 0), radius = 1 })
		local far = Kits.create("collider", { id = "s3", shape = "sphere", center = v3(50, 0, 0), radius = 1 })
		local hit = c.test(s1, s2)
		a:ok(hit ~= nil, "overlapping spheres must produce a manifold")
		a:near(hit.depth, 0.5, 1e-6)
		a:near(hit.normal.x, 1, 1e-6)
		a:equal(c.test(s1, far), nil)
		local box = Kits.create("collider", { id = "bx", shape = "box",
			center = v3(0.8, 0, 0), halfExtents = v3(0.5, 0.5, 0.5) })
		a:ok(c.test(s1, box) ~= nil, "sphere vs box must collide")
		local manifolds = c.generate({ { s1, s2 }, { s1, far }, { s1, box } })
		a:equal(#manifolds, 2)
		a:ok(c.deepest() ~= nil)
		a:gt(c.stats().tests, 0)
	end)

	s:it("constraint solver resolves penetration and joints", function(a)
		local solver = Kits.create("constraint", { id = "cs", iterations = 8 })
		local bodies = {
			ground = Kits.create("rigidbody", { id = "ground", position = v3(0, 0, 0), mass = 0 }),
			ball = Kits.create("rigidbody", { id = "ball", position = v3(0, 0.8, 0), mass = 1 }),
		}
		bodies.ball.velocity = v3(0, -5, 0)
		local manifolds = { { a = "ground", b = "ball", normal = v3(0, 1, 0), depth = 0.2,
			point = v3(0, 0.5, 0), restitution = 0.2, friction = 0.5 } }
		solver.solveContacts(manifolds, bodies, 1 / 60)
		a:gt(bodies.ball.velocity.y, -5)
		local beforeY = bodies.ball.position.y
		solver.correctPositions(manifolds, bodies)
		a:gt(bodies.ball.position.y, beforeY - 1e-9)
		a:ok(solver.addJoint("rope", { a = "ground", b = "ball", distance = 1, kind = "distance" }))
		bodies.ball.position = v3(0, 4, 0)
		solver.solveJoints(bodies, 1 / 60)
		a:lt(bodies.ball.position.y, 4)
		a:gt(solver.stats().solves, 0)
		a:ok(solver.removeJoint("rope"))
	end)

	s:it("raycaster answers rays, sweeps and overlaps", function(a)
		local rc = Kits.create("raycaster", { id = "rc" })
		for i = 1, 6 do
			rc.register(Kits.create("collider", { id = "c" .. i, shape = "sphere",
				center = v3(i * 3, 0, 0), radius = 1 }))
		end
		local hit = rc.raycast(v3(-5, 0, 0), v3(1, 0, 0), 100)
		a:ok(hit ~= nil)
		a:equal(hit.id, "c1")
		a:lt(hit.distance, 8)
		a:equal(rc.raycast(v3(-5, 50, 0), v3(1, 0, 0), 100), nil)
		a:gte(#rc.raycastAll(v3(-5, 0, 0), v3(1, 0, 0), 100), 6)
		a:ok(rc.spherecast(v3(-5, 0, 0), v3(1, 0, 0), 0.5, 100) ~= nil)
		local overlaps = rc.overlapSphere(v3(3, 0, 0), 1.5)
		a:gte(#overlaps, 1)
		a:ok(rc.update("c1", v3(0, 40, 0)))
		a:equal(rc.raycast(v3(-5, 0, 0), v3(1, 0, 0), 100).id, "c2")
		a:ok(rc.unregister("c2"))
		a:equal(rc.stats().colliders, 5)
		a:gt(rc.stats().hitRate, 0)
	end)

	s:it("charmotor walks, slides, jumps and crouches", function(a)
		local m = Kits.create("charmotor", { id = "m", position = v3(0, 0, 0), maxSpeed = 6 })
		m.setGround(true, v3(0, 1, 0))
		for _ = 1, 60 do m.move(v3(1, 0, 0), 1 / 60, nil) end
		a:gt(m.position.x, 1)
		a:near(m.speed(), 6, 0.6)
		a:equal(m.locomotionState(), "run")
		a:ok(m.jump())
		a:gt(m.velocity.y, 0)
		a:equal(m.locomotionState(), "jump")
		m.setGround(true, v3(0, 1, 0))
		local tall = m.height
		m.crouch(true)
		a:lt(m.height, tall)
		a:lt(m.maxSpeed, 6.01)
		m.crouch(false)
		a:near(m.height, tall, 1e-6)
		-- a wall makes the motor slide, not stop
		local wall = function(from, to, radius)
			if to.x > 5 then return { normal = v3(-1, 0, 0), distance = 0, point = v3(5, 0, 0) } end
			return nil
		end
		local before = m.position.z
		m.position = v3(4.9, 0, 0)
		for _ = 1, 30 do m.move(v3(1, 0, 0.4):unit(), 1 / 60, wall) end
		a:lte(m.position.x, 5.2)
		a:gt(m.position.z, before)
		a:gt(m.stats().slides, 0)
	end)

	s:it("vehicle drives with suspension, gearbox and steering", function(a)
		local car = Kits.create("vehicle", { id = "car" })
		a:equal(#car.standardChassis(), 4)
		car.updateSuspension(function() return 0.3 end, 1 / 60)
		a:equal(car.gear, 1)
		for _ = 1, 240 do car.step(1 / 60, { throttle = 1, steer = 0 }) end
		a:gt(car.speedKmh(), 5)
		a:gt(car.rpm, car.idleRpm)
		a:gt(car.shifts, 0)
		local inner, outer = car.steerAngles(1)
		a:gt(inner, 0)
		a:gt(math.abs(inner), math.abs(outer))
		local straightInner = car.steerAngles(0)
		a:equal(straightInner, 0)
		local fx, fy = car.tireForce(car.wheels[1], 0.1, 0.05, 1.0)
		a:ok(fx ~= nil and fy ~= nil)
		a:gt(car.stats().wheels, 3)
	end)

	s:it("skeleton resolves hierarchy, poses and masks", function(a)
		local sk = Kits.create("skeleton", { id = "sk" })
		sk.addBone("root", { position = v3(0, 0, 0) })
		sk.addBone("hips", { position = v3(0, 1, 0) }, "root")
		sk.addBone("chest", { position = v3(0, 0.5, 0) }, "hips")
		a:equal(sk.depthOf("chest"), 2)
		a:near(sk.worldOf("chest").position.y, 1.5, 1e-6)
		sk.setLocal("hips", v3(0, 2, 0))
		a:near(sk.worldOf("chest").position.y, 2.5, 1e-6)
		local chain = sk.chain("root", "chest")
		a:equal(#chain, 3)
		local pose = sk.pose()
		a:ok(pose.chest ~= nil)
		sk.setMask("chest", 0)
		sk.applyPose({ chest = { position = v3(0, 9, 0), rotation = v3() } }, 1)
		a:near(sk.bones.chest.position.y, 0.5, 1e-6)
		sk.setMask("chest", 1)
		sk.applyPose({ chest = { position = v3(0, 9, 0), rotation = v3() } }, 1)
		a:near(sk.bones.chest.position.y, 9, 1e-6)
		sk.resetToBind()
		a:near(sk.bones.chest.position.y, 0.5, 1e-6)
		a:equal(sk.stats().bones, 3)
	end)

	s:it("clip samples curves, fires events and compresses", function(a)
		local clip = Kits.create("clip", { id = "walk", duration = 2, loop = true })
		clip.addKey("hips", "position", 0, v3(0, 0, 0))
		clip.addKey("hips", "position", 1, v3(0, 1, 0))
		clip.addKey("hips", "position", 2, v3(0, 0, 0))
		clip.addEvent(0.5, "footstep", { foot = "left" })
		local pose = clip.sample(0.5)
		a:near(pose.hips.position.y, 0.5, 1e-6)
		a:near(clip.sample(3).hips.position.y, 1, 1e-6) -- loops around
		local events = clip.eventsBetween(0.4, 0.6)
		a:equal(#events, 1)
		a:equal(events[1].name, "footstep")
		a:equal(clip.keyCount(), 3)
		clip.addKey("chest", "position", 0, v3())
		clip.addKey("chest", "position", 0.5, v3())
		clip.addKey("chest", "position", 1, v3())
		local removed = clip.compress(0.001)
		a:gt(removed, 0)
		local before = clip.duration
		clip.retime(0.5)
		a:near(clip.duration, before * 0.5, 1e-6)
		a:gt(clip.stats().tracks, 1)
	end)

	s:it("animator layers, crossfades and blend-trees", function(a)
		local sk = Kits.create("skeleton", { id = "sk2" })
		sk.addBone("hips", { position = v3() })
		sk.addBone("chest", { position = v3(0, 0.5, 0) }, "hips")
		local idle = Kits.create("clip", { id = "idle", duration = 1 })
		idle.addKey("hips", "position", 0, v3(0, 0, 0))
		idle.addKey("hips", "position", 1, v3(0, 0, 0))
		local run = Kits.create("clip", { id = "run", duration = 1 })
		run.addKey("hips", "position", 0, v3(0, 1, 0))
		run.addKey("hips", "position", 1, v3(0, 1, 0))
		local an = Kits.create("animator", { id = "an" })
		an.addLayer("base", { weight = 1 })
		an.addClip("idle", idle)
		an.addClip("run", run)
		a:ok(an.play("base", "idle"))
		local pose = an.evaluate(1 / 60, sk)
		a:near(pose.hips.position.y, 0, 1e-6)
		an.play("base", "run", { fade = 0.5 })
		a:ok(an.isBlending("base"))
		an.evaluate(0.25, sk)
		local mid = an.evaluate(0.01, sk)
		a:gt(mid.hips.position.y, 0.1)
		a:lt(mid.hips.position.y, 0.95)
		for _ = 1, 40 do an.evaluate(0.02, sk) end
		a:ok(not an.isBlending("base"))
		a:ok(an.setBlendTree("base", { { threshold = 0, clip = "idle" },
			{ threshold = 4, clip = "run" } }, 0))
		local low = an.evaluate(1 / 60, sk)
		a:near(low.hips.position.y, 0, 1e-6)
		an.setParameter("base", 2)
		local half = an.evaluate(1 / 60, sk)
		a:near(half.hips.position.y, 0.5, 0.05)
		a:gt(an.stats().evaluations, 0)
	end)

	s:it("ik solves two-bone, fabrik and look-at", function(a)
		local ik = Kits.create("ik", { id = "ik" })
		local root, mid, eff = v3(0, 2, 0), v3(0, 1, 0), v3(0, 0, 0)
		local r, k, e, reached = ik.twoBone(root, mid, eff, v3(1, 1, 0), v3(0, 0, 1))
		a:ok(reached, "target inside reach must be reached")
		a:near(e:distance(v3(1, 1, 0)), 0, 0.02)
		a:near((k - r):length(), 1, 0.02)
		local _, _, far, ok2 = ik.twoBone(root, mid, eff, v3(20, 2, 0), v3(0, 0, 1))
		a:ok(not ok2, "an out of reach target cannot be reached")
		a:near((far - root):length(), 2, 0.05)
		local chain = { v3(0, 0, 0), v3(1, 0, 0), v3(2, 0, 0), v3(3, 0, 0) }
		local solved = ik.fabrik(chain, v3(2, 2, 0), 12)
		a:near(solved[1]:distance(v3(0, 0, 0)), 0, 1e-6)
		a:near(solved[#solved]:distance(v3(2, 2, 0)), 0, 0.05)
		local dir, angle = ik.lookAt(v3(), v3(0, 0, 1), v3(1, 0, 0), math.rad(45))
		a:near(angle, math.rad(45), 1e-6)
		a:lt(dir.x, 0.75)
		local target, hipOffset = ik.footPlacement(v3(0, 0.2, 0), 0.0, 0.45)
		a:near(target.y, 0, 1e-6)
		a:near(hipOffset, 0, 1e-9)
		local _, drop = ik.footPlacement(v3(0, 0, 0), 0.3, 0.45)
		a:lt(drop, 0)
		a:gt(ik.stats().solves, 3)
	end)

	s:it("ragdoll activates, settles and recovers", function(a)
		local rd = Kits.create("ragdoll", { id = "rd" })
		rd.addBone("hips", { position = v3(0, 2, 0), mass = 8 })
		rd.addBone("chest", { position = v3(0, 2.4, 0), parent = "hips", length = 0.4, mass = 6 })
		rd.addBone("head", { position = v3(0, 2.8, 0), parent = "chest", length = 0.3, mass = 4 })
		a:equal(rd.stats().bones, 3)
		a:gt(rd.stats().joints, 0)
		rd.setAnimatedPose({ hips = { position = v3(0, 2, 0) },
			chest = { position = v3(0, 2.4, 0) }, head = { position = v3(0, 2.8, 0) } })
		a:ok(rd.activate(v3(2, 0, 0)))
		a:ok(rd.active)
		for _ = 1, 180 do rd.step(1 / 60, 0) end
		a:lt(rd.centerOfMass().y, 2.4)
		a:gte(rd.centerOfMass().y, -0.01)
		local link = rd.bones.head.position:distance(rd.bones.chest.position)
		a:near(link, 0.3, 0.12)
		a:ok(rd.settled())
		local pose = rd.pose()
		a:ok(pose.head ~= nil)
		rd.recover(1)
		a:ok(not rd.active)
		a:near(rd.blend, 0, 1e-6)
	end)
end)

t:describe("physics/world", function(s)
	s:it("simulates a fixed-step deterministic world", function(a)
		local World = A:import("arkher/physics/world")
		local function build()
			local w = World.new({ fixedStep = 1 / 60 })
			w:addBody("floor", { position = v3(0, -1, 0), mass = 0, shape = "box",
				halfExtents = v3(20, 1, 20) })
			for i = 1, 6 do
				w:addBody("ball" .. i, { position = v3(i * 0.4, 3 + i, 0), mass = 1, radius = 0.5 })
			end
			return w
		end
		local w1 = build()
		w1:run(1.0)
		a:gt(w1.steps, 50)
		a:lt(w1.bodies.ball1.position.y, 4)
		local report = w1:report()
		a:equal(report.bodies, 7)
		a:gt(report.pairsTested, 0)
		local w2 = build()
		w2:run(1.0)
		a:equal(w1:checksum(), w2:checksum())
	end)

	s:it("layers, triggers, queries and explosions behave", function(a)
		local World = A:import("arkher/physics/world")
		local w = World.new({})
		w:addBody("a", { position = v3(0, 0, 0), radius = 1, layer = "player" })
		w:addBody("b", { position = v3(1.2, 0, 0), radius = 1, layer = "enemy" })
		w:setLayerRule("player", "enemy", false)
		a:ok(not w:layersCollide("player", "enemy"))
		a:equal(#w:broadphase(), 0)
		w:setLayerRule("player", "enemy", true)
		a:equal(#w:broadphase(), 1)
		local hit = w:raycast(v3(-10, 0, 0), v3(1, 0, 0), 100)
		a:ok(hit ~= nil)
		a:equal(hit.id, "a")
		a:gte(#w:overlapSphere(v3(0.6, 0, 0), 2), 2)
		local fired = 0
		w.onCollision:connect(function() fired = fired + 1 end)
		w:substep(1 / 60)
		a:gt(fired, 0)
		local affected = w:explode(v3(0, 0, 0), 10, 50)
		a:equal(affected, 2)
		a:gt(w.bodies.b.velocity:length(), 0)
		a:ok(w:removeBody("b"))
		a:equal(w:report().bodies, 1)
	end)

	s:it("quality scaling makes physics cheaper", function(a)
		local World = A:import("arkher/physics/world")
		local w = World.new({ gravity = v3() })
		for i = 1, 20 do w:addBody("b" .. i, { position = v3(i, 2, 0), mass = 1 }) end
		local high = w:applyQuality(1.0)
		local low = w:applyQuality(0.1)
		a:lt(low.maxSubsteps, high.maxSubsteps + 1)
		a:lte(low.iterations, high.iterations)
		a:gt(w.bodies.b1.sleepThreshold, 0.1)
		w:run(4.0)
		a:gt(w:sleepingCount(), 0)
		a:gte(w:totalEnergy(), 0)
	end)
end)

t:describe("physics/character_controller", function(s)
	s:it("walks on ground, steps up and depenetrates", function(a)
		local World = A:import("arkher/physics/world")
		local CC = A:import("arkher/physics/character_controller")
		local w = World.new({})
		w:addBody("floor", { position = v3(0, -0.5, 0), mass = 0, shape = "box",
			halfExtents = v3(50, 0.5, 50) })
		local cc = CC.new(w, {})
		local entry = cc:add("hero", { position = v3(0, 0.5, 0) })
		a:ok(entry ~= nil)
		local grounded = cc:probeGround("hero")
		a:ok(grounded, "the floor must be found under the capsule")
		for _ = 1, 60 do cc:update("hero", v3(1, 0, 0), 1 / 60) end
		a:gt(entry.motor.position.x, 0.5)
		a:gt(cc.sweeps, 0)
		-- a body overlapping the capsule is pushed away
		w:addBody("blocker", { position = entry.motor.position + v3(0.1, 0, 0),
			mass = 0, radius = 0.5 })
		local pushed = cc:pushOut("hero")
		a:gt(pushed, 0)
		a:gt(cc.depenetrations, 0)
		local report = cc:report()
		a:equal(report.controllers, 1)
		a:gt(report.sweeps, 0)
	end)

	s:it("buffers jumps, rides platforms and scales quality", function(a)
		local World = A:import("arkher/physics/world")
		local CC = A:import("arkher/physics/character_controller")
		local w = World.new({})
		local cc = CC.new(w, {})
		local entry = cc:add("hero", { position = v3(0, 5, 0) })
		entry.motor.setGround(false)
		a:ok(not cc:requestJump("hero") or entry.motor.jumps > 0)
		w:addBody("lift", { position = v3(0, 0, 0), mass = 0, shape = "box",
			halfExtents = v3(2, 0.5, 2) })
		entry.motor.position = v3(0, 1, 0)
		a:ok(cc:attachPlatform("hero", "lift"))
		w.bodies.lift.teleport(v3(4, 0, 0))
		cc:followPlatform("hero")
		a:near(entry.motor.position.x, 4, 0.01)
		a:ok(cc:detachPlatform("hero"))
		local q = cc:applyQuality(0.1)
		a:equal(q.pushOutIterations, 1)
		a:ok(cc:remove("hero"))
		a:equal(cc:report().controllers, 0)
	end)
end)

t:describe("animation/system", function(s)
	s:it("builds humanoids, plays locomotion and fires events", function(a)
		local Animation = A:import("arkher/animation/animation_system")
		local an = Animation.new({})
		local made = an:buildLocomotionSet({ "hips", "LUpperLeg", "RUpperLeg" })
		a:equal(#made, 3)
		an:createRig("hero", { position = v3() })
		local bones = an:buildHumanoid("hero")
		a:gt(bones, 20)
		a:ok(an:installLocomotionTree("hero") ~= nil)
		local footsteps = 0
		an.onEvent:connect(function(e) if e.event.name == "footstep" then footsteps = footsteps + 1 end end)
		an:setSpeed("hero", 5.0)
		for _ = 1, 120 do an:evaluate("hero", 1 / 60) end
		a:gt(an.evaluations, 100)
		local report = an:report()
		a:equal(report.rigs, 1)
		a:gt(report.bones, 20)
		a:gt(report.keys, 50)
	end)

	s:it("lods a crowd against a per-frame budget", function(a)
		local Animation = A:import("arkher/animation/animation_system")
		local an = Animation.new({ budget = 6 })
		an:buildLocomotionSet({ "hips", "chest" })
		for i = 1, 40 do
			an:createRig("npc" .. i, { position = v3(i * 12, 0, 0) })
			an:buildHumanoid("npc" .. i)
			an:installLocomotionTree("npc" .. i)
		end
		local result = an:update(1 / 60, v3())
		a:lte(result.evaluated, 6)
		a:gt(result.candidates, 0)
		local lodNear = an:updateLOD("npc1", v3())
		local lodFar = an:updateLOD("npc40", v3())
		a:lt(lodNear, lodFar)
		a:equal(an.rigs.npc40.rate, 0)
		for _ = 1, 20 do an:update(1 / 60, v3()) end
		a:gt(an.skipped, 0)
		local q = an:applyQuality(0.1)
		a:lt(q.budget, 12)
	end)

	s:it("solves foot ik and blends a ragdoll", function(a)
		local Animation = A:import("arkher/animation/animation_system")
		local an = Animation.new({})
		an:buildLocomotionSet({ "hips" })
		an:createRig("hero", {})
		an:buildHumanoid("hero")
		an:installLocomotionTree("hero")
		an:setFootTarget("hero", "L", 0)
		an:setFootTarget("hero", "R", 0)
		an:setLookTarget("hero", v3(3, 1.6, 3))
		an:evaluate("hero", 1 / 60)
		local solved = an:solveIK("hero")
		a:gte(solved, 3)
		a:gt(an.ik.stats().solves, 0)
		a:ok(an:attachRagdoll("hero") ~= nil)
		a:ok(an:activateRagdoll("hero", v3(0, 1, 0)))
		for _ = 1, 60 do an:evaluate("hero", 1 / 60) end
		a:ok(an.rigs.hero.ragdoll.active)
		an:recoverRagdoll("hero", 1)
		a:ok(not an.rigs.hero.ragdoll.active)
		a:equal(an:report().ragdolls, 1)
	end)
end)

t:describe("animation/motion_matching", function(s)
	s:it("builds a database and matches the best frame", function(a)
		local Animation = A:import("arkher/animation/animation_system")
		local MM = A:import("arkher/animation/motion_matching")
		local an = Animation.new({})
		an:buildLocomotionSet({ "hips", "LFoot", "RFoot" })
		local mm = MM.new({ minInterval = 0 })
		local idle = mm:buildFromClip("idle", an.clips.idle, { rate = 8, speed = 0 })
		local run = mm:buildFromClip("run", an.clips.run, { rate = 8, speed = 6 })
		a:gt(idle, 5)
		a:gt(run, 3)
		a:equal(mm:report().clips, 2)
		local fast = mm:queryFromMotion(v3(0, 0, 6), v3(0, 0, 1))
		local result = mm:update(1 / 60, fast)
		a:ok(result.searched)
		a:equal(result.clip, "run")
		local still = mm:queryFromMotion(v3(), v3(0, 0, 1))
		for _ = 1, 6 do result = mm:update(1 / 60, still) end
		a:equal(result.clip, "idle")
		a:gt(mm:report().switches, 0)
		a:gt(mm:report().comparisons, 10)
	end)

	s:it("respects the search budget and blends poses", function(a)
		local Animation = A:import("arkher/animation/animation_system")
		local MM = A:import("arkher/animation/motion_matching")
		local an = Animation.new({})
		an:buildLocomotionSet({ "hips" })
		local mm = MM.new({ minInterval = 0.1 })
		mm:buildFromClip("walk", an.clips.walk, { rate = 60, speed = 1.6 })
		a:gt(#mm.frames, 50)
		local low = mm:applyQuality(0.0)
		a:lt(low.searchBudget, 200)
		mm.searchBudget = 8
		local before = mm.comparisons
		mm:update(1, mm:queryFromMotion(v3(0, 0, 1.6), v3(0, 0, 1)))
		a:lte(mm.comparisons - before, 16)
		local skipped = mm:update(1 / 60, mm:queryFromMotion(v3(), v3(0, 0, 1)))
		a:ok(not skipped.searched, "searches must be throttled by minInterval")
		a:ok(mm:currentPose() ~= nil)
	end)
end)

t:describe("character/digital_human", function(s)
	s:it("spawns a full digital human and drives its state machine", function(a)
		local Character = A:import("arkher/character/digital_human")
		local ch = Character.new({ motionMatching = false })
		local hero = ch:spawn("hero", { position = v3(0, 0, 0) })
		a:ok(hero ~= nil)
		a:equal(hero.state, "idle")
		a:gt(#hero.rig.skeleton.order, 20)
		a:ok(ch:canTransition("idle", "run"))
		a:ok(not ch:canTransition("ragdoll", "run"))
		hero.motor.setGround(true, v3(0, 1, 0))
		ch:setIntent("hero", v3(1, 0, 0))
		for _ = 1, 60 do ch:update("hero", 1 / 60) end
		a:gt(hero.motor.position.x, 0.5)
		a:ok(hero.state == "run" or hero.state == "walk")
		a:ok(ch:jump("hero"))
		a:equal(hero.state, "jump")
		a:gt(ch.transitions, 0)
		a:ok(ch:lookAt("hero", v3(5, 1.6, 0)))
		a:equal(ch:report().characters, 1)
	end)

	s:it("ragdolls on death and tiers by distance", function(a)
		local Character = A:import("arkher/character/digital_human")
		local ch = Character.new({ motionMatching = false })
		ch:spawn("npc", { position = v3(0, 0, 0), health = 30 })
		a:equal(ch:damage("npc", 10), 20)
		a:equal(ch:get("npc").state, "idle")
		ch:damage("npc", 50, v3(0, 3, 0))
		a:equal(ch:get("npc").state, "ragdoll")
		a:ok(ch:get("npc").rig.ragdoll.active)
		for _ = 1, 120 do ch:update("npc", 1 / 60) end
		a:ok(ch:getUp("npc", 1 / 60))
		a:equal(ch:get("npc").state, "getup")
		ch:get("npc").motor.position = v3(0, 0, 0)
		local tier = ch:updateTier("npc", v3(0, 0, 0))
		a:equal(tier, 1)
		ch:get("npc").motor.position = v3(0, 0, 900)
		local far = ch:updateTier("npc", v3())
		a:equal(Character.LOD_TIERS[far].name, "crowd")
		a:ok(not Character.LOD_TIERS[far].ik)
	end)

	s:it("runs a crowd with motion matching inside a budget", function(a)
		local Character = A:import("arkher/character/digital_human")
		local ch = Character.new({ motionMatching = true })
		for i = 1, 12 do
			ch:spawn("npc" .. i, { position = v3(i * 15, 0, 0) })
			ch:setIntent("npc" .. i, v3(0, 0, 1))
			ch:get("npc" .. i).motor.setGround(true, v3(0, 1, 0))
		end
		a:ok(ch:get("npc1").matcher ~= nil)
		a:gt(#ch:get("npc1").matcher.frames, 10)
		local result = ch:updateAll(1 / 60, v3())
		a:equal(result.total, 12)
		a:gt(result.updated, 0)
		for _ = 1, 30 do ch:updateAll(1 / 60, v3()) end
		local report = ch:report()
		a:equal(report.characters, 12)
		a:gt(report.frame, 30)
		a:ok(report.byTier ~= nil)
		local q = ch:applyQuality(0.2)
		a:lt(q.heroDistance, 18)
		a:ok(ch:despawn("npc1"))
		a:equal(ch:report().characters, 11)
	end)
end)

local r = t:run()
if not t:report() then error("ARKHER round 5 tests failed") end
