-- ARKHER :: Round 4 verification (materials, rendering, neural)
local A = ARKHER
local TestKit = A:import("arkher/kernel/testkit")
local Kits = A:import("arkher/runtime/kits")
local Vec = A:import("arkher/kernel/vec")
local Spatial = A:import("arkher/kernel/spatial")
local v3 = Vec.vec3
local t = TestKit.new()

t:describe("render/kits", function(s)
	s:it("material blends layers, variants and lods", function(a)
		local m = Kits.create("material", { id = "rock" })
		m.addLayer("base", { albedo = 0x404040, roughness = 0.9, weight = 1 })
		m.addLayer("moss", { albedo = 0x2E7D32, roughness = 0.7, weight = 0.5,
			mask = function(ctx) return ctx.wetness or 0 end })
		local dry = m.resolve({ wetness = 0 })
		local wet = m.resolve({ wetness = 1 })
		a:equal(dry.layers, 1)
		a:equal(wet.layers, 2)
		a:ok(wet.albedo ~= dry.albedo, "moss must change the albedo")
		m.defineVariant("wetRock", { base = { roughness = 0.2 } })
		a:ok(m.applyVariant("wetRock"))
		a:near(m.resolve({}).roughness, 0.2, 0.001)
		a:gt(m.memoryBytes(), 0)
		local lod = m.lodParams(900)
		a:lte(lod.layers, 2)
		a:equal(m.checksum(), m.checksum())
	end)

	s:it("sampler packs an atlas and filters trilinearly", function(a)
		local sm = Kits.create("sampler", { id = "atlas", atlasSize = 128 })
		sm.defineTexture("grad", 16, 16, function(u, v) return u end)
		sm.defineTexture("flat", 8, 8, function() return 0.25 end)
		local packed, failed = sm.packAll()
		a:equal(packed, 2)
		a:equal(failed, 0)
		a:gt(sm.occupancy(), 0)
		a:near(sm.sample("grad", 0.0, 0.5), 0.0, 0.01)
		a:near(sm.sample("grad", 1.0, 0.5), 1.0, 0.01)
		a:near(sm.sample("flat", 0.5, 0.5), 0.25, 0.001)
		a:equal(sm.buildMips("grad"), 5)
		a:near(sm.sampleLod("grad", 0.5, 0.5, 4), 0.5, 0.2)
		a:gt(sm.residentBytes(), 0)
		a:ok(sm.evict("flat"))
	end)

	s:it("shadegraph evaluates, folds and compiles to loadable Luau", function(a)
		local g = Kits.create("shadegraph", { id = "surf" })
		g.addNode("k", "constant", { value = 0.25 })
		g.addNode("rough", "input", { key = "roughness", default = 0.5 })
		g.addNode("sum", "add")
		g.addNode("sat", "saturate")
		g.addNode("out", "output", { channel = "roughness" })
		a:ok(g.connect("k", "sum", 1))
		a:ok(g.connect("rough", "sum", 2))
		a:ok(g.connect("sum", "sat", 1))
		a:ok(g.connect("sat", "out", 1))
		local cycle = g.connect("out", "k", 1)
		a:equal(cycle, nil, "cycles must be rejected")
		local res = g.evaluate({ roughness = 0.5 })
		a:near(res.roughness, 0.75, 0.0001)
		local src = g.compile()
		local fn = load(src)
		a:isType(fn, "function")
		local compiled = fn()({ roughness = 0.5 })
		a:near(compiled.roughness, 0.75, 0.0001)
	end)

	s:it("framegraph culls, orders, aliases and respects the budget", function(a)
		local fg = Kits.create("framegraph", { id = "frame", budgetMs = 6 })
		local ran = {}
		fg.addPass("depth", { writes = { "depthBuf" }, cost = 2,
			execute = function() ran[#ran + 1] = "depth" end })
		fg.addPass("shadow", { writes = { "shadowMap" }, cost = 3, optional = true, priority = 2,
			execute = function() ran[#ran + 1] = "shadow" end })
		fg.addPass("unused", { writes = { "junk" }, cost = 5 })
		fg.addPass("color", { reads = { "depthBuf", "shadowMap" }, writes = { "colorBuf" },
			cost = 3, final = true, execute = function() ran[#ran + 1] = "color" end })
		local order = fg.compile()
		a:equal(fg.culled, 1, "the unused pass must be culled")
		a:equal(order[#order], "color")
		local aliasing = fg.alias()
		a:gte(aliasing.buckets, 1)
		local result = fg.execute({}, 6)
		a:equal(#result.skipped, 1, "the optional shadow pass exceeds the budget")
		a:lte(result.costMs, 6)
		a:equal(#ran, 2)
		local full = fg.execute({}, 20)
		a:equal(#full.skipped, 0)
	end)

	s:it("camera culls, projects and computes screen size", function(a)
		local cam = Kits.create("camera", { id = "main", width = 1280, height = 720 })
		cam.setPosition(v3(0, 0, 0))
		cam.lookAt(v3(0, 0, -1))
		a:ok(cam.visibleSphere(v3(0, 0, -50), 5))
		a:ok(not cam.visibleSphere(v3(0, 0, 50), 5))
		local p = cam.project(v3(0, 0, -10))
		a:near(p.x, 640, 1)
		a:near(p.y, 360, 1)
		a:equal(cam.project(v3(0, 0, 10)), nil)
		local near = cam.screenRadius(v3(0, 0, -10), 1)
		local far = cam.screenRadius(v3(0, 0, -100), 1)
		a:gt(near, far)
		local lodNear = cam.lodFor(v3(0, 0, -5), 1)
		local lodFar = cam.lodFor(v3(0, 0, -500), 1)
		a:lt(lodNear, lodFar)
		local jx, jy = cam.jitter(3)
		a:ok(math.abs(jx) <= 0.5 and math.abs(jy) <= 0.5)
		a:gt(cam.autoExposure(0.18, 1, 10), 0)
	end)

	s:it("visibility floods portals and rejects occluded targets", function(a)
		local vis = Kits.create("visibility", { id = "level", maxDepth = 2 })
		for i = 1, 4 do
			vis.addCell("room" .. i, Spatial.aabb(v3(i * 20, 0, 0), v3(i * 20 + 18, 10, 18)))
			vis.addItem("room" .. i, "prop" .. i)
		end
		vis.addPortal("room1", "room2")
		vis.addPortal("room2", "room3")
		vis.addPortal("room3", "room4")
		local pvs = vis.computePVS("room1", 2)
		a:equal(#pvs, 3)
		a:equal(#vis.visibleItems("room1", 1), 2)
		a:equal(vis.cellAt(v3(25, 1, 1)), "room1")
		vis.addOccluder(Spatial.aabb(v3(-1, -1, 4), v3(1, 5, 6)))
		a:ok(vis.occluded(v3(0, 1, 0), v3(0, 1, 10)))
		a:ok(not vis.occluded(v3(0, 1, 0), v3(10, 1, 0)))
		a:gt(vis.coverage("room1"), 0)
	end)

	s:it("impostor switches representation by screen error", function(a)
		local imp = Kits.create("impostor", { id = "forest", errorThreshold = 2 })
		imp.register("tree", { triangles = 8000, radius = 6 })
		a:equal(#imp.captureViews("tree", 8), 8)
		local mode = imp.select("tree", 10)
		a:equal(mode, "mesh")
		local farMode = imp.select("tree", 400)
		a:ok(farMode == "impostor" or farMode == "culled")
		a:gt(imp.stats().savedTriangles, 0)
		local view = imp.nearestView("tree", v3(1, 0, 0))
		a:ok(view ~= nil)
		imp.register("t2", { triangles = 8000, radius = 6 })
		local proxy = imp.buildHLOD("grove", { "tree", "t2" })
		a:lt(proxy.triangles, 16000)
		local budget = imp.budgetPass({ { id = "tree", distance = 10 }, { id = "t2", distance = 20 } }, 8000)
		a:equal(budget.meshes, 1)
	end)

	s:it("lightrig clusters lights and splits cascades", function(a)
		local rig = Kits.create("lightrig", { id = "rig", maxActive = 4 })
		rig.addLight("sun", { type = "directional", intensity = 2 })
		for i = 1, 6 do
			rig.addLight("lamp" .. i, { position = v3(i * 10, 2, 0), range = 12, intensity = 1 + i * 0.1 })
		end
		local clusters = rig.cluster(Spatial.aabb(v3(-10, -10, -10), v3(80, 20, 20)), 4)
		a:gt(clusters.divisions, 0)
		a:gt(rig.stats().assignments, 0)
		local at = rig.lightsAt(v3(10, 2, 0))
		a:gte(#at, 1)
		local important = rig.importance(v3(60, 2, 0))
		a:lte(#important, 4)
		a:equal(important[1].id, "sun")
		local splits = rig.cascadeSplits(1, 500, 3)
		a:equal(#splits, 3)
		a:lt(splits[1], splits[2])
		a:lt(splits[2], splits[3])
		local intensity, ambient = rig.setSunAngle(math.rad(90))
		a:gt(intensity, 0)
		a:gt(ambient, 0.1)
	end)

	s:it("probe volume bakes SH and interpolates irradiance", function(a)
		local pv = Kits.create("probe", { id = "gi", spacing = 10 })
		local count = pv.place(Spatial.aabb(v3(0, 0, 0), v3(20, 10, 20)), 10)
		a:equal(count, 3 * 2 * 3)
		local baked = pv.bake(function(pos, dir) return dir.y > 0 and 1.0 or 0.1 end, 32)
		a:equal(baked, count)
		local up = pv.sampleAt(v3(10, 5, 10), v3(0, 1, 0))
		local down = pv.sampleAt(v3(10, 5, 10), v3(0, -1, 0))
		a:gt(up, down)
		a:gt(pv.memoryBytes(), 0)
		local dirty = pv.invalidate(Spatial.aabb(v3(-1, -1, -1), v3(11, 11, 11)))
		a:gt(dirty, 0)
		a:equal(pv.dirtyCount(), dirty)
		local done = pv.rebake(function() return 0.5 end, 2)
		a:equal(done, 2)
	end)

	s:it("temporal reconstruction accumulates and rejects ghosts", function(a)
		local tm = Kits.create("temporal", { id = "taa", feedback = 0.9 })
		local jx = select(1, tm.jitter(1))
		local jx2 = select(1, tm.jitter(2))
		a:ok(jx ~= jx2, "jitter must change per frame")
		local v = 0
		tm.advance()
		v = tm.resolve("px", 0.0, { motion = 0 })
		a:equal(v, 0.0, "the first frame has no history to blend")
		for i = 1, 7 do
			tm.advance()
			v = tm.resolve("px", 1.0, { motion = 0 })
		end
		a:gt(v, 0.4, "history must converge toward the new value")
		a:lt(v, 1.0, "convergence must be gradual, not instant")
		a:gte(tm.accumulationOf("px"), 8)
		a:gt(tm.effectiveSamples("px"), 1)
		local clamped, wasClamped = tm.clamp(5.0, { 0.1, 0.2, 0.15 })
		a:ok(wasClamped)
		a:lt(clamped, 1.0)
		local fresh = tm.resolve("px", 0.0, { motion = 999 })
		a:equal(fresh, 0.0, "disocclusion must drop history")
		a:gt(tm.stats().rejections, 0)
		tm.advance()
		a:gt(tm.purge(0), 0, "stale history must be purged")
	end)

	s:it("upscaler adapts resolution and sharpens without ringing", function(a)
		local up = Kits.create("upscaler", { id = "res", targetMs = 16.6, index = 6 })
		a:near(up.scale(), 1.0, 0.001)
		for _ = 1, 5 do up.evaluate(40) end
		a:lt(up.scale(), 1.0)
		for _ = 1, 10 do up.evaluate(4) end
		a:near(up.scale(), 1.0, 0.001)
		up.index = 1
		a:gt(up.savings(1280, 720), 0.5)
		local low = { 0, 0, 1, 1 }
		local high = up.reconstruct(low, 8)
		a:equal(#high, 8)
		a:lte(high[1], 0.05)
		a:gte(high[8], 0.95)
		local sharp = up.sharpen({ 0.5, 0.5, 0.5, 0.9, 0.5 }, 0.5)
		a:equal(#sharp, 5)
		a:gt(up.quality(), 0)
	end)

	s:it("inference really trains, quantizes and round-trips weights", function(a)
		local net = Kits.create("inference", { id = "net", seed = 4242 })
		net.addLayer(2, 6, "tanh")
		net.addLayer(6, 1, "sigmoid")
		a:gt(net.parameters(), 20)
		a:gt(net.flops(), 0)
		local xor = {
			{ input = { 0, 0 }, target = { 0 } },
			{ input = { 0, 1 }, target = { 1 } },
			{ input = { 1, 0 }, target = { 1 } },
			{ input = { 1, 1 }, target = { 0 } },
		}
		local before = net.loss(net.forward({ 0, 1 }), { 1 })
		local after = net.train(xor, 600, 0.5)
		a:lt(after, before, "training must reduce the loss")
		a:lt(after, 0.1, "XOR must actually be learned")
		a:gt(net.forward({ 0, 1 })[1], 0.5)
		a:lt(net.forward({ 1, 1 })[1], 0.5)
		local weights = net.exportWeights()
		a:equal(#weights, net.parameters())
		a:equal(net.importWeights(weights), net.parameters())
		local err = net.quantize(8)
		a:lt(err, 0.05)
		a:lt(net.memoryBytes(), net.parameters() * 4)
	end)
end)


t:describe("materials/framework", function(s)
	s:it("builds a library with presets, wear and budgets", function(a)
		local MF = A:import("arkher/materials/material_framework")
		local lib = MF.new({ tier = "mobile" })
		a:gte(lib:installStandardLibrary(), 15)
		a:ok(lib:get("concrete") ~= nil)
		local dry = lib:resolve("concrete", { wetness = 0, u = 0.5, v = 0.5 })
		a:near(dry.roughness, 0.92, 0.001)
		a:ok(lib:addWear("concrete", "moisture", 0.8) ~= nil)
		local wet = lib:resolve("concrete", { wetness = 1, u = 0.5, v = 0.5 })
		a:lt(wet.roughness, dry.roughness, "moisture must smooth the surface")
		a:equal(dry.normalStrength, 0, "the mobile tier ships without normal maps")
		local report = lib:report()
		a:gt(report.materials, 15)
		a:gt(report.memoryBytes, 0)
		a:equal(lib:checksum(), lib:checksum())
	end)

	s:it("enforces tiers, lods and compaction", function(a)
		local MF = A:import("arkher/materials/material_framework")
		local lib = MF.new({ tier = "mobile" })
		lib:define("hero", { preset = "steel", priority = 1 })
		lib:addWear("hero", "rust", 0.5)
		lib:addWear("hero", "grime", 0.4)
		lib:addWear("hero", "dust", 0.3)
		a:lte(#lib:get("hero").order, 3, "the mobile tier caps the layer count")
		lib:setTier("desktop")
		a:equal(lib:tierConfig().maxLayers, 6)
		lib:addWear("hero", "edgewear", 0.6)
		local near = lib:resolveForDistance("hero", { curvature = 1 }, 5)
		local far = lib:resolveForDistance("hero", { curvature = 1 }, 900)
		a:lt(far.lod == nil and 0 or far.lod, 99)
		a:gte(far.lod, near.lod)
		a:equal(far.normalStrength, 0, "distant surfaces drop their normals")
		a:ok(lib:bakeDetail("hero", 16) ~= nil)
		a:gte(lib:detailAt("hero", 0.5, 0.5, 0), 0)
		a:ok(lib:attachGraph("hero") ~= nil)
		local src = lib:compileGraph("hero")
		local fn = load(src)
		a:isType(fn, "function")
	end)
end)

t:describe("render/lighting", function(s)
	s:it("drives a day cycle with colour temperature and ambient", function(a)
		local L = A:import("arkher/render/lighting")
		local lg = L.new({})
		local noon = lg:setTimeOfDay(12)
		local dawn = lg:setTimeOfDay(6.5)
		local night = lg:setTimeOfDay(0)
		a:gt(noon.intensity, dawn.intensity)
		a:gt(dawn.intensity, night.intensity)
		a:gt(noon.kelvin, dawn.kelvin, "dawn light must be warmer than noon")
		lg:setTimeOfDay(0)
		a:ok(lg:isNight())
		lg:setTimeOfDay(12)
		a:ok(not lg:isNight())
		a:gt(lg.ambient, 0.1)
	end)

	s:it("clusters lights, bakes GI and tonemaps", function(a)
		local L = A:import("arkher/render/lighting")
		local lg = L.new({ bounds = Spatial.aabb(v3(0, 0, 0), v3(96, 32, 96)), probeSpacing = 32 })
		for i = 1, 5 do
			lg:addLight("torch" .. i, { position = v3(i * 16, 4, 16), range = 20, intensity = 2 })
		end
		lg:cluster(4)
		a:gte(#lg:lightsFor(v3(16, 4, 16)), 1)
		a:lte(#lg:lightsFor(v3(16, 4, 16)), lg.rig.maxActive)
		local baked = lg:bakeGI(32)
		a:gt(baked, 0)
		local lit = lg:irradiance(v3(48, 8, 16), v3(0, 1, 0))
		local under = lg:irradiance(v3(48, 8, 16), v3(0, -1, 0))
		a:gt(lit, under, "up-facing normals receive more sky")
		a:equal(#lg:cascadeSplits(1, 500), 3)
		a:lte(#lg:shadowCasters(), 2)
		local nearFog = lg:fogFactor(10, 0)
		local farFog = lg:fogFactor(2000, 0)
		a:lt(nearFog, farFog)
		a:lte(farFog, 1)
		a:lte(lg:tonemap(100), 1.0, "the filmic curve must never clip above 1")
		a:gt(lg:tonemap(0.5), 0)
		local q = lg:applyQuality(0.2)
		a:lte(q.shadowBudget, 1)
		a:gt(lg:invalidateGI(), 0)
		a:gt(lg:relight(4), 0)
	end)
end)

t:describe("render/virtualization", function(s)
	s:it("clusters objects and spends a triangle budget", function(a)
		local V = A:import("arkher/render/virtualization")
		local geo = V.new({ clusterSize = 128, triangleBudget = 40000, drawBudget = 20 })
		for i = 1, 60 do
			geo:add("prop" .. i, { position = v3((i % 10) * 40, 0, math.floor(i / 10) * 40),
				radius = 5, triangles = 4000, material = "rock" })
		end
		a:gt(geo:clusterCount(), 1)
		a:gt(geo:build(2), 0)
		local pass = geo:resolve(v3(0, 2, 0), { radius = 600, screenHeight = 720 })
		a:lte(pass.triangles, 40000 + 20000, "the budget bounds what is drawn")
		a:lte(pass.draws, 20)
		a:gt(#pass.mesh + #pass.impostor + #pass.proxy + #pass.culled, 0)
		local saved, ratio = geo:savings()
		a:gt(saved, 0)
		a:gt(ratio, 0)
		local low = geo:applyQuality(0.1)
		local high = geo:applyQuality(0.9)
		a:lt(low.triangleBudget, high.triangleBudget)
		a:gt(geo:report().objects, 50)
	end)
end)

t:describe("neural/reconstruction", function(s)
	s:it("trains a policy that lowers scale under load", function(a)
		local R = A:import("arkher/neural/reconstruction")
		local rc = R.new({ targetMs = 16.6 })
		local loss = rc:train(200, 0.35)
		a:lt(loss, 0.05, "the reconstruction policy must actually converge")
		local heavy = rc:predict({ frameMs = 38, motion = 2, complexity = 0.9, battery = 0.4 })
		local light = rc:predict({ frameMs = 8, motion = 2, complexity = 0.2, battery = 1.0 })
		a:lt(heavy.scale, light.scale, "heavier frames must render smaller")
		a:gte(heavy.sharpen, 0)
		local policy = rc:exportPolicy(8)
		a:gt(policy.parameters, 20)
		a:lt(policy.quantError, 0.05)
		local rc2 = R.new({ targetMs = 16.6 })
		a:ok(rc2:importPolicy(policy))
	end)

	s:it("reconstructs, accumulates and recovers from a camera cut", function(a)
		local R = A:import("arkher/neural/reconstruction")
		local rc = R.new({ targetMs = 16.6 })
		rc:train(120, 0.35)
		local before = rc.upscaler.index
		for _ = 1, 6 do rc:apply({ frameMs = 40, motion = 0, complexity = 0.9, battery = 0.5 }) end
		a:lt(rc.upscaler.index, before, "sustained load must walk the ladder down")
		local frame = rc:beginFrame()
		a:gte(frame.frame, 1)
		a:ok(math.abs(frame.jitterX) <= 0.5)
		local line = rc:resolveLine("row", { 0.0, 0.2, 0.8, 1.0 }, 8, { motion = 0 })
		a:equal(#line, 8)
		for _ = 1, 6 do rc:resolveLine("row", { 0.0, 0.2, 0.8, 1.0 }, 8, { motion = 0 }) end
		a:gt(rc:effectiveScale(), rc.upscaler.scale() - 0.001)
		a:gt(rc:quality(), 0)
		a:ok(rc:onCameraCut())
		a:equal(rc.temporal.stats().tracked, 0, "a camera cut must drop the whole history")
		a:gt(rc:report().fallbacks, 0)
	end)
end)

t:describe("render/pipeline", function(s)
	s:it("executes a budgeted frame graph end to end", function(a)
		local Renderer = A:import("arkher/render/renderer")
		local r = Renderer.new({ width = 828, height = 1792, budgetMs = 16.6, tier = "mobile" })
		r.materials:installStandardLibrary()
		for i = 1, 40 do
			r.geometry:add("obj" .. i, { position = v3((i % 8) * 30, 0, math.floor(i / 8) * 30),
				radius = 4, triangles = 3000, material = "concrete" })
		end
		r.geometry:build(2)
		r.lighting:bakeGI(48)
		r:teleportCamera(v3(0, 8, 0), v3(60, 0, 60))
		local frame = r:renderFrame(1 / 60)
		a:gte(#frame.executed, 4)
		a:lte(frame.costMs, 16.6 * 1.25)
		a:gt(frame.triangles, 0)
		a:gt(frame.draws, 0)
		a:gt(frame.scale, 0.3)
		local avg = r:run(20, 1 / 60)
		a:gt(avg, 0)
		a:equal(r.frames, 21)
		local breakdown = r:frameBreakdown()
		a:gt(#breakdown, 4)
		a:gte(breakdown[1].costMs, breakdown[#breakdown].costMs)
		a:ok(r:bottleneck().pass ~= nil)
	end)

	s:it("degrades the whole image stack on one quality call", function(a)
		local Renderer = A:import("arkher/render/renderer")
		local r = Renderer.new({ width = 828, height = 1792, budgetMs = 16.6 })
		for i = 1, 30 do
			r.geometry:add("o" .. i, { position = v3(i * 12, 0, 0), radius = 4, triangles = 5000 })
		end
		r.geometry:build(1)
		local high = r:applyQuality(1.0)
		local hiTri = high.geometry.triangleBudget
		local low = r:applyQuality(0.15)
		a:lt(low.geometry.triangleBudget, hiTri)
		a:lte(low.lighting.shadowBudget, 1)
		a:equal(low.tier, "mobile")
		a:lt(low.scale, 1.0)
		r:renderFrame(1 / 60)
		local report = r:report()
		a:gt(report.memoryPeakBytes, 0)
		a:gt(report.frames, 0)
		a:ok(report.materials ~= nil and report.lighting ~= nil and report.reconstruction ~= nil)
		a:ok(r:setViewport(1920, 1080))
		a:equal(r.camera.width, 1920)
	end)
end)

local r = t:run()
if not t:report() then error("ARKHER round 4 tests failed") end
