-- ARKHER smoke boot (temporary bootstrap check)
local A = ARKHER
print("[arkher] modules:", A:count())
local Errors = A:import("arkher/kernel/errors")
local Vec = A:import("arkher/kernel/vec")
local Noise = A:import("arkher/kernel/noise")
local v = Vec.vec3(1, 2, 3) + Vec.vec3(1, 1, 1)
print("[arkher] vec:", tostring(v), "len", v:length())
print("[arkher] noise:", Noise.perlin2D(3.5, 7.25, 42))
print("[arkher] err:", tostring(Errors.new(Errors.Codes.NOT_FOUND, "x")))
