-- ARKHER :: Round 2 hand-written subsystems (Studio / Code / Collaboration)
local A = ARKHER
local TestKit = A:import("arkher/kernel/testkit")
local t = TestKit.new()
local Kits = A:import("arkher/runtime/kits")
local Editor = A:import("arkher/studio/editor")
local Viewport = A:import("arkher/studio/viewport")
local Intelligence = A:import("arkher/code/intelligence")
local VisualScript = A:import("arkher/code/visualscript")
local Workspace = A:import("arkher/collab/workspace")
local Build = A:import("arkher/collab/build")
local Vec = A:import("arkher/kernel/vec")
local Spatial = A:import("arkher/kernel/spatial")

t:describe("studio/kits", function(s)
	s:it("document transactions commit and roll back", function(a)
		local d = Kits.document({ id = "doc", initial = { a = { b = 1 } } })
		a:equal(d.get("a.b"), 1)
		d.begin("edit")
		d.set("a.b", 5)
		d.set("a.c", 9)
		a:equal(d.get("a.b"), 5)
		d.rollback()
		a:equal(d.get("a.b"), 1)
		d.begin("edit2")
		d.set("a.b", 7)
		local ok, n = d.commit()
		a:ok(ok)
		a:equal(n, 1)
		a:ok(d.isDirty())
		d.markSaved()
		a:equal(d.isDirty(), false)
	end)
	s:it("commands undo, redo, group and coalesce", function(a)
		local c = Kits.commands({})
		local v = 0
		c.execute({ label = "inc", doFn = function() v = v + 1 end, undoFn = function() v = v - 1 end })
		c.execute({ label = "inc", doFn = function() v = v + 1 end, undoFn = function() v = v - 1 end })
		a:equal(v, 2)
		c.undo()
		a:equal(v, 1)
		c.redo()
		a:equal(v, 2)
		c.beginGroup("bulk")
		for _ = 1, 3 do c.execute({ label = "g", doFn = function() v = v + 10 end, undoFn = function() v = v - 10 end }) end
		c.endGroup()
		a:equal(v, 32)
		c.undo()
		a:equal(v, 2)
	end)
	s:it("selection tracks primary and filters", function(a)
		local sel = Kits.selection({})
		sel.add("a") sel.add("b") sel.toggle("c") sel.toggle("b")
		a:equal(sel.count(), 2)
		a:equal(sel.contains("b"), false)
		sel.addFilter("notA", function(id) return id ~= "a" end)
		a:equal(#sel.filtered(), 1)
	end)
	s:it("layout docks, splits and serializes", function(a)
		local l = Kits.layout({})
		l.addPanel("Viewport") l.addPanel("Inspector")
		l.split("Viewport", "vertical", "Console", 0.7)
		l.dock("Inspector", "Console")
		a:gte(l.stats().panels, 3)
		local blob = l.save()
		l.setVisible("Console", false)
		a:equal(#l.visiblePanels(), l.stats().panels - 1)
		a:ok(l.restore(blob))
	end)
	s:it("widget tree binds data and renders dirty nodes", function(a)
		local w = Kits.widget({})
		local root = w.create("Frame", { size = 100 })
		local label = w.create("Text", { text = "" }, root)
		local counter = 0
		w.bind(label, "text", function() return "count " .. counter end)
		w.render()
		counter = 5
		a:equal(w.update(), 1)
		local painted = w.render()
		a:equal(painted, 1)
		a:equal(w.nodes[label].props.text, "count 5")
	end)
	s:it("inspector builds from reflection and applies edits", function(a)
		local Reflection = A:import("arkher/kernel/reflection")
		Reflection.defineType("TestLight", { fields = {
			intensity = { type = "number", default = 1, min = 0, max = 10, editor = { group = "Light" } },
			name = { type = "string", default = "light" } } })
		local target = { intensity = 2, name = "sun" }
		local insp = Kits.inspector({})
		insp.attach(target, "TestLight")
		a:equal(#insp.fields(), 2)
		local ok, clamped = insp.edit("intensity", 99)
		a:ok(ok)
		a:equal(clamped, 10)
		a:equal(insp.apply(), 1)
		a:equal(target.intensity, 10)
		local common = insp.multiSelect({ { intensity = 1 }, { intensity = 3 } })
		a:equal(common.intensity, "<mixed>")
	end)
	s:it("nodegraph type-checks, executes and compiles", function(a)
		local g = Kits.nodegraph({})
		g.defineType("Num", { inputs = {}, outputs = { { name = "out", type = "number" } },
			fn = function(_, p) return { out = p.v } end })
		g.defineType("Sum", { inputs = { { name = "a", type = "number", required = true },
			{ name = "b", type = "number", required = true } }, outputs = { { name = "out", type = "number" } },
			fn = function(i) return { out = i.a + i.b } end })
		g.defineType("Str", { inputs = {}, outputs = { { name = "out", type = "string" } } })
		local n1 = g.addNode("Num", { v = 4 })
		local n2 = g.addNode("Num", { v = 6 })
		local sum = g.addNode("Sum", {})
		local str = g.addNode("Str", {})
		a:ok(g.connect(n1, "out", sum, "a"))
		a:ok(g.connect(n2, "out", sum, "b"))
		local ok, err = g.connect(str, "out", sum, "a")
		a:equal(ok, false)
		local values = g.evaluate({})
		a:equal(values[sum .. ":out"], 10)
	end)
	s:it("source kit tokenizes, finds symbols and diagnoses", function(a)
		local code = [[
local function alpha(x)
	local y = x * 2
	return y
end
local function alpha(z) return z end
]]
		local src = Kits.source({ text = code })
		local tokens = src.tokenize()
		a:gt(#tokens, 20)
		local symbols = src.extractSymbols()
		a:gte(#symbols, 3)
		local diags = src.analyze()
		local hasDuplicate = false
		for _, d in ipairs(diags) do if d.rule == "duplicate-function" then hasDuplicate = true end end
		a:ok(hasDuplicate)
		a:gt(#src.complete("al"), 0)
		a:gt(src.metrics().tokens, 10)
	end)
	s:it("session enforces locks and rebases ops", function(a)
		local sess = Kits.session({})
		sess.join("ana", "editor")
		sess.join("bob", "editor")
		sess.join("cid", "viewer")
		a:ok(sess.acquireLock("ana", "objects.wall"))
		a:equal(sess.acquireLock("bob", "objects.wall"), false)
		a:ok(sess.submit("ana", { kind = "set", path = "objects.wall", value = 1 }))
		local ok, err = sess.submit("bob", { kind = "set", path = "objects.wall", value = 2 })
		a:equal(ok, false)
		a:equal(select(2, sess.submit("cid", { kind = "set", path = "x", value = 1 })), "read-only role")
		local rebased = sess.rebase({ kind = "set", path = "objects.wall", value = 3 }, 0)
		a:ok(rebased.conflict)
		a:equal(#sess.activeUsers(), 3)
	end)
	s:it("three-way merge resolves and detects conflicts", function(a)
		local m = Kits.merge({})
		local base = { a = 1, b = 2, nested = { x = 1 } }
		local ours = { a = 5, b = 2, nested = { x = 1 } }
		local theirs = { a = 1, b = 9, nested = { x = 7 } }
		local merged, conflicts = m.threeWay(base, ours, theirs)
		a:equal(#conflicts, 0)
		a:equal(merged.a, 5)
		a:equal(merged.b, 9)
		a:equal(merged.nested.x, 7)
		local _, conflicts2 = m.threeWay({ v = 1 }, { v = 2 }, { v = 3 })
		a:equal(#conflicts2, 1)
		a:ok(m.resolve("v", "theirs"))
	end)
	s:it("taskgraph builds incrementally", function(a)
		local tg = Kits.taskgraph({})
		local runs = 0
		tg.addTask("compile", { inputs = { "v1" }, fn = function() runs = runs + 1 return "obj" end })
		tg.addTask("link", { deps = { "compile" }, fn = function(art) return "bin:" .. art["compile"].value end })
		tg.run()
		a:equal(runs, 1)
		tg.run()
		a:equal(runs, 1, "second build must hit the cache")
		a:equal(tg.artifact("link"), "bin:obj")
		tg.invalidate("compile")
		tg.run()
		a:equal(runs, 2)
	end)
end)

t:describe("studio/editor", function(s)
	local ed
	s:it("boots with panels, commands and tools", function(a)
		ed = Editor.new({ projectName = "demo" })
		a:gte(#ed:commandList(), 13)
		a:gte(ed.layout.stats().panels, 12)
		a:ok(ed:setTool("translate"))
		a:equal(ed.activeTool, "translate")
	end)
	s:it("creates, selects, transforms and undoes objects", function(a)
		local id = ed:run("object.create", { id = "wall", position = { 0, 0, 0 }, size = { 10, 5, 1 } })
		a:equal(id, "wall")
		ed:run("object.create", { id = "floor", position = { 0, -3, 0 }, size = { 20, 1, 20 } })
		a:equal(ed:objectCount(), 2)
		ed:selectAll()
		a:equal(ed.selection.count(), 2)
		ed:transformSelection(Vec.vec3(5, 0, 0))
		a:equal(ed.document.get("objects.wall.position")[1], 5)
		ed.commands.undo()
		a:equal(ed.document.get("objects.wall.position")[1], 0)
	end)
	s:it("duplicates, copies, pastes and deletes", function(a)
		ed.selection.set({ "wall" })
		local dup = ed:run("object.duplicate")
		a:equal(#dup, 1)
		ed:run("edit.copy")
		local pasted = ed:run("edit.paste")
		a:equal(pasted, 1)
		local before = ed:objectCount()
		ed.selection.set({ "wall" })
		a:equal(ed:run("object.delete"), 1)
		a:equal(ed:objectCount(), before - 1)
		ed.commands.undo()
		a:equal(ed:objectCount(), before)
	end)
	s:it("frames selection and inspects objects", function(a)
		ed:selectAll()
		local bounds = ed:selectionBounds()
		a:ok(bounds ~= nil)
		a:gt(ed:frameSelection(), 0)
		local layout = ed:inspect("wall")
		a:ok(layout.groups ~= nil)
	end)
	s:it("searches the command palette and saves", function(a)
		a:gt(#ed:searchCommands("undo"), 0)
		local blob = ed:save()
		a:gt(#blob, 20)
		local ed2 = Editor.new({})
		a:ok(ed2:load(blob))
		a:equal(ed2:objectCount(), ed:objectCount())
	end)
end)

t:describe("studio/viewport", function(s)
	s:it("converts screen rays and picks geometry", function(a)
		local vp = Viewport.new({ width = 800, height = 600 })
		vp.camera.position = Vec.vec3(0, 0, 50)
		vp.camera.target = Vec.vec3(0, 0, 0)
		local origin, dir = vp:screenToRay(400, 300)
		a:near(dir.z, -1, 0.01)
		local prims = { { id = "box", bounds = Spatial.aabb(Vec.vec3(-5, -5, -5), Vec.vec3(5, 5, 5)) } }
		local bvh = Spatial.bvh(prims)
		local hit = vp:pick(400, 300, bvh)
		a:equal(hit.id, "box")
	end)
	s:it("projects world points back to screen", function(a)
		local vp = Viewport.new({ width = 800, height = 600 })
		vp.camera.position = Vec.vec3(0, 0, 50)
		vp.camera.target = Vec.vec3(0, 0, 0)
		local x, y = vp:worldToScreen(Vec.vec3(0, 0, 0))
		a:near(x, 400, 1)
		a:near(y, 300, 1)
	end)
	s:it("snaps gizmo drags to the grid", function(a)
		local vp = Viewport.new({})
		vp.snap.translate = 5
		vp:beginDrag("x", Vec.vec3(0, 0, 0))
		local delta = vp:updateDrag(Vec.vec3(7.4, 12, 3))
		a:equal(delta.x, 5)
		a:equal(delta.y, 0)
		vp:endDrag()
		a:equal(vp.gizmo.active, false)
	end)
	s:it("orbits, pans, dollies and frames", function(a)
		local vp = Viewport.new({})
		local before = vp.camera.position:length()
		vp:orbit(0.5, 0.2)
		a:near(vp.camera.position:length(), before, 0.01)
		vp:pan(3, 2)
		local box = Spatial.aabb(Vec.vec3(-10, -10, -10), Vec.vec3(10, 10, 10))
		a:gt(vp:frame(box), 0)
		a:gt(vp:measure(Vec.vec3(0, 0, 0), Vec.vec3(3, 4, 0)), 4.9)
	end)
end)

t:describe("code/intelligence", function(s)
	local intel
	s:it("indexes files and extracts symbols", function(a)
		intel = Intelligence.new({})
		intel:index("main.lua", [[
local Config = A:import("arkher/kernel/config")
local function boot(engine)
	local ready = true
	return ready
end
function boot2() return 2 end
]])
		intel:index("util.lua", "local function helper() return boot() end")
		a:equal(intel:report().files, 2)
		a:ok(intel:definitionOf("boot") ~= nil)
		a:gt(#intel:referencesOf("boot"), 0)
	end)
	s:it("analyzes, completes and reports metrics", function(a)
		local result = intel:analyzeAll()
		a:equal(result.errors, 0)
		a:gt(#intel:complete("main.lua", "bo"), 0)
		local m = intel:projectMetrics()
		a:gt(m.lines, 5)
		a:gt(m.tokens, 20)
		local graph = intel:dependencyGraph()
		a:gt(graph.edges, 0)
	end)
	s:it("renames symbols and regenerates docs", function(a)
		local count = intel:rename("main.lua", "boot2", "bootstrap")
		a:gt(count, 0)
		local docs = intel:generateDocs("main.lua")
		a:ok(string.find(docs, "bootstrap") ~= nil)
	end)
	s:it("detects unbalanced code as an error", function(a)
		intel:index("broken.lua", "local function x() if true then return 1 end")
		local diags = intel:analyze("broken.lua")
		local hasError = false
		for _, d in ipairs(diags) do if d.severity == "error" then hasError = true end end
		a:ok(hasError)
	end)
end)

t:describe("code/visualscript", function(s)
	s:it("executes a typed graph", function(a)
		local vs = VisualScript.new()
		local n1 = vs:node("Number", { value = 8 })
		local n2 = vs:node("Number", { value = 4 })
		local add = vs:node("Add", {})
		vs:connect(n1, "out", add, "a")
		vs:connect(n2, "out", add, "b")
		local mul = vs:node("Multiply", {})
		vs:connect(add, "out", mul, "a")
		local three = vs:node("Number", { value = 3 })
		vs:connect(three, "out", mul, "b")
		local values = vs:run({})
		a:equal(values[add .. ":out"], 12)
		a:equal(values[mul .. ":out"], 36)
	end)
	s:it("compiles to Luau that actually loads", function(a)
		local vs = VisualScript.new()
		local n1 = vs:node("Number", { value = 10 })
		local n2 = vs:node("Number", { value = 32 })
		local add = vs:node("Add", {})
		vs:connect(n1, "out", add, "a")
		vs:connect(n2, "out", add, "b")
		local print_ = vs:node("Print", {})
		vs:connect(add, "out", print_, "value")
		local src = vs:compile("demoGraph")
		a:ok(src ~= nil)
		a:ok(string.find(src, "local v"))
		local ok, err = vs:verifyCompiled()
		a:ok(ok, tostring(err))
	end)
	s:it("validates required inputs and cycles", function(a)
		local vs = VisualScript.new()
		local add = vs:node("Add", {})
		local ok, errors = vs:validate()
		a:equal(ok, false)
		a:gte(#errors, 2)
		a:gte(#vs:nodeTypes(), 9)
	end)
end)

t:describe("collab/workspace + build", function(s)
	local ws
	s:it("collaborates with locks and presence", function(a)
		ws = Workspace.new({ initial = { objects = {} } })
		ws:join("ana", "editor")
		ws:join("bob", "editor")
		a:ok(ws:lock("ana", "objects.tower"))
		a:ok(ws:edit("ana", "objects.tower", { height = 40 }))
		local ok = ws:edit("bob", "objects.tower", { height = 10 })
		a:equal(ok, false)
		ws:unlock("ana", "objects.tower")
		a:ok(ws:edit("bob", "objects.tower", { height = 12 }))
		a:equal(#ws:sync(0), 2)
		a:gt(ws:comment("ana", "objects.tower", "too short"), 0)
	end)
	s:it("commits, branches and merges without conflict", function(a)
		local c1 = ws:commit("ana", "initial")
		a:ok(c1 ~= nil)
		ws:branch("feature")
		ws:checkout("feature")
		ws:join("cid", "editor")
		ws:edit("cid", "objects.bridge", { span = 100 })
		ws:commit("cid", "add bridge")
		ws:checkout("main")
		ws:edit("ana", "objects.road", { length = 500 })
		ws:commit("ana", "add road")
		local merged, conflicts = ws:merge("feature", "ana")
		a:ok(merged ~= nil, tostring(conflicts))
		a:ok(ws.workingTree.objects.bridge ~= nil)
		a:ok(ws.workingTree.objects.road ~= nil)
		a:gte(#ws:history("main"), 3)
	end)
	s:it("runs an incremental build pipeline with gates", function(a)
		local b = Build.new({})
		b:standardPipeline({ name = "demo", version = "1.0.0", assetCount = 12, fileCount = 40,
			testsPassed = 87, testsFailed = 0, assetBytes = 1000000, channel = "release" })
		b:addGate("tests-must-pass", function(ctx) return (ctx.failed or 0) == 0, "tests failing" end)
		b:addGate("size-limit", function(ctx) return (ctx.sizeMB or 0) < 100, "bundle too large" end)
		local report = b:run()
		a:equal(report.error, nil)
		a:gte(#report.executed, 7)
		local report2 = b:run()
		a:equal(#report2.executed, 0, "everything should be cached")
		a:ok(b:checkGates({ failed = 0, sizeMB = 20 }))
		local ok, blocked = b:checkGates({ failed = 3, sizeMB = 20 })
		a:equal(ok, false)
		a:equal(#blocked, 1)
		b:invalidate("run.tests")
		a:gte(#b:run().executed, 1)
	end)
end)

local r = t:run()
if not t:report() then error("ARKHER round 2 subsystem tests failed") end
