-- ARKHER :: Round 3 world / terrain / procedural kits and subsystems
local A = ARKHER
local TestKit = A:import("arkher/kernel/testkit")
local t = TestKit.new()
local Kits = A:import("arkher/runtime/kits")
local Vec = A:import("arkher/kernel/vec")
local Spatial = A:import("arkher/kernel/spatial")
local v3 = Vec.vec3

t:describe("world/kits", function(s)
	s:it("scenegraph parents, resolves world transforms and culls", function(a)
		local g = Kits.scenegraph({})
		g.addNode("world", { position = v3(0, 0, 0) })
		g.addNode("city", { position = v3(100, 0, 0), tags = { "city" } }, "world")
		g.addNode("tower", { position = v3(10, 0, 0), tags = { "building", "city" } }, "city")
		a:equal(g.worldPosition("tower").x, 110)
		g.setPosition("city", v3(200, 0, 0))
		a:equal(g.worldPosition("tower").x, 210)
		a:equal(g.depthOf("tower"), 2)
		a:equal(#g.withTag("city"), 2)
		a:equal(#g.descendants("world"), 2)
		a:equal(g.setParent("world", "tower"), false, "cycles must be rejected")
		local visible = g.visibleFrom(v3(210, 0, 0), 50)
		a:gte(#visible, 1)
		a:ok(g.bounds() ~= nil)
		a:equal(g.remove("city"), 2)
		a:equal(g.stats().nodes, 1)
	end)
	s:it("prefab propagates template edits but respects overrides", function(a)
		local p = Kits.prefab({})
		p.define("lamp", { props = { intensity = 5, color = "warm" } })
		local i1 = p.instantiate("lamp")
		local i2 = p.instantiate("lamp", { intensity = 12 })
		a:equal(p.editTemplate("lamp", "intensity", 8), 1)
		a:equal(p.instances[i1].props.intensity, 8)
		a:equal(p.instances[i2].props.intensity, 12)
		a:equal(p.diff(i2).intensity, 12)
		p.revert(i2, "intensity")
		a:equal(p.instances[i2].props.intensity, 8)
		a:equal(#p.instancesOf("lamp"), 2)
	end)
	s:it("heightfield sculpts, samples, erodes and LODs", function(a)
		local hf = Kits.heightfield({ width = 32, height = 32, cellSize = 4 })
		hf.applyNoise({ frequency = 0.08, amplitude = 50, seed = 99 })
		local lo, hi = hf.range()
		a:gt(hi - lo, 1)
		hf.raise(16, 16, 5, 20)
		a:gt(hf.get(16, 16), lo)
		local before = hf.get(16, 16)
		hf.lower(16, 16, 5, 5)
		a:lt(hf.get(16, 16), before)
		hf.flatten(8, 8, 4, 0, 1)
		a:near(hf.get(8, 8), 0, 0.001)
		local mid = hf.sample(4 * 15.5, 4 * 15.5)
		a:isType(mid, "number")
		a:gte(hf.erodeThermal(2, 0.5, 0.5), 0)
		a:gt(hf.erodeHydraulic(8, 3), 0)
		local n = hf.normalAt(16, 16)
		a:near(n:length(), 1, 0.001)
		a:gte(hf.slopeAt(16, 16), 0)
		hf.normalize(0, 100)
		local lo2, hi2 = hf.range()
		a:near(lo2, 0, 0.001)
		a:near(hi2, 100, 0.001)
		local lod = hf.downsample()
		a:equal(lod.width, 16)
		a:equal(lod.cellSize, 8)
		a:isType(hf.checksum(), "number")
	end)
	s:it("voxel fills, carves, flood-fills and counts real surface faces", function(a)
		local v = Kits.voxel({})
		a:equal(v.fillBox(1, 1, 1, 3, 3, 3, "rock"), 27)
		a:equal(v.stats().voxels, 27)
		a:equal(v.get(2, 2, 2), "rock")
		a:equal(#v.neighbors(2, 2, 2), 6)
		a:equal(v.surfaceFaces(), 54, "a 3x3x3 cube has 54 exposed faces")
		a:equal(v.carveSphere(2, 2, 2, 0.9), 1)
		a:equal(v.stats().voxels, 26)
		v.fillSphere(20, 20, 20, 2, "snow")
		a:gt(v.histogram().snow, 5)
		a:gt(v.floodFill(1, 1, 1, "soil"), 10)
		a:ok(v.bounds() ~= nil)
	end)
	s:it("spline evaluates, measures arc length and offsets", function(a)
		local sp = Kits.spline({ points = { v3(0, 0, 0), v3(50, 0, 0), v3(100, 0, 50), v3(150, 0, 50) } })
		local mid = sp.evaluate(0.5)
		a:gt(mid.x, 10)
		local len = sp.arcLength()
		a:gt(len, 100)
		local at = sp.pointAtDistance(len / 2)
		a:isType(at.x, "number")
		a:equal(#sp.resample(10), 10)
		local off = sp.offset(10, 8)
		a:equal(#off, 9)
		local _, tt, dist = sp.closestPoint(v3(50, 0, 5))
		a:gte(tt, 0)
		a:lt(dist, 60)
		a:near(sp.tangent(0.5):length(), 1, 0.01)
	end)
	s:it("mesh builds boxes, extrusions, normals and welds", function(a)
		local m = Kits.mesh({})
		m.box(v3(0, 0, 0), v3(10, 10, 10))
		a:equal(m.stats().vertices, 8)
		a:equal(m.stats().triangles, 12)
		a:equal(m.computeNormals(), 8)
		a:near(m.area(), 600, 1)
		local poly = { v3(0, 0, 0), v3(10, 0, 0), v3(10, 0, 10), v3(0, 0, 10) }
		a:equal(m.extrude(poly, 20), 4)
		a:gt(m.stats().triangles, 12)
		a:ok(m.bounds() ~= nil)
		a:gte(m.weld(), 0)
		a:gte(m.simplify(1e-6), 0)
	end)
	s:it("chunker streams by distance with prefetch and LOD", function(a)
		local ch = Kits.chunker({ size = 100, radius = 250, maxPerTick = 8 })
		a:equal(ch.keyOf(150, -50), "1,-1")
		local toLoad, toUnload = ch.update(v3(0, 0, 0))
		a:gt(#toLoad, 5)
		a:equal(#toUnload, 0)
		a:gt(ch.pump(), 0)
		a:gt(ch.stats().loaded, 0)
		local _, unload2 = ch.update(v3(5000, 0, 5000))
		a:gt(#unload2, 0)
		a:equal(#ch.neighbors("0,0", 1), 8)
		a:equal(ch.lodOf("0,0", v3(0, 0, 0)), 0)
		a:equal(ch.lodOf("9,9", v3(0, 0, 0)), 3)
	end)
	s:it("wfc solves a constrained tiling deterministically", function(a)
		local w = Kits.wfc({})
		w.defineTile("grass", { up = "g", down = "g", left = "g", right = "g" }, 3)
		w.defineTile("coast", { up = "g", down = "w", left = "c", right = "c" }, 2)
		w.defineTile("water", { up = "w", down = "w", left = "w", right = "w" }, 3)
		local grid = w.solve(6, 6, 42)
		a:equal(#grid, 36)
		local again = Kits.wfc({})
		again.defineTile("grass", { up = "g", down = "g", left = "g", right = "g" }, 3)
		again.defineTile("coast", { up = "g", down = "w", left = "c", right = "c" }, 2)
		again.defineTile("water", { up = "w", down = "w", left = "w", right = "w" }, 3)
		local grid2 = again.solve(6, 6, 42)
		for i = 1, 36 do a:equal(grid[i], grid2[i]) end
		a:gt(w.stats().collapses, 0)
	end)
	s:it("lsystem rewrites and interprets into geometry", function(a)
		local l = Kits.lsystem({ axiom = "F", angle = 25, step = 5 })
		l.addRule("F", "F[+F]F[-F]F")
		local s1 = l.iterate(1)
		a:equal(s1, "F[+F]F[-F]F")
		l.iterate(1)
		a:gt(#l.current, 40)
		local segments = l.interpret(v3(0, 0, 0))
		a:gt(#segments, 10)
		a:gt(l.totalLength(), 20)
		a:ok(l.bounds() ~= nil)
		l.reset()
		a:equal(l.stats().iterations, 0)
	end)
	s:it("scatter respects minimum distance and masks", function(a)
		local sc = Kits.scatter({ minDistance = 12, seed = 5 })
		local bounds = Spatial.aabb(v3(0, 0, 0), v3(200, 0, 200))
		local pts = sc.generate(bounds, 400)
		a:gt(#pts, 20)
		a:gte(sc.minimumSpacing(), 12)
		a:gt(sc.stats().rejected, 0)
		sc.addMask("north", function(p) return p.z > 100 end)
		local masked = sc.generate(bounds, 400)
		for _, p in ipairs(masked) do a:gt(p.z, 100) end
		local removed = sc.filterBySlope(function(p) return p.x / 200 end, 0.5)
		a:gte(removed, 0)
		a:gte(#sc.cluster(40), 1)
	end)
	s:it("network routes with A* and reports topology", function(a)
		local n = Kits.network({})
		local ids = {}
		for i = 0, 3 do
			for j = 0, 3 do
				ids[i .. "," .. j] = n.addNode(v3(i * 100, 0, j * 100))
			end
		end
		for i = 0, 3 do
			for j = 0, 3 do
				if i < 3 then n.addEdge(ids[i .. "," .. j], ids[(i + 1) .. "," .. j], {}) end
				if j < 3 then n.addEdge(ids[i .. "," .. j], ids[i .. "," .. (j + 1)], {}) end
			end
		end
		local path, cost = n.route(ids["0,0"], ids["3,3"])
		a:ok(path ~= nil)
		a:equal(#path, 7)
		a:near(cost, 600, 0.001)
		a:equal(#n.junctions(3), 12, "8 edge nodes (degree 3) + 4 interior (degree 4)")
		a:equal(#n.deadEnds(), 0)
		a:ok(n.connected())
		a:near(n.totalLength(), 2400, 0.001)
		local near = n.nearestNode(v3(95, 0, 5))
		a:equal(near, ids["1,0"])
	end)
	s:it("simulation tiers work by observer distance and keeps living unobserved", function(a)
		local sim = Kits.simulation({ fullRadius = 100, reducedRadius = 400, budget = 100 })
		for i = 1, 10 do
			sim.spawn("npc" .. i, {
				position = v3(i * 100, 0, 0),
				state = { wealth = 10 },
				update = function(st) st.wealth = st.wealth + 1 end,
				aggregate = function(st, elapsed) st.wealth = st.wealth + elapsed * 0.5 end,
			})
		end
		local counts = sim.setObserver(v3(0, 0, 0))
		a:equal(counts.full, 1)
		a:equal(counts.reduced, 3)
		a:equal(counts.statistical, 6)
		for _ = 1, 30 do sim.tick(1 / 30) end
		a:gt(sim.entities["npc1"].state.wealth, 10)
		a:gt(sim.entities["npc10"].state.wealth, 10, "unobserved entities must keep living")
		a:gt(sim.aggregateState("wealth"), 100)
		a:gt(#sim.query(400), 3)
		a:ok(sim.catchUp("npc10", 100))
		a:equal(sim.despawn("npc10"), true)
		a:equal(sim.stats().entities, 9)
	end)
end)


local Scene = A:import("arkher/world/scene")
local Streaming = A:import("arkher/world/streaming")
local Terrain = A:import("arkher/terrain/terrain")
local City = A:import("arkher/procedural/city")
local WorldGen = A:import("arkher/procedural/worldgen")

t:describe("world/scene", function(s)
	local scene
	s:it("spawns hierarchies with prefabs and indexes them", function(a)
		scene = Scene.new({ name = "test" })
		scene:definePrefab("tree", { props = { kind = "oak", scale = 1 } })
		scene:spawn("forest", { position = v3(0, 0, 0), tags = { "group" } })
		for i = 1, 12 do
			scene:spawn("tree" .. i, { position = v3(i * 20, 0, 0), parent = "forest",
				prefab = "tree", tags = { "vegetation" }, radius = 5 })
		end
		a:equal(scene:report().objects, 13)
		a:equal(#scene:queryTag("vegetation"), 12)
		a:equal(scene.objects.tree3.props.kind, "oak")
		a:gte(#scene:queryRadius(v3(40, 0, 0), 45), 3)
	end)
	s:it("moves hierarchies and keeps the spatial index correct", function(a)
		scene:move("forest", v3(1000, 0, 0))
		a:equal(scene.graph.worldPosition("tree1").x, 1020)
		a:equal(#scene:queryRadius(v3(0, 0, 0), 100), 0)
		a:gte(#scene:queryRadius(v3(1020, 0, 0), 60), 3)
	end)
	s:it("handles layers, LOD bands and raycasts", function(a)
		scene:addLayer("props")
		scene:spawn("crate", { position = v3(1000, 0, 40), layer = "props", radius = 3 })
		a:equal(scene:setLayerVisible("props", false), 1)
		a:equal(#scene:visibleSet(v3(1000, 0, 20), 80), #scene:queryRadius(v3(1000, 0, 20), 80) - 1)
		a:gt(scene:updateLOD(v3(1000, 0, 0)), 0)
		local hist = scene:lodHistogram()
		a:ok(hist[0] ~= nil)
		local hit = scene:raycast(v3(1000, 0, -500), v3(0, 0, 1), 4000)
		a:ok(hit ~= nil)
	end)
	s:it("destroys subtrees and round-trips through save/load", function(a)
		local blob = scene:save()
		local count = scene:report().objects
		a:equal(scene:destroy("forest"), 13)
		a:equal(scene:report().objects, count - 13)
		local restored = Scene.new({})
		a:ok(restored:load(blob))
		a:equal(restored:report().objects, count)
		a:equal(restored.graph.worldPosition("tree1").x, 1020)
	end)
end)

t:describe("world/streaming", function(s)
	s:it("loads around a viewer within budget and unloads behind it", function(a)
		local st = Streaming.new({ chunkSize = 100, radius = 300, maxPerTick = 4,
			memoryBudgetMB = 64, costPerChunkMB = 1 })
		st:addViewer("p1", v3(0, 0, 0), v3(0, 0, 0))
		local loaded = st:tick(1)
		a:equal(#loaded, 4, "per-frame budget must be respected")
		for _ = 1, 20 do st:tick(1) end
		a:gt(st.chunker.loaded, 10)
		a:lte(st.chunker.loaded, st:capacity())
		local before = st.chunker.loaded
		st:updateViewer("p1", v3(5000, 0, 5000))
		local _, unloaded = st:tick(1)
		a:gt(#unloaded, 0)
		a:lt(st.chunker.loaded, before)
		a:gte(st:updateLOD(), 0)
		a:gte(st:pressure(), 0)
		a:ok(st:report().chunks ~= nil)
	end)
	s:it("pins chunks and respects the memory capacity", function(a)
		local st = Streaming.new({ chunkSize = 100, radius = 400, maxPerTick = 50,
			memoryBudgetMB = 10, costPerChunkMB = 1 })
		st:addViewer("p1", v3(0, 0, 0))
		st:tick(1)
		a:lte(st.chunker.loaded, 10)
		local key = st.chunker.loadedKeys()[1]
		st:pin(key, true)
		st:updateViewer("p1", v3(9000, 0, 9000))
		st:tick(1)
		a:equal(st.chunker.state(key), "loaded", "pinned chunks are never evicted")
	end)
end)

t:describe("terrain/framework", function(s)
	local terrain
	s:it("generates tiled terrain and samples it", function(a)
		terrain = Terrain.new({ tileResolution = 17, cellSize = 8, seed = 2026, waterLevel = 0 })
		local Spatial2 = A:import("arkher/kernel/spatial")
		local generated = terrain:generateRegion(Spatial2.aabb(v3(0, 0, 0), v3(500, 0, 500)))
		a:gte(generated, 9)
		local h = terrain:heightAt(200, 200)
		a:isType(h, "number")
		a:near(terrain:normalAt(200, 200):length(), 1, 0.001)
		a:gte(terrain:slopeAt(200, 200), 0)
		a:isType(terrain:biomeAt(200, 200), "string")
		a:equal(terrain:project(v3(200, 999, 200)).y, h)
	end)
	s:it("sculpts across tile boundaries", function(a)
		local border = v3(terrain.tileSize, 0, terrain.tileSize)
		local before = terrain:heightAt(border.x, border.z)
		local touched = terrain:sculpt("raise", border, 40, 25)
		a:gt(touched, 20)
		a:gt(terrain:heightAt(border.x, border.z), before)
		local flatTarget = 10
		terrain:flatten(border, 30, 1, flatTarget)
		a:near(terrain:heightAt(border.x, border.z), flatTarget, 2)
		a:gt(#terrain:dirtyTiles(), 1, "a cross-border sculpt must dirty several tiles")
	end)
	s:it("paints materials and falls back to procedural rules", function(a)
		terrain:paintMaterial(v3(100, 0, 100), 30, "snow", 1)
		local mat = terrain:materialAt(100, 100)
		a:equal(mat, "snow")
		local natural = terrain:materialAt(400, 400)
		a:isType(natural, "string")
	end)
	s:it("erodes, traces rivers and carves paths", function(a)
		local moved = terrain:erode(1, { talus = 1.2, rate = 0.5, hydraulic = true, droplets = 16 })
		a:gt(moved, 0)
		local river = terrain:traceRiver(v3(250, 0, 250), 60)
		a:gte(#river, 1)
		local carved = terrain:carvePath({ v3(50, 0, 50), v3(250, 0, 50) }, 20, 2)
		a:gt(carved, 0)
	end)
	s:it("builds LOD meshes and round-trips through save/load", function(a)
		local key = terrain:tileKeys()[1]
		local mesh = terrain:buildMesh(key)
		a:equal(mesh.stats().vertices, 17 * 17)
		a:equal(mesh.stats().triangles, 16 * 16 * 2)
		terrain:setLOD(key, 1)
		local lodMesh = terrain:buildMesh(key)
		a:equal(lodMesh.stats().vertices, 9 * 9)
		a:gt(terrain:updateLOD(v3(0, 0, 0)), 0)
		local blob = terrain:save()
		local restored = Terrain.new({})
		a:ok(restored:load(blob))
		a:equal(restored:report().tiles, terrain:report().tiles)
		a:near(restored:heightAt(200, 200), terrain:heightAt(200, 200), 0.001)
	end)
end)

t:describe("procedural/city", function(s)
	s:it("generates roads, blocks, lots and buildings deterministically", function(a)
		local Spatial2 = A:import("arkher/kernel/spatial")
		local bounds = Spatial2.aabb(v3(0, 0, 0), v3(900, 0, 900))
		local city = City.new({ seed = 777, blockSize = 120 })
		local report = city:generate(bounds)
		a:gt(report.roads.nodes, 40)
		a:gt(report.blocks, 20)
		a:gt(report.lots, report.blocks)
		a:gt(report.buildings, 20)
		a:gt(report.population, 100)
		a:gt(report.roadLength, 1000)
		local again = City.new({ seed = 777, blockSize = 120 })
		local report2 = again:generate(bounds)
		a:equal(report2.buildings, report.buildings)
		a:equal(report2.population, report.population)
	end)
	s:it("zones by distance to the centre and builds a real mesh", function(a)
		local Spatial2 = A:import("arkher/kernel/spatial")
		local city = City.new({ seed = 42, blockSize = 110 })
		city:generate(Spatial2.aabb(v3(0, 0, 0), v3(1200, 0, 1200)))
		local zones = city:zoneHistogram()
		a:ok(zones.downtown ~= nil or zones.commercial ~= nil)
		local tallest = city:tallest()
		a:gt(tallest.height, 8)
		local mesh, built = city:buildMesh(25)
		a:equal(built, 25)
		a:gt(mesh.stats().triangles, 200)
		a:ok(mesh.bounds() ~= nil)
	end)
end)

t:describe("procedural/worldgen", function(s)
	local gen, report
	s:it("runs the whole pipeline from a single seed", function(a)
		gen = WorldGen.new({ seed = 31337, size = 1200, cellSize = 16, tileResolution = 9 })
		report = gen:generate({ cities = 2, rivers = 2, cityExtent = 360,
			vegetationDensity = 0.6, populationPerCity = 20, biomeResolution = 6 })
		a:equal(#report.steps, 8)
		a:gte(report.cities, 1)
		a:gt(report.buildings, 10)
		a:gt(report.vegetation, 5)
		a:gt(report.agents, 10)
		a:gt(report.terrain.tiles, 10)
		a:isType(report.checksum, "number")
	end)
	s:it("is deterministic: same seed, same world", function(a)
		local twin = WorldGen.new({ seed = 31337, size = 1200, cellSize = 16, tileResolution = 9 })
		local twinReport = twin:generate({ cities = 2, rivers = 2, cityExtent = 360,
			vegetationDensity = 0.6, populationPerCity = 20, biomeResolution = 6 })
		a:equal(twinReport.checksum, report.checksum)
		a:equal(twinReport.buildings, report.buildings)
		a:equal(twinReport.vegetation, report.vegetation)
	end)
	s:it("keeps simulating the world when nobody is watching", function(a)
		local before = gen.simulation.aggregateState("wealth")
		local result = gen:simulate(2, v3(0, 0, 0))
		a:gt(result.processed, 0)
		a:gt(result.wealth, before)
		a:gt(result.stats.entities, 10)
	end)
end)

local r = t:run()
if not t:report() then error("ARKHER round 3 tests failed") end
