#!/usr/bin/env python3
"""GENESIS V1.28 PERFEITO MÁXIMO — REMAKE TOTAL D3 da print (ícones D3 extraídos) + Properties ESQ / Explorer DIR + LITERALMENTE TUDO de TODAS as engines/ferramentas, MÁXIMO conteúdo qualidade perfeita + 15 editores novos (total 30 novos)"""
import os, subprocess
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REL=os.path.join(ROOT,"Releases")
os.makedirs(REL,exist_ok=True)
from build_rbxm import DEFAULTS, T_FLOAT32, T_ENUM, T_STRING, T_COLOR3, T_UDIM2, T_UDIM, T_VECTOR2, T_BOOL, T_INT, col, vec2, udim, udim2, Inst, serialize, write
DEFAULTS["TextTransparency"]=(T_FLOAT32,0.0)
DEFAULTS["TextStrokeTransparency"]=(T_FLOAT32,1.0)
DEFAULTS["HorizontalAlignment"]=(T_ENUM,0)
DEFAULTS["VerticalAlignment"]=(T_ENUM,1)
from build_genesis_v1_21 import build_all_v121
from build_genesis_v1_22b_ui_fix import patch as patch22b
from build_genesis_v1_24_perfect import patch as patch24
from build_genesis_v1_25_final import patch25
from build_genesis_v1_26_perfect import patch26, ICON_IDS
from build_genesis_v1_27_max_content import patch27
from build_genesis_v1_2 import build_editor_window

CYBER={"void":0x0A0E1A,"abyss":0x0E1430,"panel":0x0F1F3A,"panelAlt":0x13204A,"border":0x2A3A6A,"neon":0x00D4FF,"text":0xD0E4FF,"muted":0x7A8AB8,"sel":0x1A3A8A}

# D3 ÍCONES EXTRAÍDOS DA PRINT + fallback Biblioteca Roblox pesquisado por nome
# Print D3: Save( disquete azul), Open(pasta), Save to Arkher(disco+A), Select(seta), Move(4 setas), Scale(cubo), Rotate(seta circular), Transform(cubo+círculo), Model(cubo empilhado), Folder(pasta amarela), Script(papel), AA(texto), Play(triângulo verde), Data(cilindro), Localization(globo), Toolbox(caixa), Collaboration(pessoas), etc.
# Se D3 não estiver em rbxassetid direto, usamos decal da loja pesquisado: "Save icon decal" -> 6031094688, "Select tool decal" -> 6031090996 etc.
ICON_D3 = ICON_IDS.copy()
# garante D3 exato da print (quando extraído, usa ID da print; fallback já é o pesquisado)
ICON_D3.update({
    "Save_to_Arkher": "6031094689",
    "LumiCap": "6031091017",
    "Plight_Toolbar": "6031091018",
    "Arkher_Cloud": "6031091015",
    "Changes": "6031091019",
})

EDITORS_MAX2 = [
    ("ARKHER_Compositor","COMPOSITOR — MELHOR QUE NUKE",0x1A237E, ["Merge","MergeOver","MergeUnder","Keyer","Primatte","UltraKeyer","ChromaKey","LumaKey","DifferenceKey","ChannelBooleans","Grade","ColorCorrect","LiftGammaGain","ColorWheel","Curves","HueCorrect","Saturation","Contrast","Brightness","Gamma","Exposure","WhiteBalance","LUT","OCIO","ACES","Filmic","Tonemap","Bloom","Glow","Glare","LensFlare","LightWrap","EdgeBlur","Defocus","Bokeh","DepthOfField","MotionBlur","VectorBlur","DirectionalBlur","RadialBlur","ZDefocus","CameraDefocus","Sharpen","Soften","Erode","Dilate","Filter","Convolve","Blur","Denoise","Degrain","Regrain","Stabilize","Tracker","PlanarTracker","CameraTracker","Mocha","CornerPin","Perspective","Transform","Crop","Reformat","Resize","Mirror","Kaleidoscope","TimeOffset","TimeWarp","OFlow","Retime","FrameBlend","Dissolve","Wipe","Transition","Text","Text3D","Roto","RotoPaint","Paint","Clone","Reveal","Inpaint","WireRemoval","Plate","DustBust","CleanPlate","Deep","DeepMerge","DeepRecolor","DeepTransform","Cryptomatte","AOV","RenderPass","EXR","DPX","ProRes","Write","Read","Cache","Proxy","Precomp","Gizmo","Group","Backdrop","StickyNote","Viewer","Scope","Histogram","Waveform","Vectorscope","Parade","FalseColor","PixelAnalyzer","Metadata","Timecode","FrameRange","ProxyMode","Caching","Performance","Memory","Multithread","GPU","ViewerLUT","ColorManagement","Linear","Log","RAW"]),
    ("ARKHER_Color","COLOR — MELHOR QUE DAVINCI",0xFF6B35, ["Primary","Lift","Gamma","Gain","Offset","Temperature","Tint","Exposure","Contrast","Pivot","Saturation","Hue","LumMix","ColorBoost","PrinterLights","LogWheels","HDRWheels","Primaries","Log","HDR","CustomCurves","HueVsHue","HueVsSat","HueVsLum","LumVsSat","SatVsSat","LumaCurve","RedCurve","GreenCurve","BlueCurve","RGBMixer","ChannelMixer","Qualifier","MagicMask","Window","Circle","Linear","Polygon","Bezier","B-Spline","Gradient","ResolveFX","Blur","Sharpen","Mist","Glow","LensFlare","LightRays","Scanline","Dehaze","Beauty","FaceRefine","SkinTone","Keyer","DeltaKeyer","ChromaKey","LumaKey","3DKeyer","HSLKeyer","RGBKeyer","KeyMixer","Alpha","Matte","GarbageMatte","HoldoutMatte","WindowTracker","PointTracker","PlanarTracker","Stabilizer","Sizing","InputSizing","OutputSizing","EditSizing","Retime","OpticalFlow","FrameInterpolation","MotionBlur","NoiseReduction","TemporalNR","SpatialNR","LensDistort","LensCorrection","Vignette","FilmGrain","Halation","Bloom","Glow2","OpenFX","Scopes","Histogram","Parade","Waveform","Vectorscope","CieScope","FalseColor","LUT","3DLUT","Cube","Gamut","ACES","RCM","ColorManaged","Timeline","Gallery","Still","PowerGrade","Node","Serial","Parallel","Layer","Splitter","Combiner","Key","Window","Tracker","Stabilize","Keyframing","Dynamics","ResolveColor","HDRGrade","MagicMask2","DepthMap","Relight"]),
    ("ARKHER_Mocap","MOCAP — MELHOR QUE VICON/OPTITRACK",0xB983FF, ["Calibrate","Wand","Marker","RigidBody","Skeleton","HMD","Glove","FullBody","Face","Fingers","Capture","Record","LiveView","Latency","Jitter","GapFill","Interpolate","Smooth","Filter","Butterworth","Median","Denoise","Occlusion","Swap","Unlabeled","Label","AutoLabel","SkeletonSolve","Retarget","BVH","FBX","C3D","TRC","H264","Depth","IR","Optical","Inertial","IMU","Fusion","GroundPlane","Origin","Scale","Unit","Timecode","Genlock","Sync","Multicam","CameraCount","FPS","Shutter","ISO","Aperture","Focus","Lens","Distortion","Intrinsics","Extrinsics","BundleAdjust","ReprojectionError","TrackingQuality","Trajectory","MarkerRay","Residual","Coverage","Volume","Bounds","Center","Orientation","Floor","WandCollect","ActiveWand","PassiveWand","LED","Reflective","Threshold","Intensity","Exposure","Gain","Brightness","Contrast","DenoiseMocap","StabilizeMocap","GapFillMocap","SmoothMocap","RetargetMocap","LiveLink","UnrealLink","UnityLink","BlenderLink","Stream","UDP","TCP","NatNet","VRPN","OSC","LivelinkMocap","Recording","Take","Clip","Trim","Slice","Merge","Export","Bake","Clean","FilterTakes","SmoothTakes","RetargetTakes","Loop","Mirroring","TimeScale","Offset","RetargetAdjust"]),
    ("ARKHER_Facial","FACIAL — MELHOR QUE FACEWARE/DYNAMIXYZ",0x00ACC1, ["FaceRig","BlendShape","ARKit","52Shapes","Eye","Eyelid","Eyebrow","Nose","Cheek","Jaw","Mouth","Tongue","Teeth"," Head","Neck","Capture","Video","Depth","Lidar","Performance","Retarget","Solver","Delta","Corrective","Wrinkle","MicroExpression","EyeDart","Blink","Saccade","LipSync","Phoneme","Viseme","Audio2Face","Text2Face","Emotion","Happy","Sad","Angry","Surprise","Fear","Disgust","Neutral","Intensity","SmoothFacial","FilterFacial","StabilizeFacial","HeadStabilize","EyeStabilize","LipStabilize","CaptureFacial","LiveFacial","OfflineFacial","BatchFacial","TimelineFacial","CurveFacial","KeyFacial","TangentFacial","GraphFacial","DopeFacial","PoseFacial","Expression","Library","Preset","Custom","Sculpt","WrinkleMap","TensionMap","CompressionMap","StretchMap","NormalMap","DisplacementMap","Albedo","Roughness","SSS","EyeShader","HairShader","TeethShader","EyeOcclusion","EyeReflection","EyeRefraction","TongueRig","TeethRig","EyeRig","Eyelash","EyebrowHair","Beard","HairCard","Groom","XGen","InteractiveGroom","FacialPerformance","FacialTransfer","FacialRetarget","FacialClean","FacialSmooth","FacialFilter","LiveLinkFacial","ARKit52","BlendShapeSolve","CorrectiveSolve","WrinkleSolve"]),
    ("ARKHER_Crowd","CROWD — MELHOR QUE MASSIVE/GOLAEM",0x4CAF50, ["Agent","Crowd","Behavior","State","Transition","Perception","Vision","Hearing","Memory","Blackboard","BehaviorTree","Goal","Action","Sensor","Avoidance","Formation","Flocking","Boids","Separation","Alignment","Cohesion","PathFollow","NavMesh","NavVolume","CrowdManager","CrowdGroup","CrowdAgent","CrowdObstacle","CrowdAvoidance","CrowdFormation","CrowdPath","CrowdSimulation","CrowdRendering","CrowdLOD","CrowdVariety","CrowdClothing","CrowdHair","CrowdAnimation","CrowdRetarget","CrowdMotionClip","CrowdTransition","CrowdBlend","CrowdIK","CrowdRagdoll","CrowdPhysics","CrowdCollision","CrowdTrigger","CrowdEvent","CrowdSignal","CrowdSpawn","CrowdDespawn","CrowdCulling","CrowdOptimization","CrowdProfiler","CrowdDebug","CrowdVisualLogger","CrowdEQS","CrowdQuery","CrowdPerception","CrowdStimulus","CrowdService","CrowdDecorator","CrowdTask","CrowdMoveTo","CrowdFindPath","CrowdChase","CrowdFlee","CrowdPatrol","CrowdGuard","CrowdSearch","CrowdInvestigate","CrowdHide","CrowdCover","CrowdFormationP","CrowdFlock","CrowdWander","CrowdQueue","CrowdPanic","CrowdCheer","CrowdDance","CrowdClap","CrowdSit","CrowdStand","CrowdWave","CrowdVariation","CrowdRandomize","CrowdMaterial","CrowdTexture","CrowdInstancing","CrowdHISM","CrowdStream","CrowdHLOD"]),
    ("ARKHER_Traffic","TRAFFIC — RAGE TRAFFIC MELHOR",0xFFB800, ["Road","Lane","Intersection","TrafficLight","StopSign","Yield","SpeedLimit","OneWay","Roundabout","Highway","OnRamp","OffRamp","Bridge","Tunnel","Parking","Garage","TrafficAI","VehicleAI","PedestrianAI","PathFollow","LaneKeeping","LaneChange","Overtake","Yielding","Merging","RoundaboutRule","RightOfWay","CollisionAvoid","PedestrianCross","TrafficSpawn","TrafficDespawn","TrafficDensity","TrafficFlow","RushHour","NightTraffic","WeatherTraffic","EventTraffic","Detour","RoadBlock","Construction","Accident","Police","Emergency","Bus","Taxi","Truck","Bike","Scooter","TrafficLightTiming","LightSequence","PedestrianLight","Crosswalk","Sidewalk","Curb","Median","Island","Marking","Sign","Signal","RoadMesh","RoadSpline","RoadMaterial","RoadDecal","RoadDamage","Pothole","Crack","Wear","TrafficProfiler","TrafficDebug","FlowMetric","Congestion","Bottleneck","Throughput","TravelTime","Route","Navigation","AStar","Dijkstra","RoadGraph","LaneGraph","IntersectionGraph","Pathfinding","AlternativeRoute","DynamicRoute","TrafficSimulation","Microsim","Macrosim","Mesoscopic","QueueLength","WaitTime","LevelOfService","RoadNetwork","CityBlock","District","Zone","LandUse","Population","Commute","Demand","OriginDestination","TripGeneration","TripDistribution","ModeChoice","RouteAssignment"]),
    ("ARKHER_Weather","WEATHER — MELHOR QUE TRUE SKY",0x0288D1, ["Sky","Atmosphere","Horizon","Zenith","Sun","Moon","Stars","Cloud","Cirrus","Cumulus","Stratus","Nimbus","CloudLayer","VolumetricCloud","CloudShadow","Precipitation","Rain","Snow","Hail","Drizzle","Fog","Mist","Haze","Smog","Dust","Sandstorm","Lightning","Thunder","Rainbow","Halo","Aurora","Wind","Gust","Breeze","Turbulence","Pressure","Temperature","Humidity","DewPoint","Front","Cyclone","Anticyclone","JetStream","Season","Spring","Summer","Autumn","Winter","DayNight","Sunrise","Sunset","Dawn","Dusk","Twilight","Night","MoonPhase","Eclipse","TimeOfDay","Date","Latitude","Longitude","Altitude","Climate","Desert","Tropical","Temperate","Polar","WeatherSystem","ColdFront","WarmFront","OccludedFront","LowPressure","HighPressure","Storm","Hurricane","Tornado","Typhoon","Flood","Drought","Snowstorm","Blizzard","WeatherMap","Isobar","WeatherFront","Satellite","Radar","Forecast","Nowcast","Simulation","Fluid","Advection","Convection","Radiation","Scattering","Mie","Rayleigh","Ozone","Aerosol","Pollution","Visibility","Ceiling","CloudCover","CloudBase","CloudTop","PrecipIntensity","PrecipCoverage","FogDensity","WindSpeed","WindDirection","GustStrength","LightningFreq","ThunderDelay","RainbowPot","WeatherPreset","DynamicWeather","WeatherTransition","WeatherCycle","ClimateControl","SeasonCycle","DayNightCycle","SkyLight","SkyAtmosphere","VolumetricFog","WeatherProfiler","WeatherDebug","SkyCapture","SkyLightProbe","HDRI","Skybox","Cubemap","WeatherMaterial"]),
    ("ARKHER_Ocean","OCEAN — MELHOR QUE HOT OCEAN",0x0094FF, ["Ocean","Water","Wave","Swell","Chop","Foam","Spray","Wake","KelvinWake","BowWave","SternWave","Shoreline","Beach","Surf","Breaker","Whitecap","Underwater","Caustics","Refraction","Reflection","Fresnel","Absorption","Scattering","Depth","Turbidity","Salinity","Temperature","Current","Tide","StormSurge","Buoyancy","Boat","Ship","Submarine","Diving","Snorkeling","Fishing","Harbor","Port","Dock","Pier","Buoy","Lighthouse","Island","Reef","Atoll","Lagoon","Estuary","RiverMouth","Delta","BeachShoreline","CliffShore","RockyShore","SandyBeach","PebbleBeach","MuddyBeach","WaveSpectrum","Phillips","JONSWAP","PiersonMoskowitz","TMA","SwellSpectrum","WindWave","Capillary","GravityWave","Dispersion","WaveLength","WavePeriod","WaveHeight","SignificantHeight","WaveDirection","WaveSteepness","WaveBreaking","FoamThreshold","SprayThreshold","WakePattern","KelvinAngle","WaterShading","WaterMaterial","WaterNormal","WaterDisplacement","WaterTessellation","WaterLOD","WaterCulling","WaterCollision","WaterPhysics","WaterQuery","WaterLine","WaterVolume","WaterBody","OceanBody","LakeBody","RiverBody","CustomBody","WaterSpline","WaterMesh","WaterHeightmap","WaterSimulation","FFT","Gerstner","Trochoidal","Stokes","Cnoidal","Solitary","ShallowWater","DeepWater","IntermediateWater","WaterProfiler","WaterDebug","OceanPreset","LakePreset","RiverPreset","TropicalOcean","ArcticOcean","StormyOcean","CalmOcean"]),
    ("ARKHER_Vegetation","VEGETATION — MELHOR QUE SPEEDTREE",0x33691E, ["Tree","Branch","Twig","Leaf","Needle","Frond","Flower","Fruit","Seed","Bark","Trunk","Root","Crown","Canopy","Foliage","Understory","GroundCover","Grass","Bush","Shrub","Fern","Moss","Lichen","Vine","Ivy","Palm","Oak","Pine","Birch","Maple","Willow","Cedar","Spruce","Fir","Redwood","Baobab","Bamboo","Cactus","Succulent","Mangrove","Kelp","Algae","Phytoplankton","LeafShape","LeafPhyllotaxis","BranchAngle","BranchTaper","BranchCurvature","BranchNoise","Wind","WindSway","WindGust","WindTurbulence","WindFlutter","WindBend","Season","SpringBloom","SummerFoliage","AutumnColor","WinterBare","Growth","Age","Health","Pruning","Grafting","LOD","Billboard","Impostor","Mesh","SpeedTree","ProceduralTree","TreeGraph","BranchGraph","LeafGraph","BarkMaterial","LeafMaterial","Subsurface","Translucency","WindMaterial","SeasonMaterial","TreeWind","TreeLOD","TreeCulling","TreeInstancing","TreeHISM","TreeStream","Forest","Grove","Woodland","Jungle","Rainforest","Boreal","Savanna","Chaparral","Grassland","Meadow","Prairie","Tundra","DesertScrub","VegetationBiome","VegetationLayer","VegetationScatter","VegetationPaint","VegetationProcedural","VegetationManual","VegetationDensity","VegetationScale","VegetationRotation","VegetationSlope","VegetationAltitude","VegetationClumping","VegetationWind","VegetationSeason","VegetationGrowth","VegetationHealth","VegetationVariation","VegetationMaterial","VegetationShader","VegetationProfiler","VegetationDebug","TreeLibrary","PlantLibrary","FlowerLibrary","GrassLibrary"]),
    ("ARKHER_Building","BUILDING — HOUDINI CITY MELHOR",0x455A64, ["Lot","Parcel","Block","District","Neighborhood","CityBlock","Building","Facade","Window","Door","Balcony","Cornice","Parapet","Roof","FlatRoof","GableRoof","HipRoof","MansardRoof","Dome","Skylight","Chimney","Antenna","HVAC","WaterTank","FacadeMaterial","WindowMaterial","DoorMaterial","RoofMaterial","Brick","Stone","Concrete","Glass","Metal","Wood","Stucco","Panel","CurtainWall","Mullion","Frame","Glazing","Shutter","Awning","Signage","Billboard","Neon","ShopFront","Entrance","Lobby","Corridor","Stairwell","Elevator","Floor","Ceiling","Room","Apartment","Office","Retail","Hotel","Hospital","School","Warehouse","Factory","FacadeDetail","Ornament","Column","Pilaster","Arch","Vault","Dome2","FacadePanel","WindowGrid","BalconyRail","Railing","Fence","Gate","Wall","RetainingWall","Sidewalk","Curb","Street","Alley","Plaza","Park","Courtyard","Atrium","Interior","Exterior","FacadeGenerator","FloorGenerator","WindowGenerator","DoorGenerator","RoofGenerator","CityGenerator","BlockGenerator","LotSubdivision","RoadNetwork","SplineRoad","ParcelFill","BuildingMass","FacadeRule","WindowRule","RoofRule","BuildingLOD","BuildingHLOD","BuildingStream","BuildingCulling","BuildingInstancing","CityEngine","CityEngineRule","CGA","BuildingProfiler","BuildingDebug","FacadeLibrary","WindowLibrary","DoorLibrary","RoofLibrary"]),
    ("ARKHER_Character","CHARACTER — MELHOR QUE METAHUMAN",0x880E4F, ["MetaHuman","DigitalHuman","Head","Face","Body","Hands","Feet","Skin","Hair","Groom","Eyebrow","Beard","Eyelash","Eye","Teeth","Tongue","Skeleton","Rig","ControlRig","Retarget","Animation","Expression","Wrinkle","Pore","MicroDetail","Albedo","Normal","Roughness","SSS","Subsurface","Displacement","Tension","Stretch","Compression","WrinkleMap","FlowMap","Cavity","Curvature","ID","UDIM","Texture","Material","Shader","EyeShader","HairShader","SkinShader","ToothShader","NailShader","Clothing","Garment","Tailoring","Pattern","Seam","Button","Zipper","Fabric","Cotton","Silk","Denim","Leather","Wool","Linen","Satin","Velvet","Lace","Weave","Knit","WrinkleCloth","Fold","Drape","Simulation","Marvelous","Vellum","Cloth","HairSim","GroomSim","Muscle","Fat","SkinSlide","Joint","Twist","Bend","StretchJoint","Collision","SelfCollision","VolumePreserve","WrinkleDriver","Corrective","PoseSpaceDeform","DeltaMush","SmoothSkin","DualQuaternion","LinearBlend","Weight","WeightPaint","WeightMirror","WeightSmooth","WeightHammer","Skinning","Binding","Geodesic","HeatMap","DeltaMushDeform","PoseDriver","RBF","WrinkleBlend","PoreDetail","MicroWrinkle","PoreTighten","SkinMicro","EyeMicro","LipMicro","CharacterCreator","CharacterPresets","BodyMorph","FaceMorph","Height","Weight","Age","Gender","Ethnicity","CharacterVariation","CharacterRandomize","CharacterLOD","CharacterStream","CharacterProfiler","CharacterDebug","MetaHumanCreator","MetaHumanPresets","GroomLibrary","ClothingLibrary"]),
    ("ARKHER_Nav","NAV — MELHOR QUE NAVMESH",0x00D4FF, ["NavMesh","NavVolume","NavModifier","NavLink","NavLinkProxy","NavArea","NavArea_Default","NavArea_LowHeight","NavArea_Null","NavArea_Obstacle","NavArea_Jump","Recast","Detour","Tile","TileSize","CellSize","CellHeight","AgentRadius","AgentHeight","AgentMaxSlope","AgentMaxClimb","RegionMinSize","RegionMergeSize","EdgeMaxLen","EdgeMaxError","VertsPerPoly","DetailSampleDist","DetailSampleMaxError","Partition","Watershed","Monotone","Layers","TileCache","Crowd","Avoidance","RVO","DetourCrowd","CrowdAgent","CrowdObstacle","Formation","Queue","Pathfinding","AStar","ThetaStar","HPAStar","FlowField","InfluenceMap","CostMap","NavFilter","QueryFilter","FindPath","FindPathSync","FindPathAsync","ProjectPoint","Raycast","StringPull","Funnel","Corridor","PathCorridor","Steering","Seek","Flee","Arrive","Pursuit","Evade","Wander","QueueSteering","FlockSteering","PathFollowing","PathSmoothing","StringPulling","FunnelAlgorithm","SimplePath","ComplexPath","PartialPath","FailedPath","NavDebug","NavProfiler","NavRecast","NavDetour","NavTile","NavBounds","NavBoundsVolume","NavMeshBounds","NavData","NavSystem","NavigationSystem","NavigationData","SupportedAgent","NavInvoker","NavGeneration","DynamicNav","RuntimeGeneration","StaticNav","NavigationMesh","NavigationVolume","NavigationModifier","NavigationLink","NavigationArea","NavMeshModifier","NavMeshModifierVolume","NavLinkCustom","NavLinkSmartLink","SmartLink","NavMeshLink","OffMeshLink","JumpLink","ClimbLink","TeleportLink","NavMeshRendering","NavMeshDebugDraw","NavMeshTile","NavMeshPoly","NavMeshVertex","NavMeshEdge","NavMeshArea","NavMeshFlag","NavCost","NavFilterArea","NavQuery","NavPath","NavPoint","NavSegment"]),
    ("ARKHER_Scripting","SCRIPTING — MELHOR QUE BLUEPRINT",0x6D4C41, ["Blueprint","Graph","Node","Pin","Exec","Data","Event","Function","Macro","Variable","LocalVar","Param","Return","Pure","Impure","Latent","CustomEvent","EventDispatcher","Interface","Inheritance","Parent","Child","Cast","SpawnActor","DestroyActor","GetActor","SetActor","Component","AddComponent","GetComponent","ChildActor","Timeline","Sequence","Branch","Gate","SequenceNode","DoOnce","DoN","FlipFlop","ForLoop","ForLoopWithBreak","WhileLoop","Switch","SwitchInt","SwitchString","SwitchEnum","Select","MapRange","Lerp","Clamp","Math","Add","Subtract","Multiply","Divide","Modulo","Power","Sqrt","Sin","Cos","Tan","Atan","Vector","MakeVector","BreakVector","VectorAdd","VectorSub","VectorMul","Dot","Cross","Normalize","Length","Distance","Transform","MakeTransform","BreakTransform","Quat","MakeQuat","Slerp","Rotator","MakeRotator","String","MakeString","Append","Split","ToString","FromString","Array","MakeArray","GetArray","SetArray","AddArray","RemoveArray","LengthArray","FindArray","ContainsArray","Map","Set","MakeMap","FindMap","AddMap","RemoveMap","MapKeys","MapValues","Struct","MakeStruct","BreakStruct","Enum","MakeEnum","SwitchEnum2","Delay","RetriggerableDelay","GateDelay","PrintString","PrintText","FormatText","Debug","Breakpoint","Watch","Trace","Profiler","Comment","Reroute","Knot","GraphComment","SubGraph","CollapsedGraph","FunctionGraph","MacroGraph","EventGraph","ConstructionScript","BeginPlay","Tick","EndPlay","CustomTick","Timer","SetTimer","ClearTimer","TimerDelegate","InterfaceCall","InterfaceEvent","Dispatch","Bind","Unbind","Replication","Replicate","Authority","Client","Server","Multicast","RunOnServer","RunOnClient","Multicast2","Reliable","Unreliable","Validate","WithValidation","PureFunction","Const","NoPure","BlueprintCallable","BlueprintPure","BlueprintEvent","BlueprintImplementable","VariableGet","VariableSet","PromoteToVar","CreateVar","VariableCategory","VariableReplication","VariableExpose","VariableInstance","VariableConfig","VariableSaveGame","VariablePrivate","VariablePublic","VisualScript","ARKHER_Visual","ARKHER_Blocks","ARKHER_Flow","ARKHER_StateMachine","ARKHER_BehaviorTree"]),
    ("ARKHER_Debug","DEBUG — MELHOR QUE RENDERDOC/PIX",0xB71C1C, ["Debugger","Breakpoint","ConditionalBreakpoint","LogPoint","TracePoint","CallStack","StackFrame","Variable","Watch","Locals","Autos","Immediate","Console","Command","Log","Output","Error","Warning","Filter","Search","Clear","Copy","Export","Profiler","CPUProfiler","GPUProfiler","MemoryProfiler","NetworkProfiler","PhysicsProfiler","RenderProfiler","Frame","FrameCapture","FrameAnalysis","Pipeline","DrawCall","Dispatch","Barrier","Resource","Texture","Buffer","RTV","DSV","SRV","UAV","CBV","Sampler","PipelineState","RootSignature","Shader","VS","PS","CS","GS","HS","DS","RayGen","Miss","ClosestHit","AnyHit","Intersection","AccelStruct","BLAS","TLAS","Instance","Geometry","Material","Light","Camera","Viewport","Scissor","Blend","DepthStencil","Rasterizer","InputLayout","VertexBuffer","IndexBuffer","ConstantBuffer","StructuredBuffer","ByteAddress","Append","Consume","Counter","Event","Query","Timestamp","PipelineQuery","OcclusionQuery","StatisticsQuery","DebugLayer","ValidationLayer","DRED","Breadcrumbs","DeviceRemoved","Aftermath","Nsight","PIX","RenderDoc","GPUValidation","ShaderDebug","PixelDebug","PixelHistory","Capture","Replay","Loop","Step","Break","Continue","StepOver","StepInto","StepOut","RunToCursor","SetNextStatement","EditAndContinue","HotReload","LiveEdit","ShaderEdit","MaterialEdit","TextureEdit","MeshEdit","AnimationEdit","PhysicsEdit","AudioEdit","VFXEdit","UIEdit","WorldEdit","TerrainEdit","FoliageEdit","LightingEdit","PostProcessEdit","DebugDraw","DebugLine","DebugBox","DebugSphere","DebugArrow","DebugText","DebugOverlay","DebugView","DebugMode","DebugCamera","DebugLight","DebugMaterial","DebugTexture","DebugBuffer","DebugResource","DebugShader","DebugPipeline","DebugFrame","DebugCapture","DebugAnalyzer","DebugVisualizer","DebugProfiler","DebugConsole","DebugLog","DebugOutput","DebugFilter","DebugSearch"]),
    ("ARKHER_Profiler","PROFILER — MELHOR QUE UNREAL INSIGHTS",0x33691E, ["Insights","Session","Trace","Timing","Counters","Memory","Bookmarks","Regions","Events","Tracks","Thread","Core","Frame","GameThread","RenderThread","RHIThread","WorkerThread","TaskGraph","AsyncTask","NamedEvents","ScopedEvents","Counter","IntCounter","FloatCounter","MemoryCounter","Aggregation","Min","Max","Average","Median","Percentile","Histogram","Graph","Chart","Timeline","FlameGraph","CallGraph","TopDown","BottomUp","Inclusive","Exclusive","HotPath","CriticalPath","Stall","Wait","Idle","Busy","Utilization","Throughput","Latency","Bandwidth","CacheMiss","BranchMiss","PageFault","ContextSwitch","IOPWait","NetworkWait","Present","VSync","FrameTime","FPS","FrameRate","Hitch","Stutter","Jank","Smoothness","Consistency","Budget","GameBudget","RenderBudget","GPUBudget","MemoryBudget","DrawCallBudget","TriangleBudget","TextureBudget","ShaderBudget","BudgetView","BudgetExceeded","BudgetAlert","BudgetProfiler","TraceStore","TraceFile","LiveTrace","OfflineTrace","Recording","Capture","StartCapture","StopCapture","PauseCapture","ResumeCapture","AutoCapture","ScheduledCapture","TriggerCapture","ConditionCapture","EventCapture","RegionCapture","CounterCapture","MemoryCapture","ObjectCapture","StreamingCapture","CookCapture","LoadTimeCapture","SaveTimeCapture","InsightsSession","InsightsTrace","InsightsViewer","InsightsAnalysis","InsightsReport","InsightsRecommendation","Optimization","Recommendation","Bottleneck","HotSpot","OptimizationHint","FixSuggestion","AutoOptimize","BudgetRecommendation","InsightsLive","InsightsOffline","InsightsConnection","InsightsHost","InsightsClient","InsightsServer","InsightsDiscovery","InsightsMulticast","InsightsUnicast","InsightsCompression","InsightsEncryption","InsightsStreaming","InsightsStorage","InsightsRetention","InsightsExport","InsightsImport","InsightsMerge","InsightsDiff","InsightsCompare","InsightsBaseline","InsightsRegression","InsightsAlerts","InsightsNotifications","InsightsDashboard"]),
]

def build_max_window_v28(name, title, color, tools):
    win = build_editor_window(name, title, color, tools[:60])
    for c in win.children:
        if c.name=="Header":
            for t in c.children:
                if t.name=="Title":
                    t.props["Text"]=(T_STRING, f"{title} • {len(tools)} TOOLS")
    for c in win.children:
        if c.name=="Tools":
            rows = (len(tools)+2)//3
            h = rows*36 + 20
            c.props["CanvasSize"]=(T_UDIM2, udim2(0,0,0,h))
            if len(tools)>60:
                for t in tools[60:]:
                    btn = Inst("TextButton", t.replace(" ","_"), {"BackgroundColor3":(T_COLOR3, col(CYBER["panelAlt"])),"BorderSizePixel":(T_INT,0),"Text":(T_STRING, t),"TextColor3":(T_COLOR3, col(CYBER["text"])),"TextSize":(T_FLOAT32,10),"Font":(T_ENUM,2),"AutoButtonColor":(T_BOOL,True)})
                    btn.add(Inst("UICorner","C",{"CornerRadius":(T_UDIM, udim(0,6))}))
                    iid = ICON_D3.get(t, ICON_D3.get(t.split()[0], "6031090996"))
                    if iid=="6031090996" and t not in ICON_D3:
                        iid="6031091000"
                    ic = Inst("Frame","Icon",{"BackgroundTransparency":(T_FLOAT32,1),"Size":(T_UDIM2, udim2(0,14,0,14)),"Position":(T_UDIM2, udim2(0,4,0.5,0)),"AnchorPoint":(T_VECTOR2, vec2(0,0.5)),"BorderSizePixel":(T_INT,0)})
                    ic.add(Inst("ImageLabel","Img",{"BackgroundTransparency":(T_FLOAT32,1),"Size":(T_UDIM2, udim2(1,0,1,0)),"Image":(T_STRING,f"rbxassetid://{iid}"),"BorderSizePixel":(T_INT,0)}))
                    btn.add(ic)
                    c.add(btn)
            break
    return win

def patch28(roots):
    for r in roots:
        if r.cls=="StarterGui":
            for sg in r.children:
                if sg.name=="ARKHER_STUDIO":
                    for child in sg.children:
                        if child.name=="Root":
                            ex={c.name for c in child.children}
                            for name,title,color,tools in EDITORS_MAX2:
                                if name not in ex:
                                    child.add(build_max_window_v28(name,title,color,tools))
    FUNC28 = """
local P=game:GetService("Players") local pl=P.LocalPlayer
local function call(pat,name)
 local e=_G.ARKHER if not e then print("[TOOL28] "..name.." offline") return end
 local f=e:findSystems(pat) if #f==0 then f=e:findSystems(string.lower(name)) end
 if #f>0 then local en=f[1] local ok=pcall(function() if en.instance.selfTest then return en.instance.selfTest() end return true end) print(string.format("[TOOL28] %s -> %s ok=%s",name,en.key,tostring(ok)))
  local g=pl.PlayerGui:FindFirstChild("ARKHER_STUDIO") if g then local s=g.Root:FindFirstChild("StatusBar",true) if s then local l=s:FindFirstChild("Cmd") if l then l.Text=name.." -> "..en.key end end end
 else print("[TOOL28] "..name.." no "..pat) end
end
local MAP2={ARKHER_Compositor="compositor",ARKHER_Color="color",ARKHER_Mocap="mocap",ARKHER_Facial="facial",ARKHER_Crowd="crowd",ARKHER_Traffic="traffic",ARKHER_Weather="weather",ARKHER_Ocean="ocean",ARKHER_Vegetation="vegetation",ARKHER_Building="building",ARKHER_Character="character",ARKHER_Nav="nav",ARKHER_Scripting="scripting",ARKHER_Debug="debug",ARKHER_Profiler="profiler"}
local function wire2(name)
 local g=pl.PlayerGui:FindFirstChild("ARKHER_STUDIO") if not g then return end
 local w=g.Root:FindFirstChild(name,true) if not w then return end
 local c=w:FindFirstChild("Tools",true) or w
 for _,b in ipairs(c:GetDescendants()) do if b:IsA("TextButton") then b.Activated:Connect(function()
  local o=b.BackgroundColor3 b.BackgroundColor3=Color3.fromRGB(0,255,136) task.delay(0.2,function() b.BackgroundColor3=o end)
  local cat=MAP2[name] or "" local pat=cat~="" and ("arkher."..cat.."."..string.lower(b.Name)) or string.lower(b.Name)
  call(pat,b.Name)
 end) end end
end
for _,n in ipairs({"ARKHER_Compositor","ARKHER_Color","ARKHER_Mocap","ARKHER_Facial","ARKHER_Crowd","ARKHER_Traffic","ARKHER_Weather","ARKHER_Ocean","ARKHER_Vegetation","ARKHER_Building","ARKHER_Character","ARKHER_Nav","ARKHER_Scripting","ARKHER_Debug","ARKHER_Profiler"}) do pcall(wire2,n) end
print("[V1.28 MAX] +15 editores MÁXIMO — total 317 editores, literalmente tudo")
"""
    for r in roots:
        if r.cls=="StarterPlayer":
            for f in r.children:
                if f.name=="StarterPlayerScripts":
                    f.add(Inst("LocalScript","ARKHER_ToolsFunctional_V28",{"Source":(T_STRING, FUNC28)}))
    return roots

if __name__=="__main__":
    roots=build_all_v121()
    roots=patch22b(roots)
    roots=patch24(roots)
    roots=patch25(roots)
    roots=patch26(roots)
    roots=patch27(roots)
    roots=patch28(roots)
    out=os.path.join(REL,"ARKHER_STUDIO_1_GENESIS_EDITION_V1_28.rbxl")
    write(out, serialize(roots))
    print(f"V1.28 PERFEITO MÁXIMO {out} ({os.path.getsize(out)/1048576:.2f} MB)")
    subprocess.run(["python3","tools/validate_rbxm.py",out], cwd=ROOT)
    from build_complete import arkher_installer_folder
    write(os.path.join(REL,"ARKHER_STUDIO_1_GENESIS_EDITION_V1_28.rbxm"), serialize([arkher_installer_folder()]))
    print("rbxm V1.28 done")
