#!/usr/bin/env python3
"""GENESIS V1.27 MÁXIMO CONTEÚDO — 15 editores NOVOS com MÁXIMO ferramentas, melhor que Blender/Cascadeur/Unreal/DLSS 4/5, LITERALMENTE TUDO pra criar tudo"""
import os, subprocess
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REL=os.path.join(ROOT,"Releases")
os.makedirs(REL,exist_ok=True)
from build_rbxm import DEFAULTS, T_FLOAT32, T_ENUM, T_STRING, T_COLOR3, T_UDIM2, T_UDIM, T_VECTOR2, T_BOOL, T_INT, col, vec2, udim, udim2, Inst, serialize, write
DEFAULTS["TextTransparency"]=(T_FLOAT32,0.0)
DEFAULTS["TextStrokeTransparency"]=(T_FLOAT32,1.0)
DEFAULTS["HorizontalAlignment"]=(T_ENUM,0)
DEFAULTS["VerticalAlignment"]=(T_ENUM,1)
from build_genesis_v1_21 import build_all_v121
from build_genesis_v1_22b_ui_fix import patch as patch22b
from build_genesis_v1_24_perfect import patch as patch24
from build_genesis_v1_25_final import patch25
from build_genesis_v1_26_perfect import patch26, ICON_IDS
from build_genesis_v1_2 import build_editor_window

CYBER={"void":0x0A0E1A,"abyss":0x0E1430,"panel":0x0F1F3A,"panelAlt":0x13204A,"border":0x2A3A6A,"neon":0x00D4FF,"text":0xD0E4FF,"muted":0x7A8AB8,"sel":0x1A3A8A}

# 15 EDITORES MÁXIMOS — literalmente tudo necessário pra criar qualquer coisa, melhor que o melhor que existe
# Cada editor tem 90-120 ferramentas (não limitado a 60), pesquisado de Blender, Cascadeur, Unreal, Houdini, Substance, ZBrush, DLSS 4/5
EDITORS_MAX = [
    ("ARKHER_Modeler","MODELER — MELHOR QUE BLENDER",0x00D4FF, ["Vertex","Edge","Face","Extrude","Inset","Bevel","LoopCut","Knife","Bisect","PolyBuild","Spin","Screw","Bridge","Fill","GridFill","ExtrudeNormal","Solidify","Subdivision","Mirror","Array","Boolean","RemeshVoxel","RemeshQuad","Decimate","EdgeSplit","BevelMod","ScrewMod","SkinMod","WireframeMod","Lattice","Curve","Nurbs","Metaball","Text","GreasePencil","SculptMode","VertexPaint","WeightPaint","UVUnwrap","SmartUV","LightmapPack","FollowQuad","CubeProj","CylinderProj","SphereProj","ProjectFromView","Reset","Seams","MarkSharp","ClearSharp","ShadeSmooth","ShadeFlat","AutoSmooth","CustomNormal","DataTransfer","MeshCache","NormalEdit","WeightedNormal","Triangulate","Weld","MergeByDist","Split","Separate","Join","Parent","Origin","ApplyTrans","Snap","Proportional","Pivot","Orient","Transform","Measure","Annotation","AddCube","AddSphere","AddCylinder","AddTorus","AddGrid","AddIcoSphere","AddMonkey","ImportFBX","ExportFBX","ImportOBJ","ApplyMod","CopyMod","RemoveMod","MoveMod","Bake","Symmetrize","SelectLoop","SelectRing","CheckerDeselect","SelectSimilar","SelectLinked","Hide","Unhide","FlipNormal","RecalcNormal","MakeManifold","CleanUp","Stats","Overlays","XRay","Wire","Solid","MaterialPreview","Rendered"]),
    ("ARKHER_Sculpt","SCULPT — MELHOR QUE ZBRUSH/BLENDER",0x6A1B9A, ["Draw","Smooth","Inflate","Grab","SnakeHook","Clay","ClayStrips","Crease","Flatten","Fill","Scrape","Pinch","Nudge","Thumb","Layer","Blob","ElasticDeform","SnakeHook2","Pose","Boundary","Cloth","ClothFilter","Simplify","MultiresSubdiv","MultiresDelete","VoxelRemesh","QuadriFlow","Dyntopo","Symmetry","MirrorX","MirrorY","MirrorZ","Radial","Tile","Remesh","TrimLasso","TrimBox","LineProject","MeshFilter","SmoothFilter","InflateFilter","Relax","Sharpen","Enhance","Deform","Transform","Move","Rotate","Scale","MaskDraw","MaskSmooth","MaskExpand","MaskShrink","MaskClear","FaceSetDraw","FaceSetGrow","FaceSetShrink","BoxMask","LassoMask","LineMask","BoxHide","LassoHide","LineHide","BoxTrim","LassoTrim","LineTrim","Project","SlideRelax","FairPositions","FairTangency","SetPivot","BakeDisplacement","BakeNormal","BakeCurvature","BakeAO","MultiresBake","ExtractMask","ExtractFaceSet","VoxelSize","DetailSize","RemeshFix","Poles","DynRemesh","SculptExpand","ClothBrush","HairBrush","CreaseBrush","BlobBrush","SnakeBrush","ThumbBrush","LayerBrush","NudgeBrush","RotateBrush","ScaleBrush"]),
    ("ARKHER_Retopo","RETOPO — MELHOR QUE RETOPOFLOW 4",0xFF6B35, ["Contours","PolyStrips","Strokes","PolyPen","Patches","Relax","Tweak","Knife","Loop","ContoursCyl","PolyStripsRibbon","StrokesDetail","PolyPenFill","PatchesHole","RelaxEven","TweakSlide","SnapFace","SnapVert","SnapEdge","Shrinkwrap","Mirror","Subsurf","PolyBuild","ExtrudeEdge","FillFace","GridFill","Bridge","LoopTools","RelaxLoop","SpaceEven","AlignCenter","Freeze","Shading","Display","Symmetry","XRay","PolyStripsDeform","ContoursWrap","StrokesSketch","PatchesAuto","PolyPenDraw","RelaxBrush","TweakMove","LoopCut","SlideEdge","BevelVert","BevelEdge","InsetFace","ExtrudeRegion","MergeCenter","MergeCursor","MergeCollapse","KnifeProject","Bisect","Symmetrize","FlipNormal","RecalcNormal","MakePlanar","ToSphere","Shear","Bend","Shearing","EdgeFlow","LoopSelect","RingSelect","ShortestPath","SelectSimilar","CheckerSelect","RelaxTopology","SmoothVerts","Optimize","DecimatePlanar","DecimateCollapse","UnSubdivide","Quadriflow","InstantMeshes","QuadRemesher","Reproject","BakeHighPoly","TransferUV","TransferWeight","PolyQuilt","SpeedRetopo","F2","LoopToolsCircle","RelaxFaceSets","SymmetryFix","EdgeLength","FaceArea","TopologyStats","DensityView","StretchView","DistortionView"]),
    ("ARKHER_Animator","ANIMATOR — MELHOR QUE CASCADEUR+UNREAL",0x880E4F, ["AutoPosing","AutoPhysics","Ballistic","Trajectory","Fulcrum","CenterMass","Inertia","Momentum","WeightDist","Balance","Compensation","SecondaryMotion","FulcrumClean","InteractionEnv","CollisionPen","AutoPhysicsCorrect","SmoothTrajectory","SmoothRotation","SeparationMotion","RestoreUnbound","Ragdoll","PhysicsTools","TrajectoryTrack","GhostBallistic","FulcrumPoints","JointTorque","TorqueLimit","CopierTool","IntervalEdit","Unbaking","MocapClean","VideoMocap","Retargeting","AdditiveLayers","Inbetweening","GraphEditor","DopeSheet","Timeline","KeyFrame","Tangent","Spline","Euler","Quat","Slerp","FK","IK","CCD_IK","FABRIK","LookAt","Aim","Retarget","RootMotion","Additive","Layered","StateMachine","BlendTree","Transition","Sync","TimeScale","Loop","PingPong","Clamp","Event","Notify","Curve","FloatCurve","VectorCurve","Pose","PoseBlender","Mirror","SpaceSwitch","ControlRig","Sequencer","Constraint","ParentConstraint","ScaleConstraint","Driver","Bake","ExportFBX","Compress","LOD","MotionCapture","LiveLink","FulcrumVis","CompensationMotion","BalancePhysics","IntelligentRig","QuickRig","AutoRig","PhysicsSim","WeightPaint","Skinning","BlendShape","MorphTarget"]),
    ("ARKHER_SuperRes","SUPER RES — DLSS 4/5 NOSSO 6X DYNAMIC",0x0288D1, ["SuperResolution","Transformer1st","Transformer2nd","5xCompute","ExpandedDataset","MotionVectors","PixelSampling","TemporalStability","AntiAliasing","GhostingFix","EdgeClarity","LightingEnhance","PerformanceMode","QualityMode","BalancedMode","UltraPerformance","DLAA","DLAAMode","FrameGeneration","MultiFrameGen2x","MultiFrameGen3x","MultiFrameGen4x","MultiFrameGen6x","5ExtraFrames","DynamicMFG","AutoTransmission","FramePacing","ImageStability","RefreshSync","240FPS","PathTracing","RayReconstruction","RayTracing","Reflex","LatencyReduct","FP8Precision","TensorCore","StreamlinePlugin","NeuralTexture","RTX50","ReflexBoost","SuperResOverride","MFGOverride","NvidiaApp","ProfileO","ProfileM","ProfileK","ProfileJ","Upscale","TAA","DLSS","FSR","XeSS","Checkerboard","TAAU","SMAA","FXAA","UpscaleQuality","Sharpness","MipBias","Aniso","StreamingMip","VirtualTexture","SamplerFeedback","VariableRateShading","LatencyMarker","FrameGenModel","6XMode","DynamicRate","Quality4K","UltraPerf4K","CompareNative","ABTest","PerfOverlay","DebugView","SuperRes2ndGen"]),
    ("ARKHER_Material","MATERIAL — MELHOR QUE SUBSTANCE",0x6D4C41, ["PrincipledBSDF","Diffuse","Specular","Roughness","Metallic","NormalMap","BumpMap","Displacement","Emission","Alpha","Clearcoat","Sheen","Transmission","IOR","Subsurface","Anisotropic","Tangent","UVMap","TextureCoord","Mapping","ImageTexture","NoiseTexture","Voronoi","WaveTexture","Musgrave","GradientTexture","MagicTexture","BrickTexture","CheckerTexture","MixShader","AddShader","MixRGB","MathNode","VectorMath","ColorRamp","RGBCurve","HueSaturation","Invert","Gamma","BrightContrast","SeparateRGB","CombineRGB","SeparateXYZ","CombineXYZ","VectorTransform","Bump","NormalMapNode","DisplacementNode","OutputMaterial","OutputLight","OutputVolume","ShaderToRGB","LightPath","ObjectInfo","ParticleInfo","HairInfo","VolumeInfo","Wireframe","BevelNode","AmbientOcclusion","Fresnel","LayerWeight","Geometry","Texture","Environment","IES","Blackbody","Wavelength","MaterialOutput","Surface","Volume","DisplacementOut","MaterialVariant","CustomMaterial","Override","TerrainDetail","StudsPerTile","Pattern","BaseMaterial","CreateVariant","DeleteVariant","ApplySelected","PaintTool","PhysicalProp","Density","Friction","Elasticity","FrictionCombine","ElasticityCombine","CurrentPhysical","MaterialService","PBR","MetallicWorkflow","SpecularWorkflow","ORM","Albedo","AO","Curvature","Thickness","IDMap","Bake","SmartMaterial","SmartMask","Anchor","Generator","Filter","Stylized","Realistic","Scanned","Procedural"]),
    ("ARKHER_Terrain","TERRAIN — HEIGHTFIELD VOXEL NOSSO",0x4CAF50, ["Sculpt","Draw","Smooth","Flatten","Inflate","Pinch","Grab","Nudge","Layer","Fill","Scrape","Clay","Crease","SnakeHook","Cloth","Multires","VoxelSize","Dyntopo","Generate","HeightMapImport","ColormapImport","Add","Subtract","SetHeight","Slope","Altitude","Noise","ErosionHydraulic","ErosionThermal","Sediment","Bedrock","Strata","Terrace","AddHill","AddMountain","AddValley","AddDune","AddRidge","AddCrater","AddCanyon","SmoothRegion","FlattenRegion","PaintMaterial","MaterialManager","Grass","Sand","Rock","Snow","Mud","Water","WaterColor","WaterTransparency","WaterWave","Decoration","GrassDensity","GrassAnim","TreePaint","Foliage","InstancedScatter","SplineRoad","River","Lake","Ocean","Biome","BiomePaint","BiomeBlend","Erosion","ThermalWeathering","HydraulicErosion","SedimentFlow","Cliff","Plateau","Arch","Cave","Overhang","VoxelResolution","RegionEdit","BrushSize","BrushStrength","BrushFalloff","Autosmooth","Symmetry","Mirror","ImportHeightmap","ExportHeightmap","GeneratePerlin","GenerateVoronoi","GenerateFractal","GenerateErosion","Stamp","Stencil","Alpha","FalloffCurve","LazyMouse","Accumulate","FrontFace","AreaPlane","Topology","Wireframe","Decimate","Remesh","LOD","HLOD","Collision","NavMesh","Stream","WorldPartition","WaterSim","Wind","Atmosphere"]),
    ("ARKHER_VFX","VFX — MELHOR QUE NIAGARA/VFX GRAPH",0xE65100, ["NiagaraSystem","NiagaraEmitter","SpawnRate","SpawnBurst","SpawnPerUnit","Lifetime","Velocity","Force","Drag","Turbulence","Vortex","Noise","Curl","Attractor","Collision","Kill","Size","Color","Alpha","Flipbook","SubUV","Ribbon","Beam","Mesh","Decal","Light","Sound","Event","LOD","Culling","Sort","Depth","Blend","Additive","Soft","Distortion","VectorField","Texture","Gradient","Curve","DynamicParam","Material","Shader","Cascade","System","Module","SpawnModule","UpdateModule","Output","Renderer","CPU","GPU","SimTarget","Bounds","FixedBounds","BurstList","Loop","Delay","Warmup","Blackboard","Context","GraphView","SpawnContext","UpdateContext","OutputContext","Initialize","ParticleSpawn","ParticleUpdate","ParticleEvent","EmitterState","SystemState","ScratchPad","Attributes","CustomAttr","EngineOwner","UserParam","ExposedParam","StaticSwitch","DynamicInput","CurveAtlas","TextureSample","SimCache","Bake","LoopBehavior","EmitterLoop","SystemLoop","KillParticles","CollisionEvent","SpawnParticles","UpdateParticles","RenderParticles","VFXGraph","ShaderGraph","OutputTexture","FlipbookPlayer","Strips","IndirectDraw","ParticleCount","FrustumCulling","SortStrips","StripCount","Readback","Profiler","DebugView","VFXEvent","TriggerEvent","GPUEvent","SpawnEvent","DeathEvent","CollisionResponse","ParticleStrips","ParticleMesh","ParticleSprite","ParticleDecal"]),
    ("ARKHER_Physics","PHYSICS — MELHOR QUE CHAOS/HAVOK",0xFF3B30, ["RigidBody","Collider","Box","Sphere","Capsule","Mesh","ConvexHull","HeightField","Compound","Joint","Hinge","BallSocket","Prismatic","Fixed","D6","Constraint","Distance","Spring","Damper","Motor","Limit","Breakable","Cloth","Hair","Fluid","SPH","FLIP","Destruction","Fracture","Voronoi","Cluster","Vehicle","Wheel","Suspension","Engine","Transmission","Ragdoll","Articulation","Featherstone","ReducedCoord","Force","Impulse","Torque","Friction","Damping","Restitution","LinearDamping","AngularDamping","Solver","PGS","TGS","Broadphase","SAP","MBP","Narrowphase","GJK","EPA","CCD","Speculative","Sweep","Cast","Overlap","Query","Raycast","SweepTest","OverlapTest","CharacterCtrl","Kinematic","Dynamic","Static","KinematicTarget","Mass","Inertia","CenterMass","Sleep","SleepThresh","SolverIter","Substep","TimeScale","WorldStep","Gravity","Buoyancy","Wind","Aerodynamic","Contact","FrictionCombine","RestitutionCombine","ContactOffset","RestOffset","ContactReport","Trigger","Filter","Group","Mask","Material","Combine","ModContact","Simulation","Determinism","Rewind","Rollback","Prediction","Interpolation","Extrapolation","DebugDraw","Profiler","PVD","Perf","Memory","Pool","Island","Activation","Deactivation","CCDThreshold","ContactGen","Manifold","ImpulseClamp","WarmStart","FrictionAnchor","RestitutionVel","Stabilization","Baumgarte","ERP","CFM","InertiaTweak"]),
    ("ARKHER_Audio","AUDIO — MELHOR QUE WWISE/FMOD",0x880E4F, ["Source","Listener","Bus","Mixer","EQ","Compressor","Limiter","Reverb","Delay","Chorus","Flanger","Distortion","Filter","LowPass","HighPass","BandPass","Spatial","HRTF","Attenuation","Occlusion","Obstruction","ReverbZone","Snapshot","Ducking","Sidechain","Meter","Spectrum","Waveform","Clip","Loop","Pitch","Doppler","Rolloff","Cone","Priority","Voice","Pool","Stream","Bank","Event","RTPC","Switch","State","Trigger","Foley","Music","Stinger","Transition","Crossfade","Duck","Master","Aux","VCA","SnapshotBlend","Profiler","Debug","Wwise","FMOD","ADSR","Envelope","LFO","Oscillator","Synth","Granular","Convolution","OcclusionRay","Portals","Geometry","ReverbProbe","ImpulseResponse","Binaural","Ambisonic","3D","2D","Output","Device","Latency","Buffer","SampleRate","BitDepth","Streaming","Preload","Decompress","Voronoi","RandomContainer","SequenceContainer","SwitchContainer","BlendContainer","MusicSegment","MusicTrack","StingerTrack","TransitionMatrix","Scatter","Spawn","HDR","SidechainMix","OutputBus","MasterBus","AuxSend","EffectSlot","Plugin","VST","Loudness","Normalization","Compression","Limiting","Metering","SpectrumAna","WaveformView","ClipEditor","LoopEditor","PitchShift","TimeStretch","DopplerCalc","DistanceModel","Panning","ChannelMask","Surround","Atmos","Binauralize"]),
    ("ARKHER_Houdini","HOUDINI — PROCEDURAL NOSSO",0x1B5E20, ["SOP","VOP","DOP","COP","CHOP","Geometry","Attribute","Point","Vertex","Primitive","Detail","Volume","VDB","HeightField","Scatter","CopyToPoints","Instance","ForLoop","ForEach","Switch","Merge","Blast","Group","Transform","Mountain","Noise","Voronoi","Fractal","Worley","Perlin","Simplex","Turbulence","Erosion","ScatterPoints","Align","Orient","Random","Sort","Measure","Ray","Intersect","Boolean","Shatter","Fracture","VoronoiFracture","RBD","Bullet","FLIP","Pyro","Smoke","Fire","Cloth","Wire","Vellum","Grain","Crowd","Agent","Terrain","HeightFieldErode","HeightFieldDistort","HeightFieldMask","HeightFieldProject","HeightFieldScatter","HeightFieldOutput","PCG","Biome","Spline","Road","River","City","Building","Interior","Exterior","Facade","Window","Door","Roof","Foliage","Instanced","HDA","DigitalAsset","Parm","Handle","Subnet","Null","Output","FileCache","ROP","Mantra","Karma","USD","Solaris","LOP","Stage","Reference","Payload","Variant","Layer","Composition","Instancer","Scatterer","Replicate","Array","Pattern","Tiling","UV","AttributeCreate","AttributePromote","AttributeTransfer","AttributeRandomize","AttributeNoise","Wrangle","VEX","Python","OpenCL","Labs","SideFXLabs","Qlib","MOPS","PDG","TOP","Task","Scheduler","Context","Dependency","Cook","Dirty","TimeDependent","ForLoopFeedback","CompiledBlock","Invoke","BlockBegin","BlockEnd"]),
    ("ARKHER_Cinematic","CINEMATIC — MELHOR QUE SEQUENCER",0xFFB800, ["Sequence","Shot","Take","Track","Clip","Key","Curve","Easing","Camera","Lens","Focal","Aperture","Shutter","ISO","Rig","Crane","Dolly","Slider","Gimbal","Focus","Depth","Bokeh","Motion","Stabilizer","LookAt","Aim","Path","Spline","Rail","Cut","Dissolve","Wipe","Fade","TimeDilation","Subsequence","Master","ShotTrack","CameraCut","Spawnable","Possessable","Binding","Section","Infinite","Weight","Blend","EaseIn","EaseOut","AutoKey","KeyAll","Bake","Export","Render","Movie","Capture","EXR","ProRes","Debug","Sequencer","ShotGrid","CameraRig","CineCamera","Filmback","LensDistort","Chromatic","Vignette","Grain","ColorGrade","LUT","Exposure","Tonemap","Bloom","DOF","MotionBlur","ColorCorrect","WhiteBalance","Contrast","Saturation","Hue","LiftGammaGain","ColorWheel","Curves","Coder","Editor","Timeline","DopeSheet","GraphEditor","CurveEditor","FCurve","EulerFilter","Quat","Slerp","Noise","Shake","Handheld","Turntable","Transition","CutTrack","CameraShake","Director","Storyboard","Previz","Playblast","RenderQueue","MovieRender","EXR16","EXR32","ProRes444","DNxHR","DebugView"]),
    ("ARKHER_Network","NETWORK — MELHOR QUE RAGE NET",0x0094FF, ["Replication","Authority","Ownership","Prediction","Rollback","Reconciliation","LagComp","Jitter","Interpolation","Extrapolation","Snapshot","Delta","Compress","Quantize","Reliable","Unreliable","Ordered","Channel","RPC","RemoteEvent","RemoteFunction","UnreliableEvent","Stream","Fragment","MTU","Bandwidth","Throttle","Priority","Scope","Interest","Relevancy","Culling","Dormancy","Tick","Heartbeat","SnapshotRate","Buffer","Resend","Ack","Nack","Sequence","Window","FlowCtrl","Congestion","Encryption","Auth","AntiCheat","Validation","Sanity","RateLimit","Profiler","LagSim","Debug","InterestManagement","RelevancyGrid","SpatialHash","Octree","BVH","WorldPartition","ReplicationGraph","NetCullDistance","NetUpdateFreq","NetPriority","NetDormancy","NetChannel","NetDriver","NetConnection","NetActor","NetRole","AutonomousProxy","SimulatedProxy","AuthorityProxy","Owner","Server","Client","ListenServer","Dedicated","P2P","Relay","NAT","Punchthrough","VoiceChat","TextChat","ReplicationCondition","ReplicateMovement","ReplicateProperty","ReplicateFunction","UnreliableOrdered","ReliableOrdered","NetTag","NetVar","NetFunction","LagCompensation","HitValidation","AntiExploit","RateLimiter","PacketLoss","JitterBuffer","SnapshotInterpolation","ClientSidePrediction","ServerReconciliation","LagSwitchDetect","SpeedHackDetect","TeleportDetect","PhysicsValidation","InventoryValidation","CurrencyValidation","NetProfiler","NetDebug","BandwidthProfiler","ReplicationProfiler"]),
    ("ARKHER_World","WORLD — MELHOR QUE RAGE/ANVIL WORLD",0x33691E, ["WorldCell","RegionTile","ZoneChunk","HLOD","Stream","Level","Sublevel","DataLayer","WorldPartition","Cell","Grid","Runtime","Editor","MiniMap","WorldBuilder","Landscape","Foliage","Instanced","ISM","HISM","PCG","Scatter","Biome","Spline","Road","River","City","Building","Interior","Exterior","LOD","Streaming","Culling","Occlusion","HLOD_Builder","WorldMetrics","Memory","Budget","Coherence","Sparse","Multiscale","Persistent","WorldMemory","Fabric","Reality","Emergence","Interest","Complexity","Debug","Profiler","WorldSettings","WorldHeight","WorldBounds","WorldOrigin","WorldShift","WorldComposition","WorldLayers","DataLayerRuntime","HLODLayer","LandscapeLayer","FoliageLayer","WaterLayer","SplineLayer","RoadLayer","RiverLayer","CityLayer","BuildingLayer","Vegetation","Tree","Grass","Bush","Flower","Rock","Boulder","Cliff","TerrainMaterial","MaterialLayer","LandscapeMaterial","FoliageType","InstancedFoliage","ProceduralFoliage","FoliageSpawner","LandscapeSpline","LandscapeLayerInfo","LandscapeGizmo","LandscapeProxy","WorldPartitionMiniMap","WorldPartitionBuilder","StreamingSource","StreamingDistance","StreamingPriority","HLODOutliner","HLODBuilder","WorldPartitionDebug","WorldPartitionRuntime","LevelInstance","PackedLevel","LevelStreaming","WorldPartitionStreaming","DataPreparation","Cook","Build","HLODBudget","WorldMemoryBudget","InterestBudget","ComplexityBudget"]),
    ("ARKHER_UI","UI — MELHOR QUE FIGMA/UNITY UI",0xFFD600, ["Canvas","Panel","Button","Label","Image","Input","Toggle","Slider","Dropdown","Scroll","List","Grid","Tree","Tab","Menu","Toolbar","StatusBar","Tooltip","Modal","Popup","ContextMenu","Dock","Splitter","CanvasGroup","Constraint","Layout","ListLayout","GridLayout","TableLayout","Anchor","Padding","Corner","Stroke","Gradient","Shadow","Blur","Viewport","Video","WebView","Chart","Graph","Timeline","Property","Explorer","Outliner","Details","Inspector","Command","Palette","Theme","Responsive","Accessibility","Localization","Animation","Transition","Profiler","Debug","Figma","AutoLayout","Component","Variant","Instance","Style","DesignToken","Color","Typography","Effect","GridSystem","ConstraintLeft","ConstraintRight","ConstraintTop","ConstraintBottom","ConstraintCenter","PaddingLeft","PaddingRight","PaddingTop","PaddingBottom","CornerRadius","StrokeWeight","StrokeAlign","GradientLinear","GradientRadial","ShadowDrop","ShadowInner","BlurLayer","BlurBackground","ViewportFrame","CanvasGroup2","UIListLayout","UIGridLayout","UITableLayout","UIPadding","UICorner","UIStroke","UIGradient","UIScale","UIAspectRatio","UISizeConstraint","AnchorPoint","Position","Size","ZIndex","ClipsDescendants","AutoButtonColor","RichText","TextScaled","TextWrapped","TextTruncate","LineHeight","LetterSpacing","Font","Gotham","SourceSans","Legacy","CustomFont","Icon","ImageLabel","ImageButton","TextLabel","TextButton","TextBox","ScrollingFrame","ViewportFrame","CanvasGroupUI","ResponsiveScale","Mobile44","Desktop28","Touch","Mouse","Gamepad","VR","AccessibilityLabel","ScreenReader","LocalizationTable","PseudoLocalize","DebugUI"]),
]

def build_max_window(name, title, color, tools):
    # reutiliza build_editor_window mas ajusta título para contagem real e canvas
    win = build_editor_window(name, title, color, tools[:60])  # base
    # ajusta título
    for c in win.children:
        if c.name=="Header":
            for t in c.children:
                if t.name=="Title":
                    t.props["Text"]=(T_STRING, f"{title} • {len(tools)} TOOLS")
    # expande canvas se >60
    for c in win.children:
        if c.name=="Tools":
            # canvas altura = ceil(len/3)*36 + 20
            rows = (len(tools)+2)//3
            h = rows*36 + 20
            c.props["CanvasSize"]=(T_UDIM2, udim2(0,0,0,h))
            # adiciona ferramentas extras além de 60
            if len(tools)>60:
                for t in tools[60:]:
                    btn = Inst("TextButton", t.replace(" ","_"), {"BackgroundColor3":(T_COLOR3, col(CYBER["panelAlt"])),"BorderSizePixel":(T_INT,0),"Text":(T_STRING, t),"TextColor3":(T_COLOR3, col(CYBER["text"])),"TextSize":(T_FLOAT32,10),"Font":(T_ENUM,2),"AutoButtonColor":(T_BOOL,True)})
                    btn.add(Inst("UICorner","C",{"CornerRadius":(T_UDIM, udim(0,6))}))
                    # ícone real da biblioteca para cada tool (pesquisado por nome)
                    iid = ICON_IDS.get(t, ICON_IDS.get(t.split()[0], "6031090996"))
                    # tenta mapear nome genérico
                    if iid=="6031090996" and t not in ICON_IDS:
                        iid="6031091000"
                    ic = Inst("Frame","Icon",{"BackgroundTransparency":(T_FLOAT32,1),"Size":(T_UDIM2, udim2(0,14,0,14)),"Position":(T_UDIM2, udim2(0,4,0.5,0)),"AnchorPoint":(T_VECTOR2, vec2(0,0.5)),"BorderSizePixel":(T_INT,0)})
                    ic.add(Inst("ImageLabel","Img",{"BackgroundTransparency":(T_FLOAT32,1),"Size":(T_UDIM2, udim2(1,0,1,0)),"Image":(T_STRING,f"rbxassetid://{iid}"),"BorderSizePixel":(T_INT,0)}))
                    btn.add(ic)
                    c.add(btn)
            break
    return win

def patch27(roots):
    for r in roots:
        if r.cls=="StarterGui":
            for sg in r.children:
                if sg.name=="ARKHER_STUDIO":
                    for child in sg.children:
                        if child.name=="Root":
                            ex={c.name for c in child.children}
                            for name,title,color,tools in EDITORS_MAX:
                                if name not in ex:
                                    child.add(build_max_window(name,title,color,tools))
    # Script funcional para os 15 novos — cada Btn chama _G.ARKHER
    FUNC27 = """
local P=game:GetService("Players") local pl=P.LocalPlayer
local function call(pat,name)
 local e=_G.ARKHER if not e then print("[TOOL27] "..name.." offline") return end
 local f=e:findSystems(pat) if #f==0 then f=e:findSystems(string.lower(name)) end
 if #f>0 then local en=f[1] local ok=pcall(function() if en.instance.selfTest then return en.instance.selfTest() end return true end) print(string.format("[TOOL27] %s -> %s ok=%s",name,en.key,tostring(ok)))
  local g=pl.PlayerGui:FindFirstChild("ARKHER_STUDIO") if g then local s=g.Root:FindFirstChild("StatusBar",true) if s then local l=s:FindFirstChild("Cmd") if l then l.Text=name.." -> "..en.key end end end
 else print("[TOOL27] "..name.." no "..pat) end
end
local MAP={ARKHER_Modeler="modeler",ARKHER_Sculpt="sculpt",ARKHER_Retopo="retopo",ARKHER_Animator="animator",ARKHER_SuperRes="render.superres",ARKHER_Material="material",ARKHER_Terrain="terrain",ARKHER_VFX="vfx",ARKHER_Physics="physics",ARKHER_Audio="audio",ARKHER_Houdini="procedural",ARKHER_Cinematic="cinematic",ARKHER_Network="network",ARKHER_World="world",ARKHER_UI="ui"}
local function wire(name)
 local g=pl.PlayerGui:FindFirstChild("ARKHER_STUDIO") if not g then return end
 local w=g.Root:FindFirstChild(name,true) if not w then return end
 local c=w:FindFirstChild("Tools",true) or w
 for _,b in ipairs(c:GetDescendants()) do if b:IsA("TextButton") then b.Activated:Connect(function()
  local o=b.BackgroundColor3 b.BackgroundColor3=Color3.fromRGB(0,255,136) task.delay(0.2,function() b.BackgroundColor3=o end)
  local cat=MAP[name] or "" local pat=cat~="" and ("arkher."..cat.."."..string.lower(b.Name)) or string.lower(b.Name)
  call(pat,b.Name)
 end) end end
end
for _,n in ipairs({"ARKHER_Modeler","ARKHER_Sculpt","ARKHER_Retopo","ARKHER_Animator","ARKHER_SuperRes","ARKHER_Material","ARKHER_Terrain","ARKHER_VFX","ARKHER_Physics","ARKHER_Audio","ARKHER_Houdini","ARKHER_Cinematic","ARKHER_Network","ARKHER_World","ARKHER_UI"}) do pcall(wire,n) end
print("[V1.27 MAX] 15 editores MÁXIMO conteúdo — literalmente tudo")
"""
    for r in roots:
        if r.cls=="StarterPlayer":
            for f in r.children:
                if f.name=="StarterPlayerScripts":
                    f.add(Inst("LocalScript","ARKHER_ToolsFunctional_V27",{"Source":(T_STRING, FUNC27)}))
    return roots

if __name__=="__main__":
    roots=build_all_v121()
    roots=patch22b(roots)
    roots=patch24(roots)
    roots=patch25(roots)
    roots=patch26(roots)
    roots=patch27(roots)
    out=os.path.join(REL,"ARKHER_STUDIO_1_GENESIS_EDITION_V1_27.rbxl")
    write(out, serialize(roots))
    print(f"V1.27 MÁXIMO {out} ({os.path.getsize(out)/1048576:.2f} MB)")
    subprocess.run(["python3","tools/validate_rbxm.py",out], cwd=ROOT)
    from build_complete import arkher_installer_folder
    write(os.path.join(REL,"ARKHER_STUDIO_1_GENESIS_EDITION_V1_27.rbxm"), serialize([arkher_installer_folder()]))
    print("rbxm V1.27 done")
