# ARKHER V1 :: catalog specification (R1 A,S,X; R2 B,U,Y; R3 C,D,M; R4 E,F,G; R5 H,I,J; R6 K,L; R7 N,O,P,Q,R)
# Each system = area x aspect. Aspect decides the kit (a real working machine) and the
# specialized methods emitted for that system.

ASPECTS_A = [
    ("Core Runtime",        "orchestrator", "runtime lifecycle and phase orchestration"),
    ("Registry",            "registry",     "typed record storage, tagging and querying"),
    ("Pipeline",            "pipeline",     "staged processing with isolation and retries"),
    ("Cache",               "cache",        "hot-path memoization with policy-driven eviction"),
    ("Adaptive Controller", "controller",   "closed-loop regulation of the subsystem"),
    ("Analytics",           "analyzer",     "statistical trend, anomaly and forecast analysis"),
    ("Budget Governor",     "budgeter",     "allocation of a scarce resource across consumers"),
    ("Access Guard",        "guard",        "capability checks and rate limiting"),
    ("Codec",               "codec",        "encode/decode/diff of the subsystem payloads"),
    ("Dependency Graph",    "graph",        "relationship modelling and shortest-path resolution"),
    ("Predictor",           "predictor",    "forecasting of future demand and state"),
    ("Audit Ledger",        "ledger",       "append-only journal with sealing and histograms"),
    ("Recovery",            "recovery",     "checkpointing and rollback of subsystem state"),
]

AREAS_A = [
    ("Module", "module"), ("Entity", "entity"), ("Component", "component"), ("Resource", "resource"),
    ("Scheduler", "scheduler"), ("Job", "job"), ("Event", "event"), ("Signal", "signal"),
    ("Dependency", "dependency"), ("Service", "service"), ("Lifecycle", "lifecycle"), ("State", "state"),
    ("Type", "type"), ("Reflection", "reflection"), ("Serialization", "serialization"), ("Memory", "memory"),
    ("Object Pool", "pool"), ("Async", "async"), ("Parallel Execution", "parallel"), ("Worker", "worker"),
    ("Error", "error"), ("Logging", "logging"), ("Diagnostics", "diagnostics"), ("Validation", "validation"),
    ("Configuration", "config"), ("Environment", "environment"), ("Feature Flag", "featureflag"),
    ("Capability", "capability"), ("Permission", "permission"), ("Sandbox", "sandbox"),
    ("API Gateway", "apigateway"), ("Extension", "extension"), ("Hot Reload", "hotreload"),
    ("Versioning", "versioning"), ("Migration", "migration"), ("Build Graph", "buildgraph"),
    ("Bootstrap", "bootstrap"), ("Math Kernel", "math"), ("Spatial Kernel", "spatial"), ("Time Kernel", "time"),
]

ASPECTS_S = [
    ("Profiler",             "analyzer",     "measurement and statistical profiling"),
    ("Budget Governor",      "budgeter",     "hard per-frame budget enforcement"),
    ("Adaptive Controller",  "controller",   "closed-loop quality regulation"),
    ("Bottleneck Analyzer",  "analyzer",     "detection of over-budget behaviour"),
    ("LOD Policy",           "policy",       "fidelity band selection and dispatch"),
    ("Dynamic Scaler",       "controller",   "runtime scaling of workload"),
    ("Predictive Optimizer", "predictor",    "ahead-of-time optimization from forecasts"),
    ("Result Cache",         "cache",        "reuse of expensive computations"),
    ("Streaming Governor",   "streamer",     "distance-driven load/unload of work"),
    ("Telemetry",            "ledger",       "counters, histograms and percentile export"),
    ("Fallback Recovery",    "recovery",     "safe degradation and restoration"),
    ("Quality Composer",     "composer",     "blending of quality signals into one output"),
    ("Scheduling Policy",    "policy",       "fair dispatch of the subsystem workload"),
    ("Compression Codec",    "codec",        "payload size reduction"),
    ("Throttle Guard",       "guard",        "rate limiting of expensive operations"),
    ("Spatial Index",        "index",        "spatial acceleration of the subsystem queries"),
    ("Cost Graph",           "graph",        "cost relationships and critical path"),
    ("Numeric Solver",       "solver",       "iterative convergence of the subsystem model"),
    ("Registry",             "registry",     "catalogued optimization records"),
    ("Optimization Pipeline","pipeline",     "ordered optimization passes"),
]

AREAS_S = [
    ("CPU", "cpu"), ("GPU", "gpu"), ("Memory", "memory"), ("Network", "network"),
    ("Rendering", "rendering"), ("Physics", "physics"), ("AI", "ai"), ("Animation", "animation"),
    ("Audio", "audio"), ("Terrain", "terrain"), ("Asset", "asset"), ("Texture", "texture"),
    ("Geometry", "geometry"), ("Particle", "particle"), ("UI", "ui"), ("Streaming", "streaming"),
    ("Scripting", "scripting"), ("NPC", "npc"), ("World Simulation", "world"), ("Lighting", "lighting"),
    ("Shadow", "shadow"), ("Reflection Probe", "reflection"), ("Post Process", "postfx"),
    ("Occlusion", "occlusion"), ("Culling", "culling"), ("LOD", "lod"), ("Thermal", "thermal"),
    ("Battery", "battery"), ("Mobile", "mobile"), ("Console", "console"), ("VR", "vr"),
]

ASPECTS_X = [
    ("Validator",     "pipeline",     "multi-stage validation of inputs"),
    ("Guard",         "guard",        "capability enforcement and rate limiting"),
    ("Registry",      "registry",     "record keeping of security decisions"),
    ("Audit Ledger",  "ledger",       "tamper-evident audit journal"),
    ("Recovery",      "recovery",     "state protection and rollback"),
    ("Policy Engine", "policy",       "ordered application of security policy"),
    ("Analyzer",      "analyzer",     "behavioural anomaly analysis"),
    ("Integrity Codec","codec",       "checksummed encoding of protected data"),
    ("Trust Controller","controller", "adaptive trust scoring"),
    ("Orchestrator",  "orchestrator", "incident state machine"),
]

AREAS_X = [
    ("Runtime Validation", "runtime"), ("Input Validation", "input"), ("Asset Validation", "asset"),
    ("Project Validation", "project"), ("Script Isolation", "script"), ("Plugin Isolation", "plugin"),
    ("Network Validation", "network"), ("Replication Safety", "replication"), ("Datastore Safety", "datastore"),
    ("Player Safety", "player"), ("Permission", "permission"), ("Capability", "capability"),
    ("Sandbox", "sandbox"), ("Process Isolation", "isolation"), ("Integrity", "integrity"),
    ("Checksum", "checksum"), ("Crash Recovery", "crash"), ("State Recovery", "staterecovery"),
    ("Error Containment", "error"), ("Watchdog", "watchdog"), ("Health Check", "health"),
    ("Telemetry Privacy", "privacy"), ("Anti Exploit", "antiexploit"), ("Rate Limit", "ratelimit"),
    ("Quota", "quota"), ("Dependency Validation", "dependency"), ("Version Validation", "version"),
    ("Schema Enforcement", "schema"), ("Serialization Safety", "serialization"), ("Memory Safety", "memorysafety"),
    ("Resource Guard", "resourceguard"), ("API Gateway", "apigateway"), ("Trust Model", "trust"),
    ("Content Safety", "content"), ("Collaboration Permission", "collab"), ("Build Validation", "build"),
    ("Deployment Gate", "deployment"), ("Rollback", "rollback"), ("Incident Response", "incident"),
    ("Compliance Report", "compliance"), ("Access Review", "accessreview"),
]


# ---------------------------------------------------------------- ROUND 2 (B, U, Y)
ASPECTS_B = [
    ("Document Model",     "document",   "transactional editing state with dirty tracking and revisions"),
    ("Command Stack",      "commands",   "undoable operations with grouping and coalescing"),
    ("Selection Model",    "selection",  "multi-selection with primary item and filters"),
    ("Panel Layout",       "layout",     "dockable panel tree with persistence"),
    ("Widget Surface",     "widget",     "retained-mode UI tree with data bindings"),
    ("Property Inspector", "inspector",  "reflection-driven property editing"),
    ("Node Editor",        "nodegraph",  "typed node graph authoring and compilation"),
    ("Registry",           "registry",   "catalogued editor records, tags and queries"),
    ("Tool Pipeline",      "pipeline",   "staged tool execution with isolation"),
    ("Preview Cache",      "cache",      "reuse of expensive editor previews"),
    ("Session Sync",       "session",    "multi-user editing of this editor surface"),
    ("Task Runner",        "taskgraph",  "incremental background work for the editor"),
    ("Telemetry",          "ledger",     "editor interaction journal and histograms"),
    ("Recovery",           "recovery",   "crash-safe checkpointing of editor state"),
]

AREAS_B = [
    ("Viewport", "viewport"), ("Scene Outliner", "outliner"), ("Property Panel", "properties"),
    ("Asset Browser", "assetbrowser"), ("Material Editor", "materialeditor"), ("Terrain Editor", "terraineditor"),
    ("Animation Editor", "animationeditor"), ("Particle Editor", "particleeditor"), ("Audio Editor", "audioeditor"),
    ("Script Editor", "scripteditor"), ("Visual Script Editor", "visualeditor"), ("Timeline", "timeline"),
    ("Curve Editor", "curveeditor"), ("Blueprint Library", "blueprint"), ("Prefab Editor", "prefab"),
    ("Tool Palette", "toolpalette"), ("Gizmo", "gizmo"), ("Grid And Snapping", "grid"),
    ("Camera Bookmark", "camerabookmark"), ("Layer Manager", "layers"), ("Tag Manager", "tags"),
    ("Search And Filter", "search"), ("Command Palette", "palette"), ("Shortcut Map", "shortcuts"),
    ("Theme", "theme"), ("Localization", "localization"), ("Preferences", "preferences"),
    ("Project Browser", "projectbrowser"), ("Package Manager", "packages"), ("Plugin Host", "pluginhost"),
    ("Console", "console"), ("Log Viewer", "logviewer"), ("Profiler View", "profilerview"),
    ("Debugger View", "debuggerview"), ("Memory View", "memoryview"), ("Network View", "networkview"),
    ("Statistics HUD", "statshud"), ("Notification Center", "notifications"), ("Wizard", "wizard"),
    ("Template Gallery", "templates"), ("Import Dialog", "importer"), ("Export Dialog", "exporter"),
    ("Version Panel", "versionpanel"), ("Review Panel", "reviewpanel"), ("Comment Thread", "comments"),
    ("Onboarding Tour", "onboarding"), ("Accessibility", "accessibility"), ("Touch Input", "touch"),
    ("Gamepad Navigation", "gamepad"), ("Undo History", "undohistory"),
]

ASPECTS_U = [
    ("Source Model",          "source",       "tokenizing, symbol extraction and diagnostics"),
    ("Symbol Registry",       "registry",     "declaration records, tags and lookup"),
    ("Analysis Pipeline",     "pipeline",     "staged static analysis of the subsystem"),
    ("Graph Authoring",       "nodegraph",    "visual authoring compiled to real Luau"),
    ("Compile Cache",         "cache",        "reuse of compiled and analyzed artifacts"),
    ("Diagnostics Ledger",    "ledger",       "append-only journal of code events"),
    ("Reference Graph",       "graph",        "symbol relationships and reachability"),
    ("Refactor Commands",     "commands",     "undoable code transformations"),
    ("Completion Predictor",  "predictor",    "ranking of the next likely symbol"),
    ("Sandbox Guard",         "guard",        "capability limits on executed code"),
    ("Execution Orchestrator","orchestrator", "state machine of the execution lifecycle"),
    ("Buffer Document",       "document",     "transactional text and metadata buffer"),
    ("Build Tasks",           "taskgraph",    "incremental compile and test tasks"),
    ("Codegen Codec",         "codec",        "encode and diff of generated code payloads"),
    ("Failure Recovery",      "recovery",     "checkpointing and rollback of code state"),
]

AREAS_U = [
    ("Lexer", "lexer"), ("Parser", "parser"), ("Syntax Tree", "ast"), ("Symbol Table", "symtable"),
    ("Type Inference", "typeinference"), ("Diagnostics", "diagnostics"), ("Linter", "linter"),
    ("Formatter", "formatter"), ("Completion", "completion"), ("Signature Help", "signature"),
    ("Hover Documentation", "hover"), ("Go To Definition", "definition"), ("Find References", "references"),
    ("Rename Refactor", "rename"), ("Extract Function", "extract"), ("Code Action", "codeaction"),
    ("Snippet", "snippet"), ("Template Codegen", "codegen"), ("Module Resolver", "resolver"),
    ("Import Manager", "imports"), ("Dependency Analysis", "depanalysis"), ("Dead Code", "deadcode"),
    ("Complexity Metrics", "complexity"), ("Test Runner", "testrunner"), ("Coverage", "coverage"),
    ("Breakpoint", "breakpoint"), ("Step Execution", "stepping"), ("Watch Expression", "watch"),
    ("Call Stack", "callstack"), ("Hot Reload", "hotreload"), ("Script Sandbox", "scriptsandbox"),
    ("Bytecode Cache", "bytecode"), ("Visual Script Graph", "visualgraph"), ("Node Library", "nodelibrary"),
    ("Graph Compiler", "graphcompiler"), ("Event Binding", "eventbinding"), ("Coroutine Scheduler", "coroutine"),
    ("API Surface", "apisurface"), ("Documentation Generator", "docgen"), ("Script Profiler", "scriptprofiler"),
]

ASPECTS_Y = [
    ("Live Session",       "session",   "presence, locks and operation log"),
    ("Merge Engine",       "merge",     "three-way reconciliation and conflict handling"),
    ("Change Ledger",      "ledger",    "auditable journal of production changes"),
    ("Review Commands",    "commands",  "undoable review and approval actions"),
    ("Production Tasks",   "taskgraph", "incremental production and release tasks"),
    ("Permission Guard",   "guard",     "role checks and rate limiting"),
    ("Record Registry",    "registry",  "catalogued production records"),
    ("Working Set",        "selection", "the set of items currently being worked on"),
    ("Release Recovery",   "recovery",  "checkpoint and rollback of production state"),
    ("Progress Analyzer",  "analyzer",  "throughput, trend and risk analysis"),
]

AREAS_Y = [
    ("Multiuser Session", "multiuser"), ("Presence", "presence"), ("Live Cursor", "cursor"),
    ("Object Lock", "objectlock"), ("Change Feed", "changefeed"), ("Operational Transform", "ot"),
    ("Branch", "branch"), ("Commit", "commit"), ("Merge", "merge"), ("Conflict Resolution", "conflict"),
    ("Review Request", "reviewrequest"), ("Code Review", "codereview"), ("Asset Review", "assetreview"),
    ("Comment", "comment"), ("Annotation", "annotation"), ("Approval", "approval"),
    ("Permission Role", "role"), ("Team Directory", "team"), ("Task Board", "taskboard"),
    ("Milestone", "milestone"), ("Sprint", "sprint"), ("Issue Tracker", "issues"), ("Bug Report", "bugreport"),
    ("Playtest Session", "playtest"), ("Feedback Capture", "feedback"), ("Analytics Report", "analytics"),
    ("Release Channel", "channel"), ("Build Pipeline", "buildpipeline"), ("Continuous Validation", "validation"),
    ("Deployment Gate", "deploygate"), ("Rollback Plan", "rollbackplan"), ("Changelog", "changelog"),
    ("Version Tag", "versiontag"), ("Artifact Registry", "artifacts"), ("Localization Workflow", "locworkflow"),
    ("Content Approval", "contentapproval"), ("Audit Trail", "audittrail"), ("Handoff Package", "handoff"),
    ("Studio Metrics", "studiometrics"), ("Knowledge Base", "knowledge"),
]


# ---------------------------------------------------------------- ROUND 3 (C, D, M)
ASPECTS_C = [
    ("Scene Graph",         "scenegraph", "hierarchical world state with lazy world transforms"),
    ("Instancing",          "prefab",     "template instancing with per-instance overrides"),
    ("Spatial Index",       "index",      "spatial acceleration of world queries"),
    ("Streaming",           "chunker",    "chunked residency driven by viewer distance"),
    ("Living Simulation",   "simulation", "tiered simulation that keeps running unobserved"),
    ("Registry",            "registry",   "catalogued world records, tags and queries"),
    ("Pipeline",            "pipeline",   "staged processing of world data"),
    ("Query Cache",         "cache",      "memoized world queries with eviction"),
    ("LOD Policy",          "policy",     "fidelity band scheduling for world content"),
    ("Persistence Codec",   "codec",      "encode, diff and patch of persisted world state"),
    ("Relationship Graph",  "graph",      "world relationships and reachability"),
    ("Budget Governor",     "budgeter",   "world resource allocation under a hard budget"),
    ("Event Ledger",        "ledger",     "append-only world event journal"),
    ("Recovery",            "recovery",   "checkpointing and rollback of world state"),
]

AREAS_C = [
    ("World Root", "worldroot"), ("Region", "region"), ("Zone", "zone"), ("Cell", "cell"),
    ("Chunk", "chunk"), ("Entity", "entity"), ("Actor", "actor"), ("Prop", "prop"),
    ("Interactive Object", "interactive"), ("Spawn Point", "spawnpoint"), ("Portal", "portal"),
    ("Trigger Volume", "trigger"), ("Boundary", "boundary"), ("Navigation", "navigation"),
    ("Waypoint", "waypoint"), ("Path", "path"), ("Landmark", "landmark"),
    ("Point Of Interest", "poi"), ("Building Instance", "buildinginstance"),
    ("Vegetation Instance", "veginstance"), ("Water Body", "waterbody"), ("Road Segment", "roadsegment"),
    ("Bridge", "bridge"), ("Tunnel", "tunnel"), ("Interior", "interior"), ("Room", "room"),
    ("Door", "door"), ("Light Instance", "lightinstance"), ("Sound Emitter", "soundemitter"),
    ("Weather Zone", "weatherzone"), ("Time Of Day", "timeofday"), ("Season", "season"),
    ("Climate", "climate"), ("Ecosystem", "ecosystem"), ("Wildlife", "wildlife"),
    ("Traffic", "traffic"), ("Crowd", "crowd"), ("Economy Node", "economynode"),
    ("Faction Territory", "territory"), ("Quest Volume", "questvolume"), ("Save State", "savestate"),
    ("Replication Group", "replicationgroup"), ("Ownership", "ownership"),
    ("Visibility Set", "visibilityset"), ("Occlusion Volume", "occlusionvolume"),
    ("World Origin Shift", "originshift"),
]

ASPECTS_D = [
    ("Heightfield",        "heightfield", "editable height data with sculpt and erosion"),
    ("Voxel Volume",       "voxel",       "sparse volumetric material data"),
    ("Sculpt Commands",    "commands",    "undoable terrain edits with grouping"),
    ("Material Composer",  "composer",    "weighted blending of terrain layers"),
    ("Mesh Builder",       "mesh",        "triangle mesh extraction for the terrain surface"),
    ("Tile Streaming",     "chunker",     "tile residency driven by viewer distance"),
    ("Erosion Solver",     "solver",      "iterative convergence of the erosion model"),
    ("Noise Field",        "field",       "procedural elevation and mask fields"),
    ("Spline Feature",     "spline",      "curve-driven terrain features"),
    ("Scatter Layer",      "scatter",     "blue-noise placement over the surface"),
    ("LOD Policy",         "policy",      "tile fidelity scheduling"),
    ("Tile Registry",      "registry",    "catalogued terrain tiles and metadata"),
    ("Compression Codec",  "codec",       "terrain payload size reduction"),
    ("Analysis",           "analyzer",    "statistical analysis of terrain metrics"),
    ("Recovery",           "recovery",    "checkpointing and rollback of terrain edits"),
    ("Budget Governor",    "budgeter",    "terrain work allocation under a hard budget"),
]

AREAS_D = [
    ("Heightmap", "heightmap"), ("Voxel Terrain", "voxelterrain"), ("Sculpting", "sculpting"),
    ("Smoothing", "smoothing"), ("Erosion", "erosion"), ("Hydraulic Erosion", "hydraulic"),
    ("Thermal Erosion", "thermal"), ("Sediment", "sediment"), ("River", "river"), ("Lake", "lake"),
    ("Ocean", "ocean"), ("Coastline", "coastline"), ("Beach", "beach"), ("Cliff", "cliff"),
    ("Mountain", "mountain"), ("Valley", "valley"), ("Canyon", "canyon"), ("Plateau", "plateau"),
    ("Dune", "dune"), ("Cave", "cave"), ("Overhang", "overhang"), ("Arch", "arch"),
    ("Crater", "crater"), ("Volcano", "volcano"), ("Glacier", "glacier"), ("Snow Line", "snowline"),
    ("Biome Blend", "biomeblend"), ("Material Layer", "materiallayer"), ("Texture Splat", "splat"),
    ("Vegetation Mask", "vegmask"), ("Road Carving", "roadcarve"), ("Foundation Flatten", "foundation"),
    ("Collision Field", "collisionfield"), ("Navigation Mesh", "navmesh"), ("Terrain LOD", "terrainlod"),
    ("Tile Streaming", "tilestreaming"), ("Terrain Compression", "terraincompression"),
    ("Terrain Painting", "terrainpainting"), ("Terrain Import", "terrainimport"),
    ("Terrain Export", "terrainexport"),
]

ASPECTS_M = [
    ("Grammar",             "lsystem",     "rewriting grammar interpreted into geometry"),
    ("Constraint Solver",   "wfc",         "socket-constrained tiling with entropy collapse"),
    ("Distribution",        "scatter",     "blue-noise distribution with masks"),
    ("Network Planner",     "network",     "graph planning with A* routing"),
    ("Spline Layout",       "spline",      "curve layout, arc length and offsets"),
    ("Mesh Synthesis",      "mesh",        "procedural triangle mesh construction"),
    ("Noise Field",         "field",       "coherent noise driving the generator"),
    ("Rule Synthesizer",    "synthesizer", "rule expansion with constraints"),
    ("Instancing",          "prefab",      "template instancing of generated content"),
    ("Generation Pipeline", "pipeline",    "ordered generation stages"),
    ("Result Cache",        "cache",       "reuse of expensive generation results"),
    ("Determinism Ledger",  "ledger",      "seed and output journal proving reproducibility"),
    ("Seed Registry",       "registry",    "catalogued seeds and generated artefacts"),
    ("Validation Recovery", "recovery",    "checkpointing and rollback of generation state"),
]

AREAS_M = [
    ("Seed", "seed"), ("Deterministic Random", "detrandom"), ("Biome Map", "biomemap"),
    ("Continent", "continent"), ("Island", "island"), ("Mountain Range", "mountainrange"),
    ("River Network", "rivernetwork"), ("Road Network", "roadnetwork"), ("Rail Network", "railnetwork"),
    ("Trail", "trail"), ("City Layout", "citylayout"), ("District", "district"), ("Block", "block"),
    ("Lot", "lot"), ("Building Footprint", "footprint"), ("Facade", "facade"), ("Floor Plan", "floorplan"),
    ("Interior Layout", "interiorlayout"), ("Furniture", "furniture"), ("Village", "village"),
    ("Farmland", "farmland"), ("Fence", "fence"), ("Wall", "wall"), ("Ruin", "ruin"),
    ("Dungeon", "dungeon"), ("Cave System", "cavesystem"), ("Maze", "maze"),
    ("Bridge Generation", "bridgegen"), ("Tower", "tower"), ("Wall Circuit", "wallcircuit"),
    ("Forest", "forest"), ("Tree", "tree"), ("Grass", "grass"), ("Rock Field", "rockfield"),
    ("Debris", "debris"), ("Cloud", "cloud"), ("Star Field", "starfield"),
    ("Texture Synthesis", "texturesynth"), ("Material Variation", "materialvariation"),
    ("Damage Pattern", "damage"), ("Crowd Distribution", "crowddist"), ("Loot Table", "loot"),
    ("Quest Graph", "questgraph"), ("Name Generator", "namegen"),
]


# ---------------------------------------------------------------- round 4 :: E MATERIALS
ASPECTS_E = [
    ("Definition",          "material",   "layered PBR definition resolved into parameters"),
    ("Layer Composition",   "composer",   "ordered layer composition with blend rules"),
    ("Shading Graph",       "shadegraph", "node graph evaluated and compiled to Luau"),
    ("Texture Sampling",    "sampler",    "atlas packing, mip chain and filtered sampling"),
    ("Procedural Detail",   "field",      "coherent noise detail driving the surface"),
    ("Variant Registry",    "registry",   "named variants and their lifecycle"),
    ("Parameter Budget",    "budgeter",   "texel and layer budget allocation"),
    ("Streaming",           "streamer",   "residency and demand-driven texture streaming"),
    ("Compression Codec",   "codec",      "serialization and compression of material data"),
    ("Quality Policy",      "policy",     "device tier rules for the surface"),
    ("Instance Cache",      "cache",      "resolved-parameter cache keyed by context"),
    ("Analysis",            "analyzer",   "cost, redundancy and outlier analysis"),
    ("Authoring Pipeline",  "pipeline",   "ordered authoring and bake stages"),
    ("Change Ledger",       "ledger",     "auditable history of material edits"),
    ("Recovery",            "recovery",   "fallback surface when data is missing or invalid"),
]

AREAS_E = [
    ("Material Library", "library"), ("Surface Definition", "surfacedef"), ("Albedo", "albedo"),
    ("Roughness", "roughness"), ("Metalness", "metalness"), ("Normal Detail", "normaldetail"),
    ("Height Displacement", "displacement"), ("Ambient Occlusion", "ao"), ("Emissive", "emissive"),
    ("Opacity", "opacity"), ("Subsurface", "subsurface"), ("Clear Coat", "clearcoat"),
    ("Anisotropy", "anisotropy"), ("Sheen", "sheen"), ("Iridescence", "iridescence"),
    ("Layer Blending", "layerblend"), ("Triplanar Projection", "triplanar"), ("UV Mapping", "uvmap"),
    ("Decal", "decal"), ("Wear And Tear", "wear"), ("Dust Accumulation", "dust"),
    ("Moisture", "moisture"), ("Rust", "rust"), ("Snow Cover", "snowcover"),
    ("Vertex Painting", "vertexpaint"), ("Terrain Splat", "splat"), ("Texture Atlas", "atlas"),
    ("Mip Policy", "mippolicy"), ("Texture Streaming", "texstream"), ("Detail Tiling", "detailtile"),
    ("Procedural Texture", "proctex"), ("Material Instance", "instance"),
    ("Material Variant", "variant"), ("Shader Graph", "shadergraph"),
    ("Parameter Animation", "paramanim"), ("Material LOD", "materiallod"),
    ("Physical Response", "physicalresponse"), ("Material Preview", "preview"),
    ("Material Validation", "validation"), ("Material Migration", "migration"),
]

# ---------------------------------------------------------------- round 4 :: F RENDERING
ASPECTS_F = [
    ("Frame Graph",         "framegraph", "declared passes, culling, ordering and aliasing"),
    ("View And Culling",    "camera",     "view state, frustum culling and screen-size LOD"),
    ("Visibility Set",      "visibility", "cell, portal and occluder visibility"),
    ("Geometry Virtualization", "impostor", "impostor and HLOD synthesis under a budget"),
    ("Lighting Rig",        "lightrig",   "light clustering, importance and cascades"),
    ("Probe Volume",        "probe",      "irradiance probes encoded in spherical harmonics"),
    ("Temporal Resolve",    "temporal",   "history reprojection with neighbourhood clamping"),
    ("Adaptive Resolution", "upscaler",   "render-scale ladder and edge-aware reconstruction"),
    ("Draw Budget",         "budgeter",   "draw call and triangle budget allocation"),
    ("Render Policy",       "policy",     "device tier rules for the frame"),
    ("Pass Cache",          "cache",      "reuse of pass results across frames"),
    ("Frame Analysis",      "analyzer",   "per-pass cost analysis and outlier detection"),
    ("Orchestration",       "orchestrator", "frame lifecycle orchestration"),
    ("Fallback Recovery",   "recovery",   "safe frame when a pass fails or overruns"),
]

AREAS_F = [
    ("Frame Pipeline", "framepipeline"), ("Depth Prepass", "depthprepass"),
    ("Opaque Pass", "opaquepass"), ("Transparent Pass", "transparentpass"),
    ("Shadow Pass", "shadowpass"), ("Cascade Shadows", "cascades"), ("Contact Shadows", "contact"),
    ("Ambient Occlusion Pass", "aopass"), ("Screen Space Reflection", "ssr"),
    ("Global Illumination", "gi"), ("Light Clustering", "lightcluster"),
    ("Volumetric Light", "volumetric"), ("Atmosphere", "atmosphere"), ("Sky Model", "sky"),
    ("Fog", "fog"), ("Cloud Rendering", "clouds"), ("Water Rendering", "water"),
    ("Reflection Probe", "reflectionprobe"), ("Exposure", "exposure"), ("Tonemapping", "tonemap"),
    ("Color Grading", "grading"), ("Bloom", "bloom"), ("Depth Of Field", "dof"),
    ("Motion Blur", "motionblur"), ("Antialiasing", "antialiasing"),
    ("Temporal Accumulation", "temporalaccum"), ("Render Scale", "renderscale"),
    ("Sharpening", "sharpening"), ("Draw Call Batching", "batching"), ("Instanced Draw", "instanced"),
    ("Occlusion Culling", "occlusion"), ("Portal Culling", "portal"), ("Frustum Culling", "frustum"),
    ("Distance Culling", "distanceculling"), ("Impostor Rendering", "impostorrender"),
    ("HLOD", "hlod"), ("Mesh LOD", "meshlod"), ("Geometry Streaming", "geostream"),
    ("Decal Rendering", "decalrender"), ("Particle Rendering", "particlerender"),
    ("UI Rendering", "uirender"), ("Debug Visualization", "debugvis"),
    ("Wireframe Overlay", "wireframe"), ("Frame Capture", "framecapture"),
    ("Render Target", "rendertarget"), ("Memory Aliasing", "memaliasing"),
    ("Mobile Fast Path", "mobilepath"), ("VR Stereo Path", "vrpath"),
    ("Console Path", "consolepath"), ("Frame Pacing", "framepacing"),
]

# ---------------------------------------------------------------- round 4 :: G NEURAL
ASPECTS_G = [
    ("Inference Core",      "inference",  "dense network forward pass and training"),
    ("Feature Extraction",  "field",      "signal features feeding the model"),
    ("Temporal History",    "temporal",   "history buffers reused across frames"),
    ("Reconstruction",      "upscaler",   "resolution ladder and image reconstruction"),
    ("Model Registry",      "registry",   "named models and their lifecycle"),
    ("Weight Codec",        "codec",      "weight serialization and quantized transport"),
    ("Quality Predictor",   "predictor",  "predicted quality and cost of a setting"),
    ("Compute Budget",      "budgeter",   "inference time budget allocation"),
    ("Result Cache",        "cache",      "cached inference results keyed by input"),
    ("Heuristic Policy",    "policy",     "rule fallback when the model is unavailable"),
    ("Error Analysis",      "analyzer",   "residual and drift analysis"),
    ("Training Ledger",     "ledger",     "auditable record of training and deployment"),
    ("Sampling Graph",      "graph",      "dependency graph of sampling stages"),
    ("Fallback Recovery",   "recovery",   "deterministic fallback when inference fails"),
]

AREAS_G = [
    ("Neural Upscaling", "neuralupscale"), ("Temporal Reconstruction", "temporalrecon"),
    ("Spatial Reconstruction", "spatialrecon"), ("Frame Interpolation", "frameinterp"),
    ("Motion Vector Estimation", "motionvector"), ("Disocclusion Handling", "disocclusion"),
    ("Ghosting Suppression", "ghosting"), ("Adaptive Sharpening", "adaptivesharpen"),
    ("Denoising", "denoise"), ("Detail Synthesis", "detailsynth"),
    ("Texture Super Resolution", "texturesr"), ("Geometry Detail Prediction", "geodetail"),
    ("Shading Approximation", "shadingapprox"), ("Light Transport Prediction", "lightpredict"),
    ("Ambient Occlusion Prediction", "aopredict"), ("Reflection Prediction", "reflectpredict"),
    ("Animation Compression", "animcompress"), ("Behaviour Prediction", "behaviorpredict"),
    ("Performance Prediction", "perfpredict"), ("Quality Estimation", "qualityestimate"),
    ("Perceptual Metric", "perceptual"), ("Model Registry", "modelregistry"),
    ("Weight Quantization", "quantization"), ("Model Distillation", "distillation"),
    ("Inference Scheduler", "inferencesched"), ("Batch Inference", "batchinference"),
    ("Feature Cache", "featurecache"), ("Deterministic Seeding", "detseed"),
    ("Fallback Heuristic", "fallbackheuristic"), ("Drift Detection", "drift"),
    ("Confidence Gating", "confidence"), ("Model Versioning", "modelversion"),
    ("On Device Budget", "ondevicebudget"), ("Training Data Synthesis", "datasynth"),
    ("Evaluation Harness", "evalharness"), ("Neural Debug", "neuraldebug"),
]

# ---------------------------------------------------------------- round 5 :: H PHYSICS
ASPECTS_H = [
    ("Body Dynamics",       "rigidbody",  "integration, impulses, damping and sleeping of a body"),
    ("Collision Shape",     "collider",   "shape bounds, support mapping and closest points"),
    ("Contact Generation",  "contact",    "narrow-phase manifolds with normal, depth and point"),
    ("Constraint Solver",   "constraint", "sequential impulses, friction, joints and warm starting"),
    ("Query",               "raycaster",  "rays, sweeps and overlaps against the simulation"),
    ("Character Motion",    "charmotor",  "capsule move-and-slide with slopes, steps and jumps"),
    ("Vehicle",             "vehicle",    "suspension, drivetrain, steering and tire friction"),
    ("Broadphase Index",    "index",      "spatial acceleration of candidate pair finding"),
    ("Budget Governor",     "budgeter",   "simulation time budget allocation across islands"),
    ("Simulation Policy",   "policy",     "device tier rules for substeps, iterations and sleep"),
    ("Result Cache",        "cache",      "reuse of expensive simulation and query results"),
    ("Analysis",            "analyzer",   "energy, jitter and cost analysis of the simulation"),
    ("Determinism Ledger",  "ledger",     "auditable journal proving reproducible simulation"),
    ("Recovery",            "recovery",   "checkpointing and rollback when the solver diverges"),
]

AREAS_H = [
    ("Rigid Body", "rigidbody"), ("Static Body", "staticbody"), ("Kinematic Body", "kinematicbody"),
    ("Mass Properties", "massproperties"), ("Inertia Tensor", "inertia"), ("Center Of Mass", "centerofmass"),
    ("Gravity Field", "gravityfield"), ("Force Accumulator", "force"), ("Impulse", "impulse"),
    ("Torque", "torque"), ("Linear Damping", "lineardamping"), ("Angular Damping", "angulardamping"),
    ("Sleeping", "sleeping"), ("Island Solver", "island"), ("Substepping", "substepping"),
    ("Fixed Timestep", "fixedstep"), ("Continuous Detection", "ccd"), ("Broadphase", "broadphase"),
    ("Narrowphase", "narrowphase"), ("Sphere Collider", "spherecollider"), ("Box Collider", "boxcollider"),
    ("Capsule Collider", "capsulecollider"), ("Mesh Collider", "meshcollider"),
    ("Heightfield Collider", "heightfieldcollider"), ("Compound Collider", "compoundcollider"),
    ("Trigger Volume", "trigger"), ("Collision Layer", "collisionlayer"), ("Collision Filter", "collisionfilter"),
    ("Contact Manifold", "manifold"), ("Restitution", "restitution"), ("Friction Model", "friction"),
    ("Penetration Recovery", "penetration"), ("Distance Joint", "distancejoint"), ("Hinge Joint", "hingejoint"),
    ("Ball Joint", "balljoint"), ("Slider Joint", "sliderjoint"), ("Motorized Joint", "motorjoint"),
    ("Breakable Joint", "breakjoint"), ("Rope Simulation", "rope"), ("Cloth Simulation", "cloth"),
    ("Soft Body", "softbody"), ("Buoyancy", "buoyancy"), ("Wind Force", "wind"),
    ("Explosion Force", "explosion"), ("Character Controller", "charactercontroller"),
    ("Vehicle Chassis", "vehiclechassis"), ("Wheel Suspension", "suspension"),
    ("Raycast Query", "raycast"), ("Shapecast Query", "shapecast"), ("Overlap Query", "overlap"),
]

# ---------------------------------------------------------------- round 5 :: I ANIMATION
ASPECTS_I = [
    ("Skeleton",            "skeleton",  "bone hierarchy, bind pose and world resolution"),
    ("Clip Sampling",       "clip",      "keyframe tracks sampled, retimed and evented"),
    ("Layered Blending",    "animator",  "layers, crossfades, masks and blend trees"),
    ("Inverse Kinematics",  "ik",        "two-bone, FABRIK and constrained look-at solving"),
    ("Physical Blend",      "ragdoll",   "physical bones blended against the animated pose"),
    ("Retarget Graph",      "graph",     "bone mapping and retarget path resolution"),
    ("Compression Codec",   "codec",     "curve compression and quantized transport"),
    ("Event Ledger",        "ledger",    "auditable journal of animation events fired"),
    ("Playback Pipeline",   "pipeline",  "ordered sample, blend, ik and output stages"),
    ("Pose Cache",          "cache",     "reuse of sampled poses across frames and instances"),
    ("Quality Policy",      "policy",    "device tier rules for rate, bones and solvers"),
    ("Analysis",            "analyzer",  "pop, drift and cost analysis of playback"),
    ("Recovery",            "recovery",  "fallback pose when data or solving fails"),
]

AREAS_I = [
    ("Skeleton Rig", "skeletonrig"), ("Bone Hierarchy", "bonehierarchy"), ("Bind Pose", "bindpose"),
    ("Pose Buffer", "posebuffer"), ("Animation Clip", "animclip"), ("Keyframe Track", "keytrack"),
    ("Curve Interpolation", "curveinterp"), ("Clip Looping", "cliploop"), ("Clip Events", "clipevents"),
    ("Playback Speed", "playbackspeed"), ("Animation Layer", "animlayer"), ("Layer Mask", "layermask"),
    ("Additive Layer", "additivelayer"), ("Crossfade", "crossfade"), ("Blend Tree", "blendtree"),
    ("State Machine", "animstate"), ("Transition Rule", "transitionrule"), ("Root Motion", "rootmotion"),
    ("Locomotion Blend", "locomotionblend"), ("Turn In Place", "turninplace"),
    ("Foot Placement IK", "footik"), ("Hand Placement IK", "handik"), ("Look At IK", "lookatik"),
    ("Aim Offset", "aimoffset"), ("Spine Bend", "spinebend"), ("Ragdoll Blend", "ragdollblend"),
    ("Physical Animation", "physanim"), ("Hit Reaction", "hitreaction"), ("Retargeting", "retargeting"),
    ("Bone Mapping", "bonemapping"), ("Animation Compression", "animcompression"),
    ("Animation Streaming", "animstreaming"), ("Animation LOD", "animlod"),
    ("Crowd Animation", "crowdanim"), ("Motion Matching", "motionmatching"),
    ("Procedural Animation", "proceduralanim"), ("Facial Animation", "facialanim"),
    ("Morph Target", "morphtarget"), ("Cloth Animation", "clothanim"), ("Animation Debug", "animdebug"),
]

# ---------------------------------------------------------------- round 5 :: J CHARACTERS
ASPECTS_J = [
    ("Rig Definition",      "skeleton",  "character rig definition and bone budget"),
    ("Motion Set",          "clip",      "the clips a character owns and how they sample"),
    ("Blend Controller",    "animator",  "layered playback driving the character"),
    ("Look And Reach",      "ik",        "look-at, reach and foot placement for the character"),
    ("Physical Response",   "ragdoll",   "physical reaction, ragdoll and recovery"),
    ("Locomotion",          "charmotor", "capsule locomotion driving the character"),
    ("Appearance Composer", "composer",  "composition of appearance slots into a look"),
    ("Variant Registry",    "registry",  "named character variants and their lifecycle"),
    ("Budget Governor",     "budgeter",  "per-character cost allocation in a crowd"),
    ("Streaming",           "streamer",  "distance-driven residency of character data"),
    ("Recovery",            "recovery",  "fallback character state when data is missing"),
]

AREAS_J = [
    ("Digital Human", "digitalhuman"), ("Character Rig", "characterrig"), ("Body Proportions", "proportions"),
    ("Skin Definition", "skindef"), ("Hair", "hair"), ("Eyes", "eyes"), ("Teeth", "teeth"),
    ("Facial Rig", "facialrig"), ("Expression Set", "expression"), ("Lip Sync", "lipsync"),
    ("Gaze Behaviour", "gaze"), ("Breathing", "breathing"), ("Blinking", "blinking"),
    ("Posture", "posture"), ("Gesture", "gesture"), ("Clothing", "clothing"), ("Accessory", "accessory"),
    ("Armor", "armor"), ("Equipment Slot", "equipslot"), ("Outfit Composition", "outfit"),
    ("Character Variant", "charvariant"), ("Body Type", "bodytype"), ("Aging", "aging"),
    ("Damage State", "damagestate"), ("Wetness Response", "wetnessresponse"),
    ("Character Physics", "characterphysics"), ("Character LOD", "characterlod"),
    ("Crowd Instance", "crowdinstance"), ("Character Streaming", "characterstreaming"),
    ("Character Debug", "characterdebug"),
]


# ---------------------------------------------------------------- round 6 :: K NPC / NMN
ASPECTS_K = [
    ("Mind Network",        "mindnet",      "the learned policy that turns perception into a decision"),
    ("Memory",              "memory",       "episodic memory with decay, recall and consolidation"),
    ("Drive System",        "need",         "drives that decay, turn urgent and get satisfied"),
    ("Emotion",             "emotion",      "appraisal of events into valence, arousal and mood"),
    ("Perception",          "perception",   "sight, hearing and bounded attention"),
    ("Reactive Behaviour",  "behaviortree", "sequences, selectors, decorators and cooldowns"),
    ("Utility Reasoning",   "utility",      "scored option selection with response curves"),
    ("Goal Planner",        "planner",      "backward GOAP planning to reach a goal state"),
    ("Navigation",          "navgraph",     "grid pathfinding, smoothing, line of sight and flow fields"),
    ("Crowd Steering",      "crowd",        "local avoidance, cohesion and arrival at scale"),
    ("Social Relations",    "society",      "affinity, factions, reputation and gossip"),
    ("Daily Schedule",      "schedule",     "hour-by-hour routine with priority interruptions"),
    ("Thinking Budget",     "budgeter",     "allocation of per-frame thinking time across NPCs"),
    ("Recovery",            "recovery",     "checkpointing and rollback of NPC state"),
]

AREAS_K = [
    ("NPC Brain", "npcbrain"), ("Neural Policy", "neuralpolicy"), ("Learning Loop", "learningloop"),
    ("Reward Model", "rewardmodel"), ("Episodic Memory", "episodicmemory"),
    ("Semantic Memory", "semanticmemory"), ("Working Memory", "workingmemory"),
    ("Memory Consolidation", "consolidation"), ("Forgetting", "forgetting"),
    ("Hunger Drive", "hungerdrive"), ("Rest Drive", "restdrive"), ("Safety Drive", "safetydrive"),
    ("Social Drive", "socialdrive"), ("Purpose Drive", "purposedrive"),
    ("Emotional State", "emotionalstate"), ("Mood", "mood"), ("Personality", "personality"),
    ("Temperament", "temperament"), ("Vision", "vision"), ("Hearing", "hearing"),
    ("Scent", "scent"), ("Attention", "attention"), ("Threat Assessment", "threatassessment"),
    ("Curiosity", "curiosity"), ("Behaviour Tree", "behaviourtree"),
    ("Behaviour State Machine", "behaviourstate"), ("Utility Selection", "utilityselection"),
    ("Goal Selection", "goalselection"), ("Plan Execution", "planexecution"),
    ("Interruption", "interruption"), ("Pathfinding", "pathfinding"),
    ("Local Avoidance", "localavoidance"), ("Crowd Flow", "crowdflow"), ("Formation", "formation"),
    ("Follow Behaviour", "followbehaviour"), ("Patrol Route", "patrolroute"),
    ("Flee Behaviour", "fleebehaviour"), ("Combat Behaviour", "combatbehaviour"),
    ("Dialogue Behaviour", "dialoguebehaviour"), ("Trade Behaviour", "tradebehaviour"),
    ("Work Behaviour", "workbehaviour"), ("Idle Behaviour", "idlebehaviour"),
    ("Relationship", "relationship"), ("Faction Membership", "factionmembership"),
    ("Reputation", "reputation"), ("Gossip", "gossip"), ("Daily Routine", "dailyroutine"),
    ("Sleep Cycle", "sleepcycle"), ("NPC LOD", "npclod"), ("NPC Debug", "npcdebug"),
]

# ------------------------------------------------------- round 6 :: L WORLD SIMULATION
ASPECTS_L = [
    ("Simulation Core",   "simulation", "observer-driven fidelity, catch-up and aggregate state"),
    ("Ecology",           "ecology",    "populations, predation, harvesting and carrying capacity"),
    ("Economy",           "economy",    "stock, production, demand, price discovery and trade"),
    ("Society",           "society",    "relations, factions, reputation and cohesion of the region"),
    ("Calendar",          "schedule",   "hours, days and seasons driving the region"),
    ("Region Graph",      "graph",      "connectivity, components and shortest path between places"),
    ("Route Network",     "network",    "roads, rivers and routes between settlements"),
    ("History Ledger",    "ledger",     "auditable journal of everything the world did"),
    ("State Codec",       "codec",      "persistence, diffing and checksum of the world state"),
    ("Streaming",         "streamer",   "distance-driven residency of simulated regions"),
    ("Fidelity Policy",   "policy",     "rules that pick full, cohort or statistical simulation"),
    ("Aggregate Cache",   "cache",      "reuse of expensive aggregate computations"),
    ("Analysis",          "analyzer",   "trend, anomaly and stability analysis of the world"),
    ("Forecast",          "predictor",  "prediction of the region's next state"),
    ("Recovery",          "recovery",   "checkpoint and rollback of the persistent world"),
]

AREAS_L = [
    ("Living World", "livingworld"), ("Region Fidelity", "regionfidelity"),
    ("Offscreen Simulation", "offscreensim"), ("Catch Up", "catchup"),
    ("Population", "population"), ("Cohort", "cohort"), ("Reification", "reification"),
    ("Settlement", "settlement"), ("Village Life", "villagelife"), ("City Life", "citylife"),
    ("Agriculture", "agriculture"), ("Livestock", "livestock"), ("Wildlife", "wildlife"),
    ("Predation", "predation"), ("Vegetation", "vegetation"), ("Weather", "weather"),
    ("Climate", "climate"), ("Season", "season"), ("Day Night Cycle", "daynight"),
    ("Water Cycle", "watercycle"), ("Resource Node", "resourcenode"),
    ("Production Chain", "productionchain"), ("Market", "market"),
    ("Price Discovery", "pricediscovery"), ("Trade Route", "traderoute"), ("Caravan", "caravan"),
    ("Wealth Distribution", "wealth"), ("Taxation", "taxation"), ("Law", "law"),
    ("Crime", "crime"), ("Justice", "justice"), ("Faction Politics", "factionpolitics"),
    ("Diplomacy", "diplomacy"), ("War", "war"), ("Migration", "migration"),
    ("Disease", "disease"), ("Festival", "festival"), ("World Event", "worldevent"),
    ("World History", "worldhistory"), ("World Persistence", "worldpersistence"),
]

# ------------------------------------------------------------------ round 7 :: N VFX
ASPECTS_N = [
    ("Emission",           "emitter",     "shaped, rate and burst emission of new particles"),
    ("Particle Simulation","particles",   "pooled integration of position, velocity, colour and life"),
    ("Force Field",        "forcefield",  "wind, attraction, vortex, drag and curl turbulence"),
    ("Ribbon And Trail",   "ribbon",      "trail points, tapering, beams and decimation"),
    ("Curve Authoring",    "spline",      "authored curves driving the effect over its life"),
    ("Effect Graph",       "shadegraph",  "node graph describing how the effect is shaded"),
    ("Effect Composition", "composer",    "blending of several effect signals into one output"),
    ("Spawn Budget",       "budgeter",    "global particle budget shared by every live effect"),
    ("Result Cache",       "cache",       "reuse of expensive effect evaluations"),
    ("Quality Policy",     "policy",      "distance and device driven fidelity bands"),
    ("Spatial Index",      "index",       "spatial acceleration of effect queries and culling"),
    ("Analysis",           "analyzer",    "cost, overdraw and stability analysis of the effect"),
    ("Recovery",           "recovery",    "checkpoint and rollback of the effect state"),
]

AREAS_N = [
    ("Spark", "spark"), ("Smoke", "smoke"), ("Fire", "fire"), ("Explosion", "explosion"),
    ("Dust", "dust"), ("Debris", "debris"), ("Impact", "impact"), ("Muzzle Flash", "muzzleflash"),
    ("Blood", "blood"), ("Water Splash", "splash"), ("Waterfall Mist", "mist"), ("Rain", "rain"),
    ("Snow", "snow"), ("Hail", "hail"), ("Fog Volume", "fogvolume"), ("Cloud", "cloud"),
    ("Lightning", "lightning"), ("Magic Aura", "magicaura"), ("Spell Cast", "spellcast"),
    ("Portal", "portal"), ("Shield Effect", "shieldfx"), ("Heal Effect", "healfx"),
    ("Buff Effect", "bufffx"), ("Status Effect", "statusfx"), ("Trail", "trail"),
    ("Ribbon", "ribbonfx"), ("Beam", "beam"), ("Laser", "laser"), ("Projectile", "projectile"),
    ("Decal", "decal"), ("Footprint", "footprint"), ("Wind Gust", "windgust"),
    ("Foliage Motion", "foliagemotion"), ("Cloth Wind", "clothwind"), ("Screen Effect", "screenfx"),
    ("Camera Shake", "camerashake"), ("Distortion", "distortion"), ("Glow", "glow"),
    ("Environment Ambience", "envambience"), ("Effect Debug", "fxdebug"),
]

# ---------------------------------------------------------------- round 7 :: O AUDIO
ASPECTS_O = [
    ("DSP Chain",          "dsp",          "biquad filtering, delay, envelope and soft clipping"),
    ("Mixer Bus",          "mixer",        "hierarchical buses, gain, mute, solo, ducking and voice stealing"),
    ("Spatialization",     "spatialaudio", "distance attenuation, panning, occlusion and doppler"),
    ("Music Sequencer",    "sequencer",    "musical time, sections, stems, cues and quantized transitions"),
    ("Voice Budget",       "budgeter",     "voice slots allocated by priority and audibility"),
    ("Streaming",          "streamer",     "distance-driven residency of audio assets"),
    ("Asset Registry",     "registry",     "catalogue of sounds, variations and metadata"),
    ("Compression Codec",  "codec",        "payload encoding of audio state and events"),
    ("Playback Policy",    "policy",       "rules choosing what may be heard right now"),
    ("Analysis",           "analyzer",     "loudness, headroom and masking analysis"),
    ("Event Ledger",       "ledger",       "auditable journal of everything that played"),
    ("Recovery",           "recovery",     "checkpoint and rollback of the audio state"),
]

AREAS_O = [
    ("Footstep", "footstep"), ("Foley", "foley"), ("Weapon Sound", "weaponsound"),
    ("Impact Sound", "impactsound"), ("Explosion Sound", "explosionsound"), ("Voice Line", "voiceline"),
    ("Dialogue", "dialogue"), ("Narration", "narration"), ("Crowd", "crowd"), ("Ambience Bed", "ambiencebed"),
    ("Wind Audio", "windaudio"), ("Rain Audio", "rainaudio"), ("Water Audio", "wateraudio"),
    ("Forest Audio", "forestaudio"), ("City Audio", "cityaudio"), ("Interior Audio", "interioraudio"),
    ("Reverb Zone", "reverbzone"), ("Occlusion Zone", "occlusionzone"), ("Music Bed", "musicbed"),
    ("Adaptive Music", "adaptivemusic"), ("Combat Music", "combatmusic"), ("Exploration Music", "explorationmusic"),
    ("Stinger", "stinger"), ("Transition", "audiotransition"), ("UI Sound", "uisound"),
    ("Notification", "notification"), ("Vehicle Audio", "vehicleaudio"), ("Engine Audio", "engineaudio"),
    ("Animal Audio", "animalaudio"), ("Creature Audio", "creatureaudio"), ("Magic Audio", "magicaudio"),
    ("Mix Snapshot", "mixsnapshot"), ("Accessibility Audio", "audioaccessibility"),
    ("Mobile Audio", "mobileaudio"), ("Audio Debug", "audiodebug"), ("Audio Profiling", "audioprofiling"),
]

# ------------------------------------------------------------- round 7 :: P GAMEPLAY
ASPECTS_P = [
    ("Attributes",           "stats",        "base values, layered modifiers and derived statistics"),
    ("Inventory",            "inventory",    "slots, stacking, weight, equipment and crafting"),
    ("Objectives",           "quest",        "objectives, prerequisites, progress and rewards"),
    ("Combat Resolution",    "combat",       "accuracy, mitigation, criticals, statuses and death"),
    ("State Machine",        "orchestrator", "the phase machine that drives this gameplay loop"),
    ("Rule Pipeline",        "pipeline",     "ordered rules applied to every gameplay event"),
    ("Event Ledger",         "ledger",       "auditable journal of gameplay events"),
    ("Balance Analysis",     "analyzer",     "distribution, outlier and pacing analysis"),
    ("Difficulty Controller","controller",   "closed-loop tuning toward a target challenge"),
    ("Content Registry",     "registry",     "catalogue of the definitions this loop instantiates"),
    ("Save Codec",           "codec",        "persistence, diffing and checksum of gameplay state"),
    ("Recovery",             "recovery",     "checkpoint and rollback of the gameplay state"),
]

AREAS_P = [
    ("Player Character", "playercharacter"), ("Attribute", "attribute"), ("Skill", "skill"),
    ("Ability", "ability"), ("Talent Tree", "talenttree"), ("Progression", "progression"),
    ("Experience", "experience"), ("Level Up", "levelup"), ("Inventory", "inventorysys"),
    ("Equipment", "equipment"), ("Loot", "loot"), ("Rarity", "rarity"), ("Crafting", "crafting"),
    ("Gathering", "gathering"), ("Building", "buildingsys"), ("Economy", "playereconomy"),
    ("Shop", "shop"), ("Trading", "trading"), ("Currency", "currency"), ("Quest", "questsys"),
    ("Objective", "objective"), ("Dialogue Choice", "dialoguechoice"), ("Reputation", "playerreputation"),
    ("Combat", "combatsys"), ("Melee", "melee"), ("Ranged", "ranged"), ("Damage", "damage"),
    ("Status Effect", "statuseffect"), ("Cooldown", "cooldown"), ("Threat", "threat"),
    ("Death And Respawn", "deathrespawn"), ("Checkpoint", "checkpoint"), ("Score", "score"),
    ("Match", "match"), ("Team", "team"), ("Party", "party"), ("Matchmaking", "matchmaking"),
    ("Difficulty", "difficulty"), ("Tutorial", "tutorial"), ("Gameplay Debug", "gameplaydebug"),
]

# ---------------------------------------------------------------- round 7 :: Q UI/UX
ASPECTS_Q = [
    ("Responsive Layout",     "flex",     "flex solving with safe areas, weights and breakpoints"),
    ("Widget Tree",           "widget",   "retained widget nodes, properties, bindings and rendering"),
    ("Input Mapping",         "inputmap", "one action bound to touch, gamepad, keyboard and mouse"),
    ("Transition",            "tween",    "eased, delayed, looped and sequenced motion"),
    ("Navigation Graph",      "graph",    "screens, routes and shortest path between them"),
    ("Theme Composition",     "composer", "blending of theme signals into the final appearance"),
    ("Localization Registry", "registry", "catalogue of strings, plurals and locale metadata"),
    ("Interaction Ledger",    "ledger",   "auditable journal of what the player actually touched"),
    ("Accessibility Policy",  "policy",   "rules enforcing contrast, target size and motion limits"),
    ("Frame Budget",          "budgeter", "per-frame layout and draw budget for the interface"),
    ("Usability Analysis",    "analyzer", "reachability, latency and abandonment analysis"),
    ("Recovery",              "recovery", "checkpoint and rollback of the interface state"),
]

AREAS_Q = [
    ("Screen", "screen"), ("Panel", "panel"), ("Button", "button"), ("Label", "label"),
    ("Icon", "icon"), ("List", "list"), ("Grid", "grid"), ("Scroll View", "scrollview"),
    ("Modal", "modal"), ("Toast", "toast"), ("Tooltip", "tooltip"), ("Menu", "menu"),
    ("Tab Bar", "tabbar"), ("Navigation", "navigation"), ("Head Up Display", "hud"),
    ("Health Bar", "healthbar"), ("Minimap", "minimap"), ("Compass", "compass"),
    ("Inventory Screen", "inventoryscreen"), ("Quest Log", "questlog"), ("Map Screen", "mapscreen"),
    ("Settings Screen", "settingsscreen"), ("Virtual Joystick", "virtualjoystick"),
    ("Touch Button", "touchbutton"), ("Gesture", "gesture"), ("Haptics", "haptics"),
    ("Gamepad Focus", "gamepadfocus"), ("Keyboard Focus", "keyboardfocus"), ("Safe Area", "safearea"),
    ("Responsive Breakpoint", "breakpoint"), ("Theme", "uitheme"), ("Localization", "localization"),
    ("Accessibility", "uiaccessibility"), ("UI Debug", "uidebug"),
]

# ------------------------------------------------------------ round 7 :: R NETWORKING
ASPECTS_R = [
    ("Replication",                "replicator", "authoritative entity state, interest and delta snapshots"),
    ("Time Sync",                  "netclock",   "offset estimation, outlier rejection and jitter buffering"),
    ("Prediction And Reconciliation","prediction","client simulation, correction and input replay"),
    ("Transport Graph",            "network",    "topology, capacity and routing between endpoints"),
    ("Bandwidth Budget",           "budgeter",   "bytes per second shared between competing streams"),
    ("Serialization Codec",        "codec",      "compact encoding, diffing and checksum of payloads"),
    ("Interest Streaming",         "streamer",   "distance-driven residency of replicated content"),
    ("Rate Guard",                 "guard",      "token-bucket protection against floods and abuse"),
    ("Session Registry",           "registry",   "catalogue of sessions, players and their metadata"),
    ("Audit Ledger",               "ledger",     "auditable journal of the traffic and its decisions"),
    ("Latency Analysis",           "analyzer",   "round trip, jitter and loss analysis"),
    ("Recovery",                   "recovery",   "reconnection, resynchronization and rollback"),
]

AREAS_R = [
    ("Session", "session"), ("Connection", "connection"), ("Handshake", "handshake"),
    ("Authentication", "netauth"), ("Player State", "playerstate"), ("Entity Replication", "entityreplication"),
    ("Transform Replication", "transformreplication"), ("Property Replication", "propertyreplication"),
    ("Remote Event", "remoteevent"), ("Remote Function", "remotefunction"), ("Reliable Channel", "reliablechannel"),
    ("Unreliable Channel", "unreliablechannel"), ("Delta Compression", "deltacompression"),
    ("Snapshot", "snapshot"), ("Interpolation", "interpolation"), ("Extrapolation", "extrapolation"),
    ("Client Prediction", "clientprediction"), ("Server Reconciliation", "serverreconciliation"),
    ("Lag Compensation", "lagcompensation"), ("Interest Management", "interestmanagement"),
    ("Area Of Interest", "areaofinterest"), ("Bandwidth", "bandwidth"), ("Rate Limiting", "ratelimiting"),
    ("Anti Cheat", "anticheat"), ("Server Authority", "serverauthority"), ("Cross Server", "crossserver"),
    ("Data Persistence", "netpersistence"), ("Matchmaking Transport", "matchmakingtransport"),
    ("Reconnection", "reconnection"), ("Network Debug", "networkdebug"),
]


CATEGORIES = {
    "A": dict(family="UES / CORE", prefix="core", areas=AREAS_A, aspects=ASPECTS_A,
              doc="Kernel-level engine capability: the UES foundation every other ARKHER framework stands on."),
    "S": dict(family="D-O15 OPTIMIZATION", prefix="do15", areas=AREAS_S, aspects=ASPECTS_S,
              doc="D-O15 optimization capability: measure, budget, predict, degrade gracefully, restore."),
    "X": dict(family="SECURITY / RELIABILITY", prefix="security", areas=AREAS_X, aspects=ASPECTS_X,
              doc="Security and reliability capability: nothing enters the engine unvalidated or ungoverned."),
    "B": dict(family="ARKHER STUDIO / IDE", prefix="studio", areas=AREAS_B, aspects=ASPECTS_B,
              doc="ARKHER Studio capability: the authoring environment, its documents, panels, tools and history."),
    "U": dict(family="SCRIPTING / CODE INTELLIGENCE", prefix="code", areas=AREAS_U, aspects=ASPECTS_U,
              doc="Scripting capability: reading, understanding, transforming, generating and running ARKHER code."),
    "Y": dict(family="COLLABORATION / PRODUCTION", prefix="collab", areas=AREAS_Y, aspects=ASPECTS_Y,
              doc="Collaboration capability: many creators, one project, with review, merge, release and audit."),
    "C": dict(family="SCENE / WORLD", prefix="world", areas=AREAS_C, aspects=ASPECTS_C,
              doc="World capability: what exists, where it is, who owns it, and how it keeps living."),
    "D": dict(family="TERRAIN", prefix="terrain", areas=AREAS_D, aspects=ASPECTS_D,
              doc="ARKHER Terrain Framework capability: sculpt, erode, paint, stream and mesh the ground itself."),
    "M": dict(family="PROCEDURAL", prefix="proc", areas=AREAS_M, aspects=ASPECTS_M,
              doc="Procedural capability: deterministic synthesis of worlds, cities, structures and detail from a seed."),
    "E": dict(family="MATERIALS", prefix="material", areas=AREAS_E, aspects=ASPECTS_E,
              doc="ARKHER Material Framework capability: how every surface in the world is defined, layered, worn and afforded."),
    "F": dict(family="RENDERING", prefix="render", areas=AREAS_F, aspects=ASPECTS_F,
              doc="Rendering capability: the frame itself - declared, culled, lit, budgeted, resolved and paced."),
    "G": dict(family="NEURAL / RECONSTRUCTION", prefix="neural", areas=AREAS_G, aspects=ASPECTS_G,
              doc="ARKHER Reconstruction and Neural Intelligence capability: predict, reconstruct and verify instead of brute force."),
    "H": dict(family="PHYSICS", prefix="physics", areas=AREAS_H, aspects=ASPECTS_H,
              doc="ARKHER Physics Abstraction capability: mass, contact, constraint and motion, deterministic and budgeted."),
    "I": dict(family="ANIMATION", prefix="anim", areas=AREAS_I, aspects=ASPECTS_I,
              doc="ARKHER Animation Framework capability: skeletons, clips, layers, IK and physical blending."),
    "J": dict(family="CHARACTERS / DIGITAL HUMANS", prefix="character", areas=AREAS_J, aspects=ASPECTS_J,
              doc="ARKHER Digital Human capability: a body that moves, reacts, dresses, ages and scales to a crowd."),
    "K": dict(family="NPC / NEURAL MIND NETWORK", prefix="npc", areas=AREAS_K, aspects=ASPECTS_K,
              doc="ARKHER NMN capability: minds that perceive, remember, feel, plan, move and live together."),
    "L": dict(family="WORLD SIMULATION", prefix="sim", areas=AREAS_L, aspects=ASPECTS_L,
              doc="ARKHER Living World capability: a world that keeps living, at the fidelity the observer deserves."),
    "N": dict(family="VFX", prefix="vfx", areas=AREAS_N, aspects=ASPECTS_N,
              doc="ARKHER VFX Framework capability: emission, simulation, forces and trails inside one shared budget."),
    "O": dict(family="AUDIO", prefix="audio", areas=AREAS_O, aspects=ASPECTS_O,
              doc="ARKHER Audio Framework capability: buses, DSP, spatialization and music that reacts to the world."),
    "P": dict(family="GAMEPLAY", prefix="play", areas=AREAS_P, aspects=ASPECTS_P,
              doc="ARKHER Gameplay Framework capability: attributes, items, objectives, combat and progression."),
    "Q": dict(family="UI / UX", prefix="ui", areas=AREAS_Q, aspects=ASPECTS_Q,
              doc="ARKHER Interface Framework capability: responsive, themed, accessible interfaces on every device."),
    "R": dict(family="NETWORKING", prefix="net", areas=AREAS_R, aspects=ASPECTS_R,
              doc="ARKHER Networking Framework capability: authoritative replication, prediction and bandwidth discipline."),
}
